"use client";

import { useSyncExternalStore } from "react";
import { deadlineFetch } from "@/lib/net";
import {
  PERSONAS,
  forSpeech,
  helloParts,
  type PersonaId,
  type SpeechPart,
} from "@/lib/voice-lines";

export { PERSONAS, type PersonaId };

/**
 * صوت وين, live — the third rendering path.
 *
 * The clip library covers every sentence that could be written down in
 * advance, which is most of them and all of the ones worth paying to record.
 * What it cannot cover is a sentence assembled at runtime, and that is exactly
 * where شوق stopped being herself: the browser's own Arabic voice took over,
 * and the drop from a Kuwaiti woman to a robot is the loudest thing on the
 * page — louder than anything either voice actually says.
 *
 * The bridge is an n8n webhook that holds the ElevenLabs key server-side, so
 * the static export still ships no credential; that constraint is the reason
 * the clip pipeline exists at all and it is not being relaxed here. The
 * workflow renders the same voice with the same settings the clips were
 * recorded with — its «اختر الصوت» node and `scripts/gen-voice.mjs` carry the
 * same table on purpose, because a clip and a live sentence are heard one
 * after the other inside a single utterance, and any difference between them
 * is audible as the speaker changing mid-sentence.
 *
 * Unset, nothing about the site changes. Set and unreachable, the browser
 * voice speaks after at most TTS_DEADLINE_MS. This is an upgrade to a path
 * that already worked, never a dependency.
 */
const TTS_URL = process.env.NEXT_PUBLIC_WAIN_TTS_URL ?? "";

/**
 * How long to wait for the bridge before giving the line to the browser.
 *
 * The honest cost of this feature: a configured-but-slow bridge buys silence,
 * and silence is worse than the robot. Four seconds is about the longest a
 * visitor will wait for an answer they asked for out loud — a render plus a
 * transfer on a Kuwaiti mobile connection normally lands well inside it, and
 * anything that does not, isn't going to.
 */
const TTS_DEADLINE_MS = 4_000;

/**
 * صوت وين — the playback engine.
 *
 * Two rendering paths, chosen per utterance:
 *
 * 1. Pre-rendered ElevenLabs clips (public/voice/<persona>/<key>.mp3,
 *    catalogued by public/voice/manifest.json, generated by
 *    scripts/gen-voice.mjs). Used when every required part of the utterance
 *    has a clip for the active persona — never mixed with synthetic speech.
 * 2. The browser's own Arabic voice (Web Speech API) otherwise, so the
 *    feature works before any clips have been generated and for dynamic
 *    sentences no clip can exist for.
 *
 * The persona and on/off switch live in localStorage only — nothing leaves
 * the device, matching the site's no-tracking promise. Speech only ever
 * starts from a user gesture (the toggle or a play button), which also
 * satisfies browser autoplay policies.
 */

type Manifest = { version: number; clips: Record<string, string> };

type VoiceState = {
  enabled: boolean;
  persona: PersonaId;
  speaking: boolean;
};

const PREF_ENABLED = "wain-voice-enabled";
const PREF_PERSONA = "wain-voice-persona";

function readPrefs(): Pick<VoiceState, "enabled" | "persona"> {
  if (typeof window === "undefined") return { enabled: false, persona: "shouq" };
  try {
    const persona = window.localStorage.getItem(PREF_PERSONA);
    return {
      enabled: window.localStorage.getItem(PREF_ENABLED) === "1",
      persona: persona === "salem" ? "salem" : "shouq",
    };
  } catch {
    return { enabled: false, persona: "shouq" };
  }
}

function writePref(key: string, value: string) {
  try {
    window.localStorage.setItem(key, value);
  } catch {
    // Storage unavailable (private mode) — the choice just won't persist.
  }
}

const SERVER_SNAPSHOT: VoiceState = { enabled: false, persona: "shouq", speaking: false };

let snapshot: VoiceState = { ...SERVER_SNAPSHOT, ...readPrefs() };
const listeners = new Set<() => void>();

function update(patch: Partial<VoiceState>) {
  snapshot = { ...snapshot, ...patch };
  listeners.forEach((l) => l());
}

function subscribe(listener: () => void): () => void {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

export function useVoice(): VoiceState {
  return useSyncExternalStore(
    subscribe,
    () => snapshot,
    () => SERVER_SNAPSHOT
  );
}

// --- Clip manifest ---------------------------------------------------------

const EMPTY_MANIFEST: Manifest = { version: 0, clips: {} };
let manifestPromise: Promise<Manifest> | null = null;

function loadManifest(): Promise<Manifest> {
  manifestPromise ??= fetch("/voice/manifest.json")
    .then((r) => (r.ok ? (r.json() as Promise<Manifest>) : EMPTY_MANIFEST))
    .catch(() => EMPTY_MANIFEST);
  return manifestPromise;
}

/** Clip sources for the utterance, or null when any required part is missing
 * and the whole utterance should fall back to synthetic speech. */
function resolveClips(parts: SpeechPart[], manifest: Manifest): string[] | null {
  const srcs: string[] = [];
  for (const part of parts) {
    if (!part.key) {
      if (part.optional) continue;
      return null;
    }
    const src = manifest.clips[`${snapshot.persona}/${part.key}`];
    if (!src) return null;
    srcs.push(src);
  }
  return srcs.length > 0 ? srcs : null;
}

// --- Playback --------------------------------------------------------------

let audio: HTMLAudioElement | null = null;
let queue: string[] = [];
// Guards against a stale async manifest resolution starting playback after
// the user has already stopped or started a newer utterance.
let generation = 0;

function playNext() {
  const src = queue.shift();
  if (!src || !audio) {
    update({ speaking: false });
    return;
  }
  audio.src = src;
  audio.play().catch(() => {
    queue = [];
    update({ speaking: false });
  });
}

/**
 * Unlock audio while a user gesture is still on the stack.
 *
 * iOS Safari will only let an <audio> element or speechSynthesis start from
 * inside a user gesture — and "inside" means the same task, not merely "some
 * time after a tap". Everything this module speaks goes through speak(),
 * which awaits the clip manifest first, so by the time it plays, the gesture
 * is long over and iOS refuses.
 *
 * That was survivable while the only entry point was the voice toggle, whose
 * greeting was itself the unlock. وين AI deliberately skips the greeting — it
 * is about to navigate to an answer that speaks for itself — which left the
 * assistant silent on iPhones. So the gesture handler calls this instead: a
 * muted zero-length play and an empty utterance, both synchronous, purely to
 * spend the gesture's permission before it expires.
 */
export function primeAudio() {
  if (typeof window === "undefined") return;
  // Start the manifest fetch on the gesture instead of leaving it to speak(),
  // which awaits it. The first answer of a session paid a round trip AFTER the
  // tap and before any sound — silence exactly where the visitor is waiting to
  // find out whether the thing works. It is memoised, so only the first
  // utterance was ever slow; this makes that one overlap the gesture.
  void loadManifest();
  try {
    const el = ensureAudio();
    el.muted = true;
    const p = el.play();
    // Older Safari returns undefined rather than a promise here.
    void p?.then(
      () => {
        el.pause();
        el.muted = false;
      },
      () => {
        el.muted = false;
      }
    );
  } catch {
    /* nothing to unlock */
  }
  try {
    // Same trick for the synthetic path: an empty utterance is inaudible but
    // still counts as the gesture-initiated first speak() Safari waits for.
    const synth = window.speechSynthesis;
    if (synth) synth.speak(new SpeechSynthesisUtterance(""));
  } catch {
    /* no speech synthesis */
  }
}

function ensureAudio(): HTMLAudioElement {
  if (!audio) {
    audio = new Audio();
    audio.preload = "auto";
    audio.onended = playNext;
    audio.onerror = () => {
      queue = [];
      update({ speaking: false });
    };
  }
  return audio;
}

function pickArabicVoice(): SpeechSynthesisVoice | undefined {
  const voices = window.speechSynthesis?.getVoices() ?? [];
  return (
    voices.find((v) => v.lang?.toLowerCase().startsWith("ar-kw")) ??
    voices.find((v) => v.lang?.toLowerCase().startsWith("ar"))
  );
}

function speakFallback(text: string) {
  const synth = window.speechSynthesis;
  if (!synth) return;
  const utterance = new SpeechSynthesisUtterance(forSpeech(text));
  utterance.lang = "ar-KW";
  // Guarded because the failure mode is total silence, not merely the wrong
  // accent: this assignment throws if the engine rejects the voice object —
  // a stale entry from a getVoices() list the browser has since replaced is
  // the realistic way that happens — and an exception here means she says
  // nothing at all. Better her default voice than no voice.
  try {
    const voice = pickArabicVoice();
    if (voice) utterance.voice = voice;
  } catch {
    /* the engine keeps its default */
  }
  // 1.02 rather than the 1.0 default: the browser voices read Arabic a shade
  // slower than a Kuwaiti speaker does. Small on purpose — past about 1.1 the
  // connecting strokes slur and the dialect words are the first to go.
  utterance.rate = 1.02;
  utterance.onend = () => update({ speaking: false });
  utterance.onerror = () => update({ speaking: false });
  update({ speaking: true });
  synth.speak(utterance);
}

/** The object URL of the last live render, so it can be revoked. One at a
 *  time is all this ever holds: a new utterance stops the previous one. */
let liveUrl: string | null = null;
function releaseLive() {
  if (liveUrl) {
    URL.revokeObjectURL(liveUrl);
    liveUrl = null;
  }
}

/** Render one sentence through the bridge. Resolves false for every reason a
 *  caller would do the same thing about — unconfigured, offline, slow, non-2xx,
 *  or a body that is not audio — so the fallback has exactly one condition. */
async function speakLive(text: string, mine: number): Promise<boolean> {
  if (!TTS_URL) return false;
  releaseLive();
  try {
    const res = await deadlineFetch(TTS_URL, {
      method: "POST",
      headers: { "content-type": "application/json" },
      // forSpeech here for the same reason gen-voice.mjs calls it before
      // recording: what is synthesised has to be the string the fallback would
      // have uttered, digits and dashes included, or the two paths say
      // different things.
      body: JSON.stringify({ persona: snapshot.persona, text: forSpeech(text) }),
      signal: AbortSignal.timeout(TTS_DEADLINE_MS),
    });
    if (!res.ok) return false;
    const blob = await res.blob();
    // A zero-length or non-audio body plays as silence, and silence is
    // indistinguishable from a working call — the visitor just thinks she
    // ignored them. An error page returned with a 200 is the realistic way
    // that happens.
    if (blob.size < 512 || !blob.type.startsWith("audio/")) return false;
    // The visitor moved on while this was in flight.
    if (mine !== generation) return false;
    liveUrl = URL.createObjectURL(blob);
    update({ speaking: true });
    queue = [liveUrl];
    ensureAudio();
    playNext();
    return true;
  } catch {
    return false;
  }
}

export function speak(parts: SpeechPart[]) {
  if (typeof window === "undefined" || parts.length === 0) return;
  stop();
  const mine = ++generation;
  void loadManifest().then((manifest) => {
    if (mine !== generation) return;
    const clips = resolveClips(parts, manifest);
    if (clips) {
      update({ speaking: true });
      queue = clips;
      ensureAudio();
      playNext();
      return;
    }
    // No clip for this sentence — it was assembled at runtime. Her real voice
    // if the bridge can produce it, the browser's if it cannot.
    const text = parts.map((p) => p.text).join(" ");
    void speakLive(text, mine).then((spoke) => {
      if (mine !== generation || spoke) return;
      speakFallback(text);
    });
  });
}

export function stop() {
  if (typeof window === "undefined") return;
  generation++;
  queue = [];
  if (audio && !audio.paused) audio.pause();
  // A blob URL is a document-lifetime reference to the whole MP3 in memory.
  // Nothing else drops it, and «اسمع الاقتراح» on a place page is a button
  // people press repeatedly.
  releaseLive();
  window.speechSynthesis?.cancel();
  if (snapshot.speaking) update({ speaking: false });
}

// --- Preferences -----------------------------------------------------------

export function setEnabled(enabled: boolean, opts?: { greet?: boolean }) {
  writePref(PREF_ENABLED, enabled ? "1" : "0");
  update({ enabled });
  if (enabled) {
    // The greeting doubles as the audio unlock (we're inside a click) and as
    // a preview of the chosen voice. وين AI passes greet:false — it is about
    // to navigate to an answer that speaks for itself, and the greeting would
    // be cut off mid-word by that answer's own stop().
    if (opts?.greet !== false) speak(helloParts(snapshot.persona));
  } else {
    stop();
  }
}

export function setPersona(persona: PersonaId) {
  if (persona === snapshot.persona) return;
  writePref(PREF_PERSONA, persona);
  update({ persona });
  if (snapshot.enabled) speak(helloParts(persona));
}
