"use client";

import { useSyncExternalStore } from "react";
import { deadlineFetch } from "@/lib/net";
import {
  PERSONAS,
  forSpeech,
  helloParts,
  type PersonaId,
  type SpeechPart,
} from "@/lib/voice-lines";

export { PERSONAS, type PersonaId };

/**
 * صوت وين, live — the third rendering path.
 *
 * The clip library covers every sentence that could be written down in
 * advance, which is most of them and all of the ones worth paying to record.
 * What it cannot cover is a sentence assembled at runtime, and that is exactly
 * where شوق stopped being herself: the browser's own Arabic voice took over,
 * and the drop from a Kuwaiti woman to a robot is the loudest thing on the
 * page — louder than anything either voice actually says.
 *
 * The bridge is an n8n webhook that holds the ElevenLabs key server-side, so
 * the static export still ships no credential; that constraint is the reason
 * the clip pipeline exists at all and it is not being relaxed here. The
 * workflow renders the same voice with the same settings the clips were
 * recorded with — its «اختر الصوت» node and `scripts/gen-voice.mjs` carry the
 * same table on purpose, because a clip and a live sentence are heard one
 * after the other inside a single utterance, and any difference between them
 * is audible as the speaker changing mid-sentence.
 *
 * Unset, nothing about the site changes. Set and unreachable, the browser
 * voice speaks after at most TTS_DEADLINE_MS. This is an upgrade to a path
 * that already worked, never a dependency.
 */
const TTS_URL = process.env.NEXT_PUBLIC_WAIN_TTS_URL ?? "";

/**
 * How long to wait for the bridge before giving the line to the browser.
 *
 * The honest cost of this feature: a configured-but-slow bridge buys silence,
 * and silence is worse than the robot. Four seconds is about the longest a
 * visitor will wait for an answer they asked for out loud — a render plus a
 * transfer on a Kuwaiti mobile connection normally lands well inside it, and
 * anything that does not, isn't going to.
 */
const TTS_DEADLINE_MS = 4_000;

/**
 * The beat between one sentence and the next, on the recorded path.
 *
 * Clips are recorded a sentence at a time and were played back to back, so the
 * pause a listener heard between them was not a decision — it was however long
 * the browser took to fetch the next file. Measured across the five clips of a
 * real answer: 8ms on a local connection, 358ms on a 350ms link. The same
 * speaker, rushed on wifi and hesitant on mobile, and 1.9 seconds of the answer
 * spent in dead air that all lands in the gaps where somebody is waiting.
 *
 * `prefetch` below takes the network out of it. This puts back a beat that is
 * the same on every connection.
 *
 * 200ms is the short end of an ordinary sentence boundary. Short on purpose:
 * each clip already carries a little silence of its own at both ends, and two
 * pauses stacked read as a hesitation rather than a breath.
 */
const SENTENCE_GAP_MS = 200;

/**
 * صوت وين — the playback engine.
 *
 * Two rendering paths, chosen per utterance:
 *
 * 1. Pre-rendered ElevenLabs clips (public/voice/<persona>/<key>.mp3,
 *    catalogued by public/voice/manifest.json, generated by
 *    scripts/gen-voice.mjs). Used when every required part of the utterance
 *    has a clip for the active persona — never mixed with synthetic speech.
 * 2. The browser's own Arabic voice (Web Speech API) otherwise, so the
 *    feature works before any clips have been generated and for dynamic
 *    sentences no clip can exist for.
 *
 * The persona and on/off switch live in localStorage only — nothing leaves
 * the device, matching the site's no-tracking promise. Speech only ever
 * starts from a user gesture (the toggle or a play button), which also
 * satisfies browser autoplay policies.
 */

type Manifest = { version: number; clips: Record<string, string> };

type VoiceState = {
  enabled: boolean;
  persona: PersonaId;
  speaking: boolean;
};

const PREF_ENABLED = "wain-voice-enabled";
const PREF_PERSONA = "wain-voice-persona";

function readPrefs(): Pick<VoiceState, "enabled" | "persona"> {
  if (typeof window === "undefined") return { enabled: false, persona: "shouq" };
  try {
    const persona = window.localStorage.getItem(PREF_PERSONA);
    return {
      enabled: window.localStorage.getItem(PREF_ENABLED) === "1",
      persona: persona === "salem" ? "salem" : "shouq",
    };
  } catch {
    return { enabled: false, persona: "shouq" };
  }
}

function writePref(key: string, value: string) {
  try {
    window.localStorage.setItem(key, value);
  } catch {
    // Storage unavailable (private mode) — the choice just won't persist.
  }
}

const SERVER_SNAPSHOT: VoiceState = { enabled: false, persona: "shouq", speaking: false };

let snapshot: VoiceState = { ...SERVER_SNAPSHOT, ...readPrefs() };
const listeners = new Set<() => void>();

function update(patch: Partial<VoiceState>) {
  snapshot = { ...snapshot, ...patch };
  listeners.forEach((l) => l());
}

function subscribe(listener: () => void): () => void {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

export function useVoice(): VoiceState {
  return useSyncExternalStore(
    subscribe,
    () => snapshot,
    () => SERVER_SNAPSHOT
  );
}

// --- Clip manifest ---------------------------------------------------------

const EMPTY_MANIFEST: Manifest = { version: 0, clips: {} };
let manifestPromise: Promise<Manifest> | null = null;

function loadManifest(): Promise<Manifest> {
  manifestPromise ??= fetch("/voice/manifest.json")
    .then((r) => (r.ok ? (r.json() as Promise<Manifest>) : EMPTY_MANIFEST))
    .catch(() => EMPTY_MANIFEST);
  return manifestPromise;
}

/** Clip sources for the utterance, or null when any required part is missing
 * and the whole utterance should fall back to synthetic speech. */
function resolveClips(parts: SpeechPart[], manifest: Manifest): string[] | null {
  const srcs: string[] = [];
  for (const part of parts) {
    if (!part.key) {
      if (part.optional) continue;
      return null;
    }
    const src = manifest.clips[`${snapshot.persona}/${part.key}`];
    if (!src) return null;
    srcs.push(src);
  }
  return srcs.length > 0 ? srcs : null;
}

// --- Playback --------------------------------------------------------------

let audio: HTMLAudioElement | null = null;
let queue: string[] = [];
// Guards against a stale async manifest resolution starting playback after
// the user has already stopped or started a newer utterance.
let generation = 0;
/** The pause between two clips, held so stop() can cancel it. */
let gapTimer: ReturnType<typeof setTimeout> | null = null;

function clearGap() {
  if (gapTimer !== null) {
    clearTimeout(gapTimer);
    gapTimer = null;
  }
}

/**
 * Pull the rest of the utterance into the HTTP cache while the first clip is
 * still playing.
 *
 * The element fetched each clip at the moment it became due, which is the one
 * moment the visitor can hear. `.mp3` is served with a week of cache (see
 * public/.htaccess), so a plain fetch now means the element finds every later
 * clip already in the cache: measured at 350ms latency, the four gaps after
 * the first drop from ~358ms each to ~6ms, and the number of requests to the
 * server does not change.
 *
 * Not the first clip. The element is already loading that one, and a second
 * request for the same file races it for a connection — warming all five
 * pushed the FIRST clip from 431ms to 771ms while fixing the other four,
 * which moves the delay to the worst possible place: before she has said
 * anything at all.
 *
 * Failures are ignored on purpose. A prefetch that does not arrive costs
 * nothing; the element fetches it the old way when its turn comes.
 */
function prefetch(srcs: string[]) {
  for (const src of srcs.slice(1)) {
    void fetch(src).catch(() => {
      /* the element will fetch it when it is due */
    });
  }
}

function playNext() {
  const src = queue.shift();
  if (!src || !audio) {
    update({ speaking: false });
    return;
  }
  audio.src = src;
  audio.play().catch(() => {
    queue = [];
    update({ speaking: false });
  });
}

/**
 * Unlock audio while a user gesture is still on the stack.
 *
 * iOS Safari will only let an <audio> element or speechSynthesis start from
 * inside a user gesture — and "inside" means the same task, not merely "some
 * time after a tap". Everything this module speaks goes through speak(),
 * which awaits the clip manifest first, so by the time it plays, the gesture
 * is long over and iOS refuses.
 *
 * That was survivable while the only entry point was the voice toggle, whose
 * greeting was itself the unlock. وين AI deliberately skips the greeting — it
 * is about to navigate to an answer that speaks for itself — which left the
 * assistant silent on iPhones. So the gesture handler calls this instead: a
 * muted zero-length play and an empty utterance, both synchronous, purely to
 * spend the gesture's permission before it expires.
 */
export function primeAudio() {
  if (typeof window === "undefined") return;
  // Start the manifest fetch on the gesture instead of leaving it to speak(),
  // which awaits it. The first answer of a session paid a round trip AFTER the
  // tap and before any sound — silence exactly where the visitor is waiting to
  // find out whether the thing works. It is memoised, so only the first
  // utterance was ever slow; this makes that one overlap the gesture.
  void loadManifest();
  try {
    const el = ensureAudio();
    el.muted = true;
    const p = el.play();
    // Older Safari returns undefined rather than a promise here.
    void p?.then(
      () => {
        el.pause();
        el.muted = false;
      },
      () => {
        el.muted = false;
      }
    );
  } catch {
    /* nothing to unlock */
  }
  try {
    // Same trick for the synthetic path: an empty utterance is inaudible but
    // still counts as the gesture-initiated first speak() Safari waits for.
    const synth = window.speechSynthesis;
    if (synth) synth.speak(new SpeechSynthesisUtterance(""));
  } catch {
    /* no speech synthesis */
  }
}

function ensureAudio(): HTMLAudioElement {
  if (!audio) {
    audio = new Audio();
    audio.preload = "auto";
    audio.onended = () => {
      // Last sentence — end the utterance now rather than after a pause
      // nobody is waiting through.
      if (queue.length === 0) {
        update({ speaking: false });
        return;
      }
      // The beat. Pinned to this generation so a stop() during the pause
      // cannot be resumed out of by a timer that was already scheduled.
      const mine = generation;
      clearGap();
      gapTimer = setTimeout(() => {
        gapTimer = null;
        if (mine === generation) playNext();
      }, SENTENCE_GAP_MS);
    };
    audio.onerror = () => {
      queue = [];
      clearGap();
      update({ speaking: false });
    };
  }
  return audio;
}

function pickArabicVoice(): SpeechSynthesisVoice | undefined {
  const voices = window.speechSynthesis?.getVoices() ?? [];
  return (
    voices.find((v) => v.lang?.toLowerCase().startsWith("ar-kw")) ??
    voices.find((v) => v.lang?.toLowerCase().startsWith("ar"))
  );
}

/**
 * The browser's own voice — one utterance per sentence, not one per answer.
 *
 * No clips ship yet (public/voice/manifest.json is empty until someone runs
 * the generator), so this is the path every visitor actually hears, and it was
 * handed the entire answer as a single string. Measured across all 44 places
 * in both seasons: 170 characters on average and 227 at the longest, which at
 * the pace the recorded clips are spoken — 7.5 characters a second, measured
 * off the fixtures — is 23 seconds of speech in one utterance and 30 at the
 * worst. Chrome stops a single utterance at around fifteen. The cut lands in
 * «أحلى وقت» or the summer warning: the half that answers the question.
 *
 * Splitting is the recommended fix for that ceiling, and it is the right shape
 * regardless of it. The parts already are sentences — that is what a
 * SpeechPart is — so each becomes its own utterance and the engine puts its
 * own boundary between them, which is the same beat SENTENCE_GAP_MS gives the
 * recorded path.
 *
 * They are queued all at once rather than chained on `onend`. The engine keeps
 * the order, and a chain would put the rest of the answer behind an event that
 * some engines do not fire reliably — a stalled chain is silence in the middle
 * of a sentence, which is worse than the ceiling this exists to avoid.
 */
function speakFallback(parts: SpeechPart[], mine: number) {
  const synth = window.speechSynthesis;
  if (!synth) return;
  const lines = parts.map((p) => forSpeech(p.text)).filter((t) => t.length > 0);
  if (lines.length === 0) return;

  // Picked once for the whole answer. Guarded because the failure mode is
  // total silence, not merely the wrong accent: this assignment throws if the
  // engine rejects the voice object — a stale entry from a getVoices() list
  // the browser has since replaced is the realistic way that happens — and an
  // exception here means she says nothing at all. Better her default voice
  // than no voice.
  let voice: SpeechSynthesisVoice | undefined;
  try {
    voice = pickArabicVoice();
  } catch {
    /* the engine keeps its default */
  }

  update({ speaking: true });
  // Only the last sentence ending means she has finished. Both handlers are
  // pinned to this generation because cancel() fires `error` on every pending
  // utterance, and a newer answer is already speaking by then.
  const done = () => {
    if (mine === generation) update({ speaking: false });
  };
  lines.forEach((line, i) => {
    const utterance = new SpeechSynthesisUtterance(line);
    utterance.lang = "ar-KW";
    try {
      if (voice) utterance.voice = voice;
    } catch {
      /* the engine keeps its default */
    }
    // 1.02 rather than the 1.0 default: the browser voices read Arabic a shade
    // slower than a Kuwaiti speaker does. Small on purpose — past about 1.1 the
    // connecting strokes slur and the dialect words are the first to go.
    utterance.rate = 1.02;
    if (i === lines.length - 1) utterance.onend = done;
    utterance.onerror = done;
    synth.speak(utterance);
  });
}

/** The object URL of the last live render, so it can be revoked. One at a
 *  time is all this ever holds: a new utterance stops the previous one. */
let liveUrl: string | null = null;
function releaseLive() {
  if (liveUrl) {
    URL.revokeObjectURL(liveUrl);
    liveUrl = null;
  }
}

/** Render one sentence through the bridge. Resolves false for every reason a
 *  caller would do the same thing about — unconfigured, offline, slow, non-2xx,
 *  or a body that is not audio — so the fallback has exactly one condition. */
async function speakLive(text: string, mine: number): Promise<boolean> {
  if (!TTS_URL) return false;
  releaseLive();
  try {
    const res = await deadlineFetch(TTS_URL, {
      method: "POST",
      headers: { "content-type": "application/json" },
      // forSpeech here for the same reason gen-voice.mjs calls it before
      // recording: what is synthesised has to be the string the fallback would
      // have uttered, digits and dashes included, or the two paths say
      // different things.
      body: JSON.stringify({ persona: snapshot.persona, text: forSpeech(text) }),
      signal: AbortSignal.timeout(TTS_DEADLINE_MS),
    });
    if (!res.ok) return false;
    const blob = await res.blob();
    // A zero-length or non-audio body plays as silence, and silence is
    // indistinguishable from a working call — the visitor just thinks she
    // ignored them. An error page returned with a 200 is the realistic way
    // that happens.
    if (blob.size < 512 || !blob.type.startsWith("audio/")) return false;
    // The visitor moved on while this was in flight.
    if (mine !== generation) return false;
    liveUrl = URL.createObjectURL(blob);
    update({ speaking: true });
    queue = [liveUrl];
    ensureAudio();
    playNext();
    return true;
  } catch {
    return false;
  }
}

export function speak(parts: SpeechPart[]) {
  if (typeof window === "undefined" || parts.length === 0) return;
  stop();
  const mine = ++generation;
  void loadManifest().then((manifest) => {
    if (mine !== generation) return;
    const clips = resolveClips(parts, manifest);
    if (clips) {
      update({ speaking: true });
      queue = clips;
      // Before the first play, not after: the whole point is that the later
      // clips are already in the cache by the time the first one ends.
      prefetch(clips);
      ensureAudio();
      playNext();
      return;
    }
    // No clip for this sentence — it was assembled at runtime. Her real voice
    // if the bridge can produce it, the browser's if it cannot. The bridge
    // gets the whole answer in one render, punctuation and all, so it paces
    // itself; the browser gets it a sentence at a time.
    const text = parts.map((p) => p.text).join(" ");
    void speakLive(text, mine).then((spoke) => {
      if (mine !== generation || spoke) return;
      speakFallback(parts, mine);
    });
  });
}

export function stop() {
  if (typeof window === "undefined") return;
  generation++;
  queue = [];
  // A pause between two sentences is still an utterance in progress: without
  // this, stopping during the beat let the next clip start 200ms later.
  clearGap();
  if (audio && !audio.paused) audio.pause();
  // A blob URL is a document-lifetime reference to the whole MP3 in memory.
  // Nothing else drops it, and «اسمع الاقتراح» on a place page is a button
  // people press repeatedly.
  releaseLive();
  window.speechSynthesis?.cancel();
  if (snapshot.speaking) update({ speaking: false });
}

// --- Preferences -----------------------------------------------------------

export function setEnabled(enabled: boolean, opts?: { greet?: boolean }) {
  writePref(PREF_ENABLED, enabled ? "1" : "0");
  update({ enabled });
  if (enabled) {
    // The greeting doubles as the audio unlock (we're inside a click) and as
    // a preview of the chosen voice. وين AI passes greet:false — it is about
    // to navigate to an answer that speaks for itself, and the greeting would
    // be cut off mid-word by that answer's own stop().
    if (opts?.greet !== false) speak(helloParts(snapshot.persona));
  } else {
    stop();
  }
}

export function setPersona(persona: PersonaId) {
  if (persona === snapshot.persona) return;
  writePref(PREF_PERSONA, persona);
  update({ persona });
  if (snapshot.enabled) speak(helloParts(persona));
}
