"use client";

import { useSyncExternalStore } from "react";
import { PERSONAS, helloParts, type PersonaId, type SpeechPart } from "@/lib/voice-lines";

export { PERSONAS, type PersonaId };

/**
 * صوت وين — the playback engine.
 *
 * Two rendering paths, chosen per utterance:
 *
 * 1. Pre-rendered ElevenLabs clips (public/voice/<persona>/<key>.mp3,
 *    catalogued by public/voice/manifest.json, generated by
 *    scripts/gen-voice.mjs). Used when every required part of the utterance
 *    has a clip for the active persona — never mixed with synthetic speech.
 * 2. The browser's own Arabic voice (Web Speech API) otherwise, so the
 *    feature works before any clips have been generated and for dynamic
 *    sentences no clip can exist for.
 *
 * The persona and on/off switch live in localStorage only — nothing leaves
 * the device, matching the site's no-tracking promise. Speech only ever
 * starts from a user gesture (the toggle or a play button), which also
 * satisfies browser autoplay policies.
 */

type Manifest = { version: number; clips: Record<string, string> };

type VoiceState = {
  enabled: boolean;
  persona: PersonaId;
  speaking: boolean;
};

const PREF_ENABLED = "wain-voice-enabled";
const PREF_PERSONA = "wain-voice-persona";

function readPrefs(): Pick<VoiceState, "enabled" | "persona"> {
  if (typeof window === "undefined") return { enabled: false, persona: "shouq" };
  try {
    const persona = window.localStorage.getItem(PREF_PERSONA);
    return {
      enabled: window.localStorage.getItem(PREF_ENABLED) === "1",
      persona: persona === "salem" ? "salem" : "shouq",
    };
  } catch {
    return { enabled: false, persona: "shouq" };
  }
}

function writePref(key: string, value: string) {
  try {
    window.localStorage.setItem(key, value);
  } catch {
    // Storage unavailable (private mode) — the choice just won't persist.
  }
}

const SERVER_SNAPSHOT: VoiceState = { enabled: false, persona: "shouq", speaking: false };

let snapshot: VoiceState = { ...SERVER_SNAPSHOT, ...readPrefs() };
const listeners = new Set<() => void>();

function update(patch: Partial<VoiceState>) {
  snapshot = { ...snapshot, ...patch };
  listeners.forEach((l) => l());
}

function subscribe(listener: () => void): () => void {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

export function useVoice(): VoiceState {
  return useSyncExternalStore(
    subscribe,
    () => snapshot,
    () => SERVER_SNAPSHOT
  );
}

// --- Clip manifest ---------------------------------------------------------

const EMPTY_MANIFEST: Manifest = { version: 0, clips: {} };
let manifestPromise: Promise<Manifest> | null = null;

function loadManifest(): Promise<Manifest> {
  manifestPromise ??= fetch("/voice/manifest.json")
    .then((r) => (r.ok ? (r.json() as Promise<Manifest>) : EMPTY_MANIFEST))
    .catch(() => EMPTY_MANIFEST);
  return manifestPromise;
}

/** Clip sources for the utterance, or null when any required part is missing
 * and the whole utterance should fall back to synthetic speech. */
function resolveClips(parts: SpeechPart[], manifest: Manifest): string[] | null {
  const srcs: string[] = [];
  for (const part of parts) {
    if (!part.key) {
      if (part.optional) continue;
      return null;
    }
    const src = manifest.clips[`${snapshot.persona}/${part.key}`];
    if (!src) return null;
    srcs.push(src);
  }
  return srcs.length > 0 ? srcs : null;
}

// --- Playback --------------------------------------------------------------

let audio: HTMLAudioElement | null = null;
let queue: string[] = [];
// Guards against a stale async manifest resolution starting playback after
// the user has already stopped or started a newer utterance.
let generation = 0;

function playNext() {
  const src = queue.shift();
  if (!src || !audio) {
    update({ speaking: false });
    return;
  }
  audio.src = src;
  audio.play().catch(() => {
    queue = [];
    update({ speaking: false });
  });
}

function ensureAudio(): HTMLAudioElement {
  if (!audio) {
    audio = new Audio();
    audio.preload = "auto";
    audio.onended = playNext;
    audio.onerror = () => {
      queue = [];
      update({ speaking: false });
    };
  }
  return audio;
}

function pickArabicVoice(): SpeechSynthesisVoice | undefined {
  const voices = window.speechSynthesis?.getVoices() ?? [];
  return (
    voices.find((v) => v.lang?.toLowerCase().startsWith("ar-kw")) ??
    voices.find((v) => v.lang?.toLowerCase().startsWith("ar"))
  );
}

function speakFallback(text: string) {
  const synth = window.speechSynthesis;
  if (!synth) return;
  const utterance = new SpeechSynthesisUtterance(text);
  utterance.lang = "ar-KW";
  const voice = pickArabicVoice();
  if (voice) utterance.voice = voice;
  utterance.rate = 1.02;
  utterance.onend = () => update({ speaking: false });
  utterance.onerror = () => update({ speaking: false });
  update({ speaking: true });
  synth.speak(utterance);
}

export function speak(parts: SpeechPart[]) {
  if (typeof window === "undefined" || parts.length === 0) return;
  stop();
  const mine = ++generation;
  void loadManifest().then((manifest) => {
    if (mine !== generation) return;
    const clips = resolveClips(parts, manifest);
    if (clips) {
      update({ speaking: true });
      queue = clips;
      ensureAudio();
      playNext();
    } else {
      speakFallback(parts.map((p) => p.text).join(" "));
    }
  });
}

export function stop() {
  if (typeof window === "undefined") return;
  generation++;
  queue = [];
  if (audio && !audio.paused) audio.pause();
  window.speechSynthesis?.cancel();
  if (snapshot.speaking) update({ speaking: false });
}

// --- Preferences -----------------------------------------------------------

export function setEnabled(enabled: boolean) {
  writePref(PREF_ENABLED, enabled ? "1" : "0");
  update({ enabled });
  if (enabled) {
    // The greeting doubles as the audio unlock (we're inside a click) and as
    // a preview of the chosen voice.
    speak(helloParts(snapshot.persona));
  } else {
    stop();
  }
}

export function setPersona(persona: PersonaId) {
  if (persona === snapshot.persona) return;
  writePref(PREF_PERSONA, persona);
  update({ persona });
  if (snapshot.enabled) speak(helloParts(persona));
}
