-- Wain — database schema for the admin panel.
-- Generated by scripts/gen-schema.mjs from src/lib/places.ts. Do not hand-edit;
-- re-run `npm run db:schema` instead.
--
-- Paste this whole file into the Supabase SQL editor and run it once.

-- ---------------------------------------------------------------------------
-- Who may administer the site.
--
-- Membership here — not merely "is signed in" — is what grants write access.
-- Leaving it at "any authenticated user" would mean anyone who can create an
-- account could edit the site.
-- ---------------------------------------------------------------------------
create table if not exists public.admins (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email   text not null,
  added_at timestamptz not null default now()
);
alter table public.admins enable row level security;

create policy "admins can see the admin list"
  on public.admins for select
  using (exists (select 1 from public.admins a where a.user_id = auth.uid()));

-- ---------------------------------------------------------------------------
-- Places
-- ---------------------------------------------------------------------------
create table if not exists public.places (
  id             uuid primary key default gen_random_uuid(),
  slug           text unique not null check (slug ~ '^[a-z0-9-]+$'),
  name           text not null,
  name_ar        text not null,
  category       text not null check (category in
                   ('landmarks','restaurants','fastfood','coffee',
                    'outdoors','shopping','culture','family')),
  area           text not null,
  area_ar        text not null,
  lat            double precision not null check (lat between -90 and 90),
  lng            double precision not null check (lng between -180 and 180),
  rating         numeric(2,1) not null check (rating between 0 and 5),
  price_level    smallint not null check (price_level between 1 and 3),
  emoji          text not null default '📍',
  tagline_ar     text not null,
  description_ar text not null,
  highlights_ar  text[] not null default '{}',
  best_time_ar   text not null,
  featured       boolean not null default false,
  published      boolean not null default true,
  sort_order     integer not null default 0,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists places_category_idx on public.places (category);
create index if not exists places_sort_idx     on public.places (sort_order, created_at);

-- Keep updated_at honest.
create or replace function public.touch_updated_at() returns trigger
language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

drop trigger if exists places_touch on public.places;
create trigger places_touch before update on public.places
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- Row level security
--
-- Visitors read published rows with the anon key and can do nothing else.
-- Every write requires an authenticated session that is also in admins.
-- ---------------------------------------------------------------------------
alter table public.places enable row level security;

drop policy if exists "anyone can read published places" on public.places;
create policy "anyone can read published places"
  on public.places for select
  using (published = true);

drop policy if exists "admins read every place" on public.places;
create policy "admins read every place"
  on public.places for select
  using (exists (select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admins insert places" on public.places;
create policy "admins insert places"
  on public.places for insert
  with check (exists (select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admins update places" on public.places;
create policy "admins update places"
  on public.places for update
  using (exists (select 1 from public.admins a where a.user_id = auth.uid()))
  with check (exists (select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admins delete places" on public.places;
create policy "admins delete places"
  on public.places for delete
  using (exists (select 1 from public.admins a where a.user_id = auth.uid()));

-- ---------------------------------------------------------------------------
-- Seed: the 17 places the site ships with today.
-- ---------------------------------------------------------------------------
insert into public.places
  (slug, name, name_ar, category, area, area_ar, lat, lng, rating, price_level,
   emoji, tagline_ar, description_ar, highlights_ar, best_time_ar, featured, sort_order)
values
  ('kuwait-towers', 'Kuwait Towers', 'أبراج الكويت', 'landmarks', 'Kuwait City', 'مدينة الكويت', 29.3897, 48.0022, 4.7, 2, '🗼', 'أيقونة الكويت، على ارتفاع ١٨٧ متر فوق الخليج.', 'undefined', ARRAY['كرة المشاهدة ٣٦٠°', 'مطعم دوّار', 'ممشى على البحر']::text[], 'وقت الغروب، لمّا تضوّي الأبراج', true, 0),
  ('souq-al-mubarakiya', 'Souq Al-Mubarakiya', 'سوق المباركية', 'shopping', 'Kuwait City', 'مدينة الكويت', 29.3759, 47.9774, 4.8, 1, '🏮', 'قرنين من التجارة والبهارات والحكايات.', 'undefined', ARRAY['أكل كويتي أصيل', 'سوق البهارات والذهب', 'أحواش تراثية']::text[], 'بالليل، بعد الخامسة', true, 10),
  ('al-shaheed-park', 'Al Shaheed Park', 'حديقة الشهيد', 'outdoors', 'Kuwait City', 'مدينة الكويت', 29.3689, 47.9884, 4.6, 1, '🌳', 'الرئة الخضراء للعاصمة.', 'undefined', ARRAY['حدائق نباتية', 'متحف الحبيتات ومتحف الذاكرة', 'مسار مشي حول البحيرة']::text[], 'الصبح بدري أو بعد المغرب', true, 20),
  ('mais-alghanim', 'Mais Alghanim', 'ميس الغانم', 'restaurants', 'Gulf Road', 'شارع الخليج', 29.3665, 48.0003, 4.6, 2, '🍢', 'مطعم كويتي عريق على شارع الخليج.', 'undefined', ARRAY['مشاوي ومقبّلات', 'إطلالة على شارع الخليج', 'مناسب للعوائل']::text[], 'العشاء، ويفضّل الحجز', true, 30),
  ('freej-swaileh', 'Freej Swaileh', 'فريج صويلح', 'restaurants', 'Salmiya', 'السالمية', 29.3339, 48.0709, 4.5, 2, '🍛', 'أكل كويتي في أجواء الفريج القديم.', 'undefined', ARRAY['مچبوس ومرقوق', 'ديكور تراثي', 'أجواء كويتية']::text[], 'الغدا، خصوصاً نهاية الأسبوع', false, 40),
  ('mubarakiya-tea-houses', 'Mubarakiya Tea Houses', 'مقاهي المباركية', 'coffee', 'Kuwait City', 'مدينة الكويت', 29.3765, 47.9781, 4.7, 1, '☕', 'چاي وقهوة عربية في حوش السوق.', 'undefined', ARRAY['چاي كرك', 'قهوة عربية وهيل', 'جلسات شعبية']::text[], 'العصر وبعد المغرب', true, 50),
  ('salem-al-mubarak-street', 'Salem Al Mubarak Street', 'شارع سالم المبارك', 'fastfood', 'Salmiya', 'السالمية', 29.3369, 48.0664, 4.3, 1, '🍔', 'شارع الأكل السريع والسهرات في السالمية.', 'undefined', ARRAY['برجر ووجبات سريعة', 'محلات حلا وآيس كريم', 'مفتوح لوقت متأخر']::text[], 'بالليل، بعد الثامنة', false, 60),
  ('the-avenues', 'The Avenues', 'الأفنيوز', 'shopping', 'Al Rai', 'الري', 29.3025, 47.937, 4.7, 3, '🛍️', 'مدينة داخل مدينة — أكبر مول في الخليج.', 'undefined', ARRAY['مناطق تسوّق متنوّعة', 'مطاعم عالمية', 'ممشى داخلي مكيّف']::text[], 'الصبح في أيام الدوام، عشان الزحمة', false, 70),
  ('souq-sharq', 'Souq Sharq', 'سوق شرق', 'shopping', 'Kuwait City', 'مدينة الكويت', 29.3811, 47.9903, 4.4, 2, '⛵', 'مول على البحر مع مارينا وقوارب.', 'undefined', ARRAY['إطلالة على المارينا', 'كافيهات على البحر', 'ممشى بحري']::text[], 'العصر، قبل الغروب', false, 80),
  ('grand-mosque', 'The Grand Mosque', 'المسجد الكبير', 'culture', 'Kuwait City', 'مدينة الكويت', 29.3759, 47.986, 4.9, 1, '🕌', 'أكبر مساجد الكويت، وتحفة في الفن الإسلامي.', 'undefined', ARRAY['جولات مجانية بمرشد', 'خط عربي وقبة مذهلة', 'أحواش هادية']::text[], 'مواعيد الجولات الصباحية', false, 90),
  ('marina-beach', 'Marina Beach & Crescent', 'شاطئ المارينا', 'outdoors', 'Salmiya', 'السالمية', 29.3411, 48.0673, 4.5, 1, '🏖️', 'رمل ناعم ومطاعم على بحر السالمية.', 'undefined', ARRAY['سباحة وكاياك', 'كافيهات على الواجهة', 'ممشى المارينا كرسنت']::text[], 'العصر المتأخر', true, 100),
  ('jacc', 'Sheikh Jaber Cultural Centre', 'مركز الشيخ جابر الثقافي', 'culture', 'Kuwait City', 'مدينة الكويت', 29.3662, 47.9885, 4.8, 2, '🎭', 'دار الأوبرا في الخليج.', 'undefined', ARRAY['عروض عالمية', 'معمار مميّز', 'إضاءة مسائية']::text[], 'ليالي العروض — احجز مقدّماً', false, 110),
  ('failaka-island', 'Failaka Island', 'جزيرة فيلكا', 'outdoors', 'Arabian Gulf', 'الخليج العربي', 29.4457, 48.3318, 4.4, 2, '⛵', 'آثار يونانية قديمة، على بعد رحلة عبّارة.', 'undefined', ARRAY['آثار هلنستية', 'رحلات عبّارة يومية', 'شواطئ هادية']::text[], 'الربيع والشتاء، نهاية الأسبوع', false, 120),
  ('mirror-house', 'The Mirror House', 'بيت المرايا', 'culture', 'Qadsiya', 'القادسية', 29.3486, 47.9932, 4.6, 1, '🪞', 'بيت مغطّى بالمرايا من داخله وخارجه.', 'undefined', ARRAY['غرف فسيفساء المرايا', 'جولة مع عائلة الفنانة', 'تجربة فريدة في الخليج']::text[], 'بموعد مسبق', false, 130),
  ('aqua-park', 'Aqua Park Kuwait', 'أكوا بارك', 'family', 'Kuwait City', 'مدينة الكويت', 29.3856, 47.9958, 4.3, 2, '🎢', 'أول مدينة ألعاب مائية في الخليج، جنب الأبراج.', 'undefined', ARRAY['مسبح أمواج وزحاليق', 'مناطق ألعاب للصغار', 'موقع على البحر']::text[], 'الصبح في أيام الدوام صيفاً', false, 140),
  ('tareq-rajab-museum', 'Tareq Rajab Museum', 'متحف طارق رجب', 'culture', 'Jabriya', 'الجابرية', 29.3222, 48.0231, 4.7, 1, '🏺', 'كنز خاص من الفن الإسلامي.', 'undefined', ARRAY['خط عربي نادر', 'مجوهرات ذهب وفضة', 'قصة مذهلة']::text[], 'عصر أيام الدوام', false, 150),
  ('green-island', 'Green Island', 'الجزيرة الخضراء', 'family', 'Gulf Road', 'شارع الخليج', 29.3652, 48.0076, 4.2, 1, '🏝️', 'جزيرة صناعية فيها حدائق وبحيرات.', 'undefined', ARRAY['بحيرة سباحة', 'برج مشاهدة', 'مساحات خضراء للتنزّه']::text[], 'الأشهر الباردة، وقت العصر', false, 160)
on conflict (slug) do nothing;
