<?php
/**
 * READ-ONLY. Is any migration still to run on the LIVE database? Compares information_schema with
 * every table, column (and type) and index a fully-migrated install has.
 *
 *   wget -nv -O r.php https://raw.githubusercontent.com/hkspower/wain/<40-char-sha>/scripts/live/live-schema-full.php && php r.php
 *
 * THE MANIFEST BELOW IS GENERATED — `node scripts/make-schema-manifest.mjs` imports
 * database-sql/IMPORT-THIS-ONE.sql and then every api/*.mysql.sql into a scratch database and
 * writes what it finds; `--check` fails when this file has fallen behind. It used to be a list
 * typed in on 2026-10-03 (424 columns), and within four days nine tables had been added that it
 * could not see — so a live database missing all nine would have reported `missing=0`.
 *
 * One line per section, each printed as soon as it is measured:
 *   SCHEMA   the server, the totals
 *   TABLES   tables the live database lacks, each with the migrate-*.php that creates it
 *            (`no-migrator` when nothing in scripts/publish/ does — then the install is the only way)
 *   COLUMNS  columns missing from tables that DO exist, with the migrator that adds each, if any
 *   TYPES    columns whose type differs (MySQL-vs-MariaDB spelling normalised away; enum lists are not)
 *   INDEXES  index names missing from tables that exist
 *   EXTRA    tables on live that no install creates — names only
 *   VERDICT  complete, or the migrators to run
 * Prints no data value and no credential: names and column types only. Writes nothing.
 */
declare(strict_types=1);

function line(string $s): void { echo $s, "\n"; @ob_flush(); @flush(); }

// The SAME normalisation as norm() in scripts/make-schema-manifest.mjs — change both or neither.
function norm(string $t): string {
    $t = strtolower(trim($t));
    $t = (string) preg_replace('/\b(tinyint|smallint|mediumint|int|bigint)\(\d+\)/', '$1', $t);
    $t = (string) preg_replace('/\s+zerofill\b/', '', $t);
    return $t === 'json' ? 'longtext' : trim($t);
}
function lst(array $items, int $max = 25): string {
    $n = count($items);
    return implode(' ', array_slice($items, 0, $max)) . ($n > $max ? ' +' . ($n - $max) . 'more' : '');
}
function clip(string $s, int $n = 60): string { return strlen($s) > $n ? substr($s, 0, $n - 1) . '~' : $s; }
// A connection error can name the database user; nothing else this script prints can.
function safe(Throwable $e): string {
    $msg = (string) preg_replace("/'[^']*'@'[^']*'/", "'?'@'?'", $e->getMessage());
    return get_class($e) . ':' . clip(str_replace(["\n", "\r"], ' ', $msg), 160);
}

// >>> SCHEMA MANIFEST — generated by scripts/make-schema-manifest.mjs; do not edit by hand.
// 55 tables, 499 columns, 129 indexes: sporta-site/database-sql/IMPORT-THIS-ONE.sql + 40 api/*.mysql.sql.
$MANIFEST_JSON = <<<'JSON'
{"tables":{
"accounts":{"cols":{"active":"tinyint","code":"varchar(10)","created_at":"timestamp","id":"int unsigned","is_system":"tinyint","name_ar":"varchar(80)","name_en":"varchar(80)","normal_side":"varchar(6)","type":"varchar(10)"},"idx":["PRIMARY","code"]},
"admin_audit_log":{"cols":{"admin_email":"varchar(120)","admin_id":"int unsigned","created_at":"timestamp","id":"int unsigned","route":"varchar(64)","status_code":"smallint unsigned","summary":"text"},"idx":["PRIMARY","idx_audit_created"]},
"admin_devices":{"cols":{"admin_id":"int unsigned","created_at":"timestamp","expires_at":"datetime","failed":"tinyint unsigned","id":"int unsigned","label":"varchar(80)","last_used_at":"timestamp","pass_hash":"varchar(255)","token_hash":"char(64)"},"idx":["PRIMARY","idx_admin_devices_admin","uq_admin_devices_token"]},
"admin_ip_geo":{"cols":{"country":"varchar(2)","country_name":"varchar(80)","ip":"varchar(45)","looked_up_at":"timestamp"},"idx":["PRIMARY"]},
"admin_known_ips":{"cols":{"admin_id":"int unsigned","first_seen":"timestamp","ip":"varchar(45)","last_seen":"timestamp"},"idx":["PRIMARY"]},
"admin_login_log":{"cols":{"admin_id":"int unsigned","agent":"varchar(160)","at":"timestamp","country":"varchar(2)","country_name":"varchar(80)","email":"varchar(190)","id":"bigint unsigned","ip":"varchar(45)","method":"varchar(16)","new_ip":"tinyint","result":"varchar(40)"},"idx":["PRIMARY","idx_login_log_at","idx_login_log_ip"]},
"admin_passkeys":{"cols":{"admin_id":"int unsigned","alg":"int","created_at":"timestamp","credential_id":"varbinary(400)","id":"int unsigned","label":"varchar(60)","last_used_at":"timestamp","public_key":"blob","sign_count":"bigint unsigned","transports":"varchar(80)"},"idx":["PRIMARY","idx_passkeys_admin","uq_passkey_cred"]},
"admin_password_resets":{"cols":{"admin_id":"int unsigned","attempts":"tinyint unsigned","code_hash":"varchar(255)","created_at":"timestamp","expires_at":"datetime"},"idx":["PRIMARY"]},
"admin_sessions":{"cols":{"admin_id":"int unsigned","agent":"varchar(200)","created_at":"timestamp","id":"int unsigned","ip":"varchar(45)","last_seen":"timestamp","method":"varchar(16)","revoked_at":"timestamp","sid_hash":"char(64)"},"idx":["PRIMARY","idx_sessions_admin","sid_hash"]},
"admin_users":{"cols":{"created_at":"timestamp","email":"varchar(120)","email_otp_attempts":"int","email_otp_enabled":"tinyint","email_otp_expires":"timestamp","email_otp_hash":"char(64)","email_otp_sent_at":"timestamp","failed_attempts":"int","id":"int unsigned","last_login_at":"timestamp","locked_until":"timestamp","must_change_password":"tinyint","password_hash":"varchar(255)","phone":"varchar(20)","totp_enabled":"tinyint","totp_last_step":"bigint","totp_secret":"varchar(64)"},"idx":["PRIMARY","email"]},
"assistant_outbox":{"cols":{"attempts":"int","created_at":"timestamp","handled_at":"timestamp","id":"int unsigned","intent":"varchar(24)","lang":"varchar(2)","last_error":"varchar(500)","message":"varchar(500)","reply":"varchar(1000)","sent_at":"timestamp"},"idx":["PRIMARY","idx_assistant_recent","idx_assistant_unsent"]},
"assistant_qa":{"cols":{"a_ar":"varchar(1000)","a_en":"varchar(1000)","active":"tinyint","created_at":"timestamp","hits":"int unsigned","id":"int unsigned","last_hit_at":"timestamp","q_ar":"varchar(200)","q_en":"varchar(200)","updated_at":"timestamp"},"idx":["PRIMARY","idx_assistant_qa_active"]},
"blocked_customers":{"cols":{"blocked_by":"varchar(120)","created_at":"timestamp","id":"int unsigned","phone":"varchar(15)","reason":"varchar(200)","scope":"varchar(3)"},"idx":["PRIMARY","phone"]},
"brands":{"cols":{"active":"tinyint","created_at":"timestamp","id":"int unsigned","logo":"mediumtext","name_ar":"varchar(80)","name_en":"varchar(80)","slug":"varchar(80)","sort":"int","updated_at":"timestamp"},"idx":["PRIMARY","slug"]},
"category_art":{"cols":{"bytes":"mediumblob","etag":"char(32)","fmt":"varchar(4)","tile":"varchar(16)","updated_at":"timestamp","variant":"varchar(16)"},"idx":["PRIMARY"]},
"customer_login_codes":{"cols":{"attempts":"tinyint unsigned","code_hash":"char(64)","created_at":"timestamp","email":"varchar(190)","expires_at":"timestamp","id":"int unsigned","used_at":"timestamp"},"idx":["PRIMARY","customer_login_codes_email"]},
"customer_mail_outbox":{"cols":{"attempts":"int","created_at":"timestamp","id":"int unsigned","kind":"varchar(24)","lang":"varchar(2)","last_error":"varchar(500)","order_id":"int unsigned","sent_at":"timestamp","to_email":"varchar(120)"},"idx":["PRIMARY","idx_customer_mail_unsent","uniq_customer_mail"]},
"customer_notes":{"cols":{"note":"text","phone":"varchar(15)","tags":"varchar(400)","updated_at":"timestamp","updated_by":"varchar(190)"},"idx":["PRIMARY"]},
"customer_passkeys":{"cols":{"alg":"int","created_at":"timestamp","credential_id":"varbinary(400)","customer_id":"int unsigned","id":"int unsigned","label":"varchar(60)","last_used_at":"timestamp","public_key":"text","sign_count":"int unsigned","transports":"varchar(80)"},"idx":["PRIMARY","customer_passkeys_cred","customer_passkeys_owner"]},
"customers":{"cols":{"created_at":"timestamp","email":"varchar(190)","id":"int unsigned","last_seen_at":"timestamp","name":"varchar(120)","password_hash":"varchar(255)","phone":"varchar(20)","verified_at":"timestamp"},"idx":["PRIMARY","email"]},
"discounts":{"cols":{"active":"tinyint","category":"varchar(40)","code":"varchar(24)","created_at":"timestamp","ends_at":"datetime","id":"int unsigned","kind":"varchar(6)","label":"varchar(80)","min_order":"decimal(10,3)","starts_at":"datetime","type":"varchar(8)","updated_at":"timestamp","usage_limit":"int unsigned","used_count":"int unsigned","value":"decimal(10,3)"},"idx":["PRIMARY","code","idx_discounts_live"]},
"fulfilment_outbox":{"cols":{"attempts":"int","created_at":"timestamp","id":"int unsigned","kind":"varchar(10)","last_error":"varchar(500)","new_once":"int unsigned","order_id":"int unsigned","payload":"longtext","sent_at":"timestamp"},"idx":["PRIMARY","fk_outbox_order","idx_outbox_pending","uq_outbox_new"]},
"hero_slides":{"cols":{"active":"tinyint","created_at":"timestamp","cta_href":"varchar(200)","cta_label_ar":"varchar(40)","cta_label_en":"varchar(40)","focal_x":"tinyint unsigned","focal_y":"tinyint unsigned","id":"int unsigned","image":"longtext","image_h":"int","image_hash":"char(64)","image_mobile":"longtext","image_mobile_h":"int","image_mobile_hash":"char(64)","image_mobile_w":"int","image_w":"int","sort":"int","subtitle_ar":"varchar(200)","subtitle_en":"varchar(200)","title_ar":"varchar(120)","title_en":"varchar(120)","updated_at":"timestamp"},"idx":["PRIMARY","idx_hero_sort"]},
"home_banner":{"cols":{"button_ar":"varchar(30)","button_en":"varchar(30)","enabled":"tinyint","etag":"char(32)","href":"varchar(200)","id":"tinyint","image":"mediumblob","image_h":"int","image_type":"varchar(10)","image_w":"int","kicker_ar":"varchar(60)","kicker_en":"varchar(60)","product":"varchar(64)","title_ar":"varchar(90)","title_en":"varchar(90)","updated_at":"timestamp"},"idx":["PRIMARY"]},
"journal_entries":{"cols":{"created_at":"timestamp","created_by":"varchar(120)","entry_date":"date","id":"int unsigned","kind":"varchar(20)","memo":"varchar(200)","reversed_by_id":"int unsigned","reverses_id":"int unsigned","source":"varchar(10)","source_ref":"varchar(40)"},"idx":["PRIMARY","fk_journal_reverses","idx_journal_date","uq_journal_source"]},
"journal_lines":{"cols":{"account_id":"int unsigned","credit":"decimal(12,3)","debit":"decimal(12,3)","entry_id":"int unsigned","id":"int unsigned","memo":"varchar(200)"},"idx":["PRIMARY","idx_lines_account","idx_lines_entry"]},
"order_items":{"cols":{"fit":"varchar(10)","id":"int unsigned","name_ar":"varchar(120)","name_en":"varchar(120)","order_id":"int unsigned","product_id":"int unsigned","qty":"int","size":"varchar(4)","unit_price":"decimal(10,3)"},"idx":["PRIMARY","fk_items_product","idx_items_order"]},
"order_location":{"cols":{"accuracy_m":"int unsigned","lat":"decimal(9,6)","lng":"decimal(9,6)","order_id":"int unsigned","updated_at":"timestamp"},"idx":["PRIMARY"]},
"orders":{"cols":{"amount":"decimal(10,3)","cbk_authcode":"varchar(30)","cbk_message":"varchar(200)","cbk_paymentid":"varchar(60)","cbk_paytype":"varchar(20)","cbk_receipt":"varchar(60)","cbk_reference":"varchar(60)","cbk_status":"varchar(30)","cbk_transaction":"varchar(60)","courier":"varchar(24)","courier_ref":"varchar(80)","created_at":"timestamp","customer_area":"varchar(60)","customer_block":"varchar(12)","customer_building":"varchar(24)","customer_email":"varchar(120)","customer_flat":"varchar(16)","customer_floor":"varchar(16)","customer_governorate":"varchar(20)","customer_id":"int unsigned","customer_lang":"varchar(2)","customer_name":"varchar(80)","customer_note":"varchar(280)","customer_phone":"varchar(15)","customer_street":"varchar(40)","delivery_fee":"decimal(10,3)","discount_amount":"decimal(10,3)","discount_code":"varchar(24)","discount_label":"varchar(200)","fulfilled_at":"timestamp","fulfilment_status":"varchar(12)","id":"int unsigned","packed_at":"timestamp","paid_at":"timestamp","pay_attempt":"int unsigned","payment_method":"varchar(10)","payment_status":"varchar(10)","referrer_host":"varchar(120)","shipped_at":"timestamp","stock_claimed":"tinyint","stock_released":"tinyint","subtotal":"decimal(10,3)","track_id":"varchar(30)","utm_campaign":"varchar(80)","utm_medium":"varchar(60)","utm_source":"varchar(60)"},"idx":["PRIMARY","idx_orders_created","idx_orders_discount","idx_orders_fulfilment","idx_orders_payment","idx_orders_phone_open","idx_orders_source","idx_orders_stock_sweep","orders_customer_idx","track_id"]},
"product_attrs":{"cols":{"colour":"varchar(32)","fits":"varchar(120)","slug":"varchar(80)","updated_at":"timestamp"},"idx":["PRIMARY"]},
"product_image_thumbs":{"cols":{"bytes":"mediumblob","image_id":"int unsigned","type":"varchar(8)","w":"smallint"},"idx":["PRIMARY"]},
"product_images":{"cols":{"created_at":"timestamp","id":"int unsigned","image":"longtext","image_h":"int","image_hash":"char(64)","image_w":"int","slug":"varchar(120)","sort":"int"},"idx":["PRIMARY","idx_product_images"]},
"product_seo":{"cols":{"desc_ar":"varchar(200)","desc_en":"varchar(200)","slug":"varchar(64)","title_ar":"varchar(70)","title_en":"varchar(70)","updated_at":"timestamp"},"idx":["PRIMARY"]},
"product_variants":{"cols":{"cost_aed":"decimal(10,2)","size":"varchar(4)","sku":"varchar(30)","slug":"varchar(80)","stock":"int"},"idx":["PRIMARY","idx_variants_slug"]},
"products":{"cols":{"active":"tinyint","brand_slug":"varchar(64)","category":"varchar(40)","created_at":"timestamp","desc_ar":"text","desc_en":"text","featured":"tinyint","featured_sort":"int","id":"int unsigned","image":"varchar(500)","images":"text","name_ar":"varchar(160)","name_en":"varchar(160)","no_exchange":"tinyint","price":"decimal(10,3)","sale_ends_at":"datetime","sale_price":"decimal(10,3)","sale_starts_at":"datetime","slug":"varchar(80)"},"idx":["PRIMARY","idx_products_brand","idx_products_featured","slug"]},
"purchase_order_items":{"cols":{"cost_aed":"decimal(10,2)","id":"int unsigned","po_id":"int unsigned","qty":"int unsigned","sku":"varchar(30)"},"idx":["PRIMARY","idx_poi_po"]},
"purchase_orders":{"cols":{"created_at":"timestamp","created_by":"varchar(80)","expected_on":"date","id":"int unsigned","note":"varchar(300)","received_at":"timestamp","status":"varchar(10)","supplier_id":"int unsigned"},"idx":["PRIMARY","fk_po_supplier"]},
"push_outbox":{"cols":{"attempts":"int","body":"varchar(300)","created_at":"timestamp","id":"int unsigned","kind":"varchar(24)","last_error":"varchar(500)","order_id":"int unsigned","sent_at":"timestamp","title":"varchar(120)","url":"varchar(200)"},"idx":["PRIMARY","idx_push_unsent","uniq_push_order_kind"]},
"push_subscriptions":{"cols":{"auth":"varchar(40)","created_at":"timestamp","endpoint":"varchar(500)","endpoint_hash":"char(64)","id":"int unsigned","label":"varchar(60)","last_error":"varchar(300)","last_ok_at":"timestamp","p256dh":"varchar(120)"},"idx":["PRIMARY","uniq_push_endpoint"]},
"rate_bucket":{"cols":{"allowed":"tinyint","bucket_key":"char(32)","refilled_at":"double","tokens":"double"},"idx":["PRIMARY","idx_rate_bucket_sweep"]},
"rate_limit":{"cols":{"bucket_key":"char(32)","hits":"int unsigned","window_start":"int unsigned"},"idx":["PRIMARY","idx_rate_limit_sweep"]},
"return_request_items":{"cols":{"id":"int unsigned","order_item_id":"int unsigned","qty":"int","request_id":"int unsigned","want_size":"varchar(4)"},"idx":["PRIMARY","fk_ritem_line","uq_ritem"]},
"return_requests":{"cols":{"created_at":"timestamp","decided_at":"timestamp","id":"int unsigned","kind":"varchar(10)","lang":"varchar(2)","order_id":"int unsigned","phone":"varchar(15)","reason":"varchar(280)","ref":"varchar(20)","staff_note":"varchar(280)","status":"varchar(12)"},"idx":["PRIMARY","idx_returns_order","idx_returns_status","ref"]},
"reviews":{"cols":{"comment":"varchar(1000)","created_at":"timestamp","id":"int unsigned","lang":"varchar(2)","order_id":"int unsigned","published":"tinyint","rating":"tinyint unsigned","reward_code":"varchar(24)"},"idx":["PRIMARY","idx_reviews_created","uq_reviews_order"]},
"seo_image":{"cols":{"etag":"char(32)","id":"tinyint","image":"mediumblob","image_h":"int","image_type":"varchar(10)","image_w":"int","updated_at":"timestamp"},"idx":["PRIMARY"]},
"settings":{"cols":{"name":"varchar(40)","updated_at":"timestamp","value":"text"},"idx":["PRIMARY"]},
"site_images":{"cols":{"bytes":"mediumblob","etag":"char(32)","fmt":"varchar(4)","name":"varchar(24)","updated_at":"timestamp"},"idx":["PRIMARY"]},
"size_advice_log":{"cols":{"chest_cm":"smallint unsigned","confidence":"varchar(8)","created_at":"timestamp","fit":"varchar(10)","height_cm":"smallint unsigned","hip_cm":"smallint unsigned","id":"int unsigned","lang":"varchar(2)","outcome":"varchar(10)","prefers":"varchar(10)","size":"varchar(4)","slug":"varchar(80)","usual_size":"varchar(4)","waist_cm":"smallint unsigned","weight_kg":"smallint unsigned"},"idx":["PRIMARY","idx_advice_recent","idx_advice_slug"]},
"size_charts":{"cols":{"chart":"varchar(24)","chest_max":"smallint unsigned","chest_min":"smallint unsigned","hip_max":"smallint unsigned","hip_min":"smallint unsigned","id":"int unsigned","is_default":"tinyint","length_cm":"smallint unsigned","size":"varchar(4)","sort":"smallint","waist_max":"smallint unsigned","waist_min":"smallint unsigned"},"idx":["PRIMARY","uniq_chart_size"]},
"stock_log":{"cols":{"actor":"varchar(80)","at":"timestamp","delta":"int","id":"bigint unsigned","reason":"varchar(24)","ref":"varchar(40)","size":"varchar(4)","sku":"varchar(30)","slug":"varchar(80)","stock_after":"int"},"idx":["PRIMARY","idx_stock_log_at","idx_stock_log_slug"]},
"suppliers":{"cols":{"contact":"varchar(160)","created_at":"timestamp","id":"int unsigned","lead_days":"int unsigned","name":"varchar(80)","note":"varchar(300)"},"idx":["PRIMARY"]},
"variant_supplier":{"cols":{"sku":"varchar(30)","supplier_id":"int unsigned"},"idx":["PRIMARY","fk_vs_supplier"]},
"wallet_passes":{"cols":{"auth_token":"varchar(64)","device_id":"varchar(64)","id":"int unsigned","issued_at":"timestamp","kind":"varchar(10)","name":"varchar(80)","phone":"varchar(16)","points_at_issue":"int unsigned","push_token":"varchar(128)","serial":"varchar(40)","updated_at":"timestamp"},"idx":["PRIMARY","idx_wallet_phone","serial"]},
"wallet_registrations":{"cols":{"created_at":"timestamp","device_id":"varchar(64)","push_token":"varchar(200)","serial":"varchar(40)"},"idx":["PRIMARY","idx_wallet_reg_serial"]},
"whatsapp_outbox":{"cols":{"attempts":"int","created_at":"timestamp","id":"int unsigned","kind":"varchar(12)","lang":"varchar(5)","last_error":"varchar(500)","order_id":"int unsigned","payload":"longtext","sent_at":"timestamp","template":"varchar(80)","to_e164":"varchar(20)","wa_message_id":"varchar(120)"},"idx":["PRIMARY","idx_wa_pending","uq_wa_once"]}
},
"creates":{"admin_audit_log":["migrate-admin-audit-log.php"],"admin_devices":["migrate-admin-devices.php"],"admin_ip_geo":["migrate-admin-login-log.php"],"admin_known_ips":["migrate-known-ips.php"],"admin_login_log":["migrate-admin-login-log.php"],"admin_passkeys":["migrate-security.php"],"admin_password_resets":["migrate-admin-reset.php"],"admin_sessions":["migrate-security.php"],"category_art":["migrate-category-art.php"],"customer_login_codes":["migrate-customerfast.php"],"customer_passkeys":["migrate-customerfast.php"],"customers":["migrate-customers.php"],"home_banner":["migrate-home-banner.php"],"order_location":["migrate-livetrack.php"],"product_attrs":["migrate-product-attrs.php"],"product_image_thumbs":["migrate-product-image-thumbs.php"],"product_seo":["migrate-seo.php"],"purchase_order_items":["migrate-purchasing.php"],"purchase_orders":["migrate-purchasing.php"],"rate_bucket":["migrate-ratebucket.php"],"seo_image":["migrate-seo.php"],"site_images":["migrate-site-images.php"],"stock_log":["migrate-stock-log.php"],"suppliers":["migrate-purchasing.php"],"variant_supplier":["migrate-purchasing.php"],"wallet_registrations":["migrate-wallet-web.php"]},
"adds":{"admin_users.must_change_password":["migrate-must-change-password.php"],"hero_slides.image_mobile":["migrate-hero-mobile.php"],"hero_slides.image_mobile_h":["migrate-hero-mobile.php"],"hero_slides.image_mobile_hash":["migrate-hero-mobile.php"],"hero_slides.image_mobile_w":["migrate-hero-mobile.php"],"orders.courier":["migrate-livetrack.php"],"orders.courier_ref":["migrate-livetrack.php"],"orders.customer_id":["migrate-customers.php"],"orders.packed_at":["migrate-livetrack.php"],"orders.shipped_at":["migrate-livetrack.php"],"wallet_passes.auth_token":["migrate-wallet-web.php"]}}
JSON;
// <<< SCHEMA MANIFEST

// store_db() does not THROW when it cannot connect: store_out() prints its own JSON and exits, so
// the catch below never runs for the commonest failure, and a fatal error (memory, a missing
// function) prints nothing at all where display_errors is off. Either way the run must still end
// on a line that says no measurement was taken, or an absent VERDICT reads like a cut-off echo.
$done = false;
register_shutdown_function(function () use (&$done) {
    if ($done) return;
    $e = error_get_last();
    $fatal = $e && in_array($e['type'], [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR], true);
    if (!$fatal) echo "\n"; // store_out()'s JSON ends without one
    line('VERDICT unknown - stopped before measuring' . ($fatal
        ? ' fatal=' . clip(basename((string) $e['file']) . ':' . $e['line'] . ' ' . str_replace(["\n", "\r"], ' ', (string) preg_replace("/'[^']*'@'[^']*'/", "'?'@'?'", (string) $e['message'])), 120)
        : ' (store.php answered on the line above)'));
});

try {
    $m = json_decode($MANIFEST_JSON, true);
    if (!is_array($m) || empty($m['tables'])) { $done = true; line('SCHEMA error=manifest-unreadable'); exit; }
    $want = $m['tables']; $creates = $m['creates'] ?? []; $adds = $m['adds'] ?? [];

    $live = '/home/u130124229/domains/sporta.com.kw/public_html/api/store.php';
    require is_file($live) ? $live : __DIR__ . '/../../sporta-site/public_html/api/store.php';
    $db = store_db();

    $have = [];
    foreach ($db->query('select table_name, table_type from information_schema.tables where table_schema = database()')->fetchAll(PDO::FETCH_NUM) as $r) {
        if ($r[1] === 'BASE TABLE') $have[$r[0]] = ['cols' => [], 'idx' => []];
    }
    foreach ($db->query('select table_name, column_name, column_type from information_schema.columns where table_schema = database()')->fetchAll(PDO::FETCH_NUM) as $r) {
        if (isset($have[$r[0]])) $have[$r[0]]['cols'][$r[1]] = norm((string) $r[2]);
    }
    foreach ($db->query('select distinct table_name, index_name from information_schema.statistics where table_schema = database()')->fetchAll(PDO::FETCH_NUM) as $r) {
        if (isset($have[$r[0]])) $have[$r[0]]['idx'][$r[1]] = true;
    }

    $wc = 0; $wi = 0;
    foreach ($want as $t) { $wc += count($t['cols']); $wi += count($t['idx']); }
    $missT = []; $missC = []; $types = []; $missI = []; $run = []; $orphan = 0; $nc = 0; $ni = 0;
    foreach ($want as $t => $spec) {
        if (!isset($have[$t])) {
            $by = $creates[$t] ?? [];
            foreach ($by as $s) $run[$s] = true;
            if (!$by) $orphan++;
            $missT[] = $t . '[' . ($by ? implode(',', $by) : 'no-migrator') . ']';
            continue;
        }
        $cs = [];
        foreach ($spec['cols'] as $c => $ty) {
            if (!isset($have[$t]['cols'][$c])) {
                $by = $adds["$t.$c"] ?? [];
                foreach ($by as $s) $run[$s] = true;
                if (!$by) $orphan++;
                $cs[] = $c . '[' . ($by ? implode(',', $by) : 'no-migrator') . ']';
                $nc++;
            } elseif ($have[$t]['cols'][$c] !== $ty) {
                $types[] = "$t.$c(" . clip($have[$t]['cols'][$c]) . '>' . clip($ty) . ')';
            }
        }
        if ($cs) $missC[] = $t . '(' . implode(',', $cs) . ')';
        $is = array_values(array_filter($spec['idx'], fn($i) => !isset($have[$t]['idx'][$i])));
        if ($is) { $missI[] = $t . '(' . implode(',', $is) . ')'; $ni += count($is); }
    }
    $extra = array_values(array_filter(array_keys($have), fn($t) => !isset($want[$t])));
    sort($extra);

    line('SCHEMA server=' . clip((string) $db->query('select version()')->fetchColumn(), 40)
        . ' want=' . count($want) . 't/' . $wc . 'c/' . $wi . 'i live=' . count($have) . 't'
        . ' missingTables=' . count($missT) . ' missingColumns=' . $nc . ' typeDiffer=' . count($types)
        . ' missingIndexes=' . $ni . ' extraTables=' . count($extra));
    line('TABLES missing=' . count($missT) . ($missT ? ' ' . lst($missT) : ''));
    line('COLUMNS missing=' . $nc . ($missC ? ' ' . lst($missC) : ''));
    line('TYPES differ=' . count($types) . ($types ? ' ' . lst($types, 15) : ''));
    line('INDEXES missing=' . $ni . ($missI ? ' ' . lst($missI) : ''));
    line('EXTRA tables=' . count($extra) . ($extra ? ' ' . lst($extra, 40) : ''));
    $r = array_keys($run); sort($r);
    line(!$missT && !$nc
        ? 'VERDICT complete' . ($types || $ni ? ' (types/indexes differ — read the lines above)' : '')
        : 'VERDICT behind' . ($r ? ' run=' . implode(',', $r) : '') . ($orphan ? " noMigrator=$orphan(no migrate-*.php creates these: write one, or run only their statements from IMPORT-THIS-ONE.sql - never the whole file on live, it re-inserts seed products and stock the owner deleted)" : ''));
    $done = true;
} catch (Throwable $e) {
    $done = true;
    line('SCHEMA error=' . safe($e));
}
