<?php
/**
 * The whole docroot, rolled out in THREE STAGES with a gate between each.
 *
 *   wget -qO r.php https://raw.githubusercontent.com/hkspower/wain/<sha>/scripts/publish/publish-staged.php && php r.php
 *
 * Run it THREE TIMES. Each run advances the rollout by exactly ONE stage — the
 * first stage that is not already complete — so the three cron cycles are the
 * three stages, in order, and there is nothing to remember between them. When
 * every stage is complete it writes NOTHING and instead runs all three
 * verifications, so a fourth run is a full read-only report.
 *
 * IT TAKES NO ARGUMENT, and that is not a preference. Measured 2026-09-10:
 * `php r.php 1` through this channel produced an EMPTY output twice running,
 * where the identical command without the trailing argument answered first
 * time. Add it to the list of things this channel silently drops — alongside
 * $VAR expansions, `%`, quoted metacharacters and anything after the command
 * whose output you want. The stage therefore comes from the SERVER'S OWN STATE
 * rather than from a parameter, which is better anyway: the run cannot be told
 * to do a stage the gate would refuse.
 *
 * WHY THREE, AND WHY THIS ORDER. The order is not "small things first"; it is
 * the only order in which the shop is a working shop at every moment BETWEEN
 * the stages, which is the whole point of staging it at all.
 *
 *   1. SERVER   api/*.php, seo.php, knet/, pay/, the .sql files, every
 *               .htaccess EXCEPT the root one.
 *
 *      A NEW page calling an OLD server is broken. An OLD page calling a NEW
 *      server is fine, because a route that was added is a route nothing yet
 *      asks for. So the server goes first and absorbs the change while every
 *      visitor is still running yesterday's page. This is not theoretical here:
 *      /assets/rules.js was published in the same breath as the admin.php route
 *      it calls, and had the order gone the other way the panel would have been
 *      live and dead at the same time.
 *
 *   2. ASSETS   assets/, hero/, cats/, images/, fonts/, the icons, the xml.
 *
 *      These have FIXED names and the shell references them by those names, so
 *      a new stylesheet that nothing has switched to yet harms nobody: it sits
 *      on disk being correct. The API each new overlay calls already exists,
 *      because stage 1 put it there.
 *
 *   3. SHELL    index.html, the root .htaccess, sw.js — together, always.
 *
 *      This is the stage that actually moves visitors onto the new shop, and
 *      the three are one atom:
 *
 *        - .htaccess carries the CSP, which names each inline script in
 *          index.html BY SHA256. Published apart, in either order, there is a
 *          window where the boot script is REFUSED — a new page against an old
 *          policy is a hash the policy does not name, and an old page against a
 *          new policy is the same thing reversed. A blocked boot script is not
 *          a blank page; it is the language flipping after first paint and the
 *          theme not sticking, which looks like anything but a header.
 *        - sw.js's VERSION is what drops the caches pinning a returning visitor
 *          to an old fixed-name asset. It belongs LAST, once the assets it is
 *          freeing them onto are already on disk. Bumped in stage 2 it would
 *          drop caches and re-fetch against the old shell for one stage.
 *
 * THE GATE IS THE SELECTION. The stage a run performs is the FIRST one not
 * already complete — complete meaning every one of its files matches its sha256
 * on disk, not "I ran it". So a half-finished stage 1 is simply chosen again,
 * and stage 2 cannot be reached over the top of it. That is what makes this a
 * rollout rather than three scripts that happen to be numbered, and there is no
 * way to ask for a stage the gate would refuse, because nothing is asked for.
 *
 * ONE HOME FOR THE FILE LIST. The manifest is NOT repeated here. It is fetched
 * from scripts/live/live-file-check.php at the same commit and parsed — that
 * file's list is generated by `npm run make:file-manifest` and guarded by
 * `npm run test:file-manifest`, so it cannot drift. A second copy typed into
 * this file would be a second home for it, which is exactly the staleness this
 * repository keeps paying for. If the fetch or the parse yields a suspiciously
 * short list this refuses to run: an empty manifest publishes nothing and
 * reports a clean sweep, which is the failure that looks most like success.
 *
 * AND EVERY FILE LANDS IN EXACTLY ONE STAGE. Asserted, not assumed — the three
 * counts must sum to the manifest's size. A file in no stage would never be
 * published and nothing would say so.
 *
 * WHEN NOT TO USE THIS. A change that couples the root .htaccess to something
 * in stage 1 — a rewrite added alongside a new PHP entry point — is one atom
 * that this splits across stages 1 and 3. Publish that with a single-run
 * publisher instead. Staging is for an ordinary rollout, not for every change.
 *
 * WHY IT IS SAFE TO FETCH AND RUN. Plain HTTP from a PUBLIC repository: paths
 * come only from the manifest, each is checked against its recorded sha256
 * BEFORE it is written, writes are temp-file-plus-rename, nothing is deleted,
 * no directory is created, fetches are ONE AT A TIME, and a file already
 * matching is skipped — so re-running costs nothing and a half-finished stage
 * completes on the next run.
 */

$COMMIT = '54c1330';
$ROOT   = '/home/u130124229/domains/sporta.com.kw/public_html';
$RAW    = 'https://raw.githubusercontent.com/hkspower/wain/' . $COMMIT . '/';
$BASE   = $RAW . 'sporta-site/public_html/';

/* ------------------------------------------------- the manifest, fetched --- */

function fetch(string $url): ?string
{
    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_TIMEOUT        => 60,
    ]);
    $body = curl_exec($ch);
    $code = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    return ($body === false || $code !== 200 || $body === '') ? null : $body;
}

$src = fetch($RAW . 'scripts/live/live-file-check.php');
if ($src === null) { echo "STAGED could not fetch the manifest\n"; exit(1); }

/* Only the $WANT block, so $MUSTNOT's entries can never be mistaken for files
   to publish — they are the six that must NOT be on the server. */
$want = [];
if (preg_match('/\$WANT = \[(.*?)\n\];/s', $src, $m)) {
    preg_match_all("/'([^']+)' => '([0-9a-f]{64})'/", $m[1], $rows, PREG_SET_ORDER);
    foreach ($rows as $r) $want[$r[1]] = $r[2];
}

// A short list publishes almost nothing and reports a clean sweep.
if (count($want) < 100) { echo 'STAGED manifest looks wrong — ' . count($want) . " entries\n"; exit(1); }

/* ------------------------------------------------------ the three stages --- */

/** The shell is named exactly, because it is an atom rather than a pattern. */
$SHELL = ['index.html', '.htaccess', 'sw.js'];

$stageOf = static function (string $rel) use ($SHELL): int {
    if (in_array($rel, $SHELL, true)) return 3;
    // Every other .htaccess belongs to the directory it guards, which is server.
    if (str_ends_with($rel, '.htaccess')) return 1;
    if (str_ends_with($rel, '.php') || str_ends_with($rel, '.sql')) return 1;
    return 2;
};

$buckets = [1 => [], 2 => [], 3 => []];
foreach ($want as $rel => $sha) $buckets[$stageOf($rel)][$rel] = $sha;

// Every file in exactly one stage. A file in none would never be published and
// nothing would say so.
$sum = count($buckets[1]) + count($buckets[2]) + count($buckets[3]);
if ($sum !== count($want)) { echo "STAGED classification lost files — $sum of " . count($want) . "\n"; exit(1); }

/** How many of a stage's files already match on disk. */
$state = static function (array $files) use ($ROOT): array {
    $ok = 0; $todo = [];
    foreach ($files as $rel => $sha) {
        $p = $ROOT . '/' . $rel;
        if (is_file($p) && hash_file('sha256', $p) === $sha) $ok++;
        else $todo[] = $rel;
    }
    return [$ok, $todo];
};


/* ------------------------------------------------- one request, verifying -- */

$serve = static function (string $path): array {
    $ch = curl_init('https://127.0.0.1' . $path);
    curl_setopt_array($ch, [
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_HEADER         => true,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_SSL_VERIFYHOST => false,
        CURLOPT_HTTPHEADER     => ['Host: www.sporta.com.kw'],
        CURLOPT_TIMEOUT        => 30,
    ]);
    $out  = (string) curl_exec($ch);
    $size = (int) curl_getinfo($ch, CURLINFO_HEADER_SIZE);
    $code = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    return [substr($out, 0, $size), substr($out, $size), $code];
};

/* What each stage is asked to PROVE, and it is a different question per stage.
   A byte count would read as success for all three whatever happened. */
$prove = static function (int $n) use ($serve): string {
    if ($n === 1) {
        // The server still answers, and still refuses what it should refuse. A
        // broken PHP file is a 500 on every page, so a failure here is total
        // and immediate — which is exactly why this stage goes first, while
        // every visitor is still being served yesterday's page.
        [, $prod, $c1] = $serve('/api/api.php?r=products');
        [, , $c2]      = $serve('/api/admin.php?r=stats');
        return 'api=' . $c1 . '/' . strlen($prod)
             . ' adminGate=' . $c2 . ($c2 === 401 ? '(gated)' : ($c2 === 200 ? '(LEAK)' : ''));
    }
    if ($n === 2) {
        // The assets answer. Nothing references the new ones yet — that is
        // stage 3 — so this asks only that they are there and non-empty.
        $ok = 0; $bytes = 0;
        foreach (['/assets/sporta-ui.css', '/assets/sporta-dark.css', '/assets/rules.js'] as $p) {
            [, $b, $c] = $serve($p);
            if ($c === 200 && $b !== '') { $ok++; $bytes += strlen($b); }
        }
        return 'assets=' . $ok . '/3 assetBytes=' . $bytes;
    }
    // THE ONE THAT MATTERS. Re-derive the sha256 of every inline script the
    // SERVED page carries and compare it against the policy the server SENDS.
    // Reading .htaccess would only say what the repository thinks.
    [$head, $html, $c] = $serve('/');
    $declared = [];
    if (preg_match('/content-security-policy:.*/i', $head, $mm)) {
        preg_match_all("/'(sha256-[A-Za-z0-9+\/=]+)'/", $mm[0], $d);
        $declared = $d[1];
    }
    preg_match_all('/<script(?![^>]*\bsrc=)[^>]*>(.*?)<\/script>/s', $html, $s);
    $blocked = 0;
    foreach ($s[1] as $b) {
        if (!in_array('sha256-' . base64_encode(hash('sha256', $b, true)), $declared, true)) $blocked++;
    }
    return 'shell=' . $c . '/' . strlen($html)
         . ' inlineScripts=' . count($s[1]) . ' cspHashes=' . count($declared) . ' BLOCKED=' . $blocked
         . ' swVersion=' . (preg_match("/const VERSION = '([^']+)'/", $serve('/sw.js')[1], $v) ? $v[1] : 'UNREADABLE');
};

/* ------------------------------------------- which stage this run is for --- */

/* THE GATE IS THE SELECTION. The stage is the first one not already complete
   on disk — complete meaning every file matches its sha256, not "I ran it" —
   so a half-finished stage is simply chosen again, and a later stage can never
   be reached over the top of an earlier one. There is no way to ask for a
   stage the gate would refuse, because nothing is asked for. */
$stage = 0;
$counts = [];
foreach ([1, 2, 3] as $n) {
    [$ok, $todo] = $state($buckets[$n]);
    $counts[] = 'stage' . $n . '=' . $ok . '/' . count($buckets[$n]);
    if ($stage === 0 && $todo) $stage = $n;
}

/* Nothing to do: the rollout is complete, so this run is a read-only report and
   every stage's own verification is run. A publisher with nothing to publish
   should still be able to tell you the shop is right. */
if ($stage === 0) {
    echo 'STAGED complete manifest=' . count($want) . ' ' . implode(' ', $counts)
       . ' | 1{' . $prove(1) . '} 2{' . $prove(2) . '} 3{' . $prove(3) . '}'
       . "\n";
    exit(0);
}

/* ---------------------------------------------------------------- write ---- */

$files = $buckets[$stage];
$wrote = 0; $same = 0; $bad = []; $failed = [];

foreach ($files as $rel => $sha) {
    $target = $ROOT . '/' . $rel;
    if (is_file($target) && hash_file('sha256', $target) === $sha) { $same++; continue; }

    $body = fetch($BASE . $rel);
    if ($body === null) { $failed[] = $rel; continue; }
    if (hash('sha256', $body) !== $sha) { $bad[] = $rel; continue; }

    $tmp = dirname($target) . '/.pub-' . bin2hex(random_bytes(6));
    $ok  = @file_put_contents($tmp, $body) === strlen($body);
    if ($ok) $ok = @rename($tmp, $target) || @copy($tmp, $target);
    @unlink($tmp);

    if ($ok && is_file($target) && hash_file('sha256', $target) === $sha) { @chmod($target, 0644); $wrote++; }
    else $failed[] = $rel;
}

/* A check run in the same breath as a write can measure the state BEFORE it —
   this docroot has a writer that acts on a delay and LiteSpeed has been seen
   holding an old parse seconds after a verified write. The bytes above were
   verified by sha256; if the line below disagrees with them, re-ask a minute
   later before believing either. */
echo 'STAGED ran=' . $stage . ' of=' . count($files)
   . ' wrote=' . $wrote . ' alreadyOk=' . $same
   . ' hashMismatch=' . (count($bad) ? implode(',', $bad) : '0')
   . ' failed=' . (count($failed) ? implode(',', $failed) : '0')
   . ' | ' . $prove($stage)
   . ' | ' . implode(' ', $counts) . ' (before this run)'
   . "\n";
