-- Sporta native backend — catalogue + inventory seed.
--
-- GENERATED by scripts/generate-mysql-seed.mjs. Do not hand-edit.
-- Import in phpMyAdmin AFTER schema.mysql.sql. Safe to re-run: matching is on
-- slug / sku, so prices and names update in place and nothing duplicates.
-- Stock is NOT overwritten on re-run — the shelf count belongs to the shop,
-- not to this file.

set names utf8mb4;

insert into products (slug, name_en, name_ar, desc_en, desc_ar, price, category, active) values
  ('cagliari-calcio-backpack', 'Cagliari Calcio Backpack', 'حقيبة ظهر كالياري كالتشو', 'Cagliari Calcio Backpack.', 'حقيبة ظهر كالياري كالتشو.', 4.000, 'accessories', 1),
  ('cagliari-calcio-backpack-navy', 'Cagliari Calcio Backpack — Navy', 'حقيبة ظهر كالياري كالتشو — كحلي', 'Cagliari Calcio Backpack in navy.', 'حقيبة ظهر كالياري كالتشو، كحلي.', 9.000, 'accessories', 1),
  ('cagliari-calcio-sweatshirt-navy', 'Cagliari Calcio Sweatshirt — Navy', 'سويت شيرت كالياري كالتشو — كحلي', 'Cagliari Calcio Sweatshirt in navy.', 'سويت شيرت كالياري كالتشو، كحلي.', 10.000, 'outerwear', 1),
  ('cheetahs-rugby-t-shirt', 'Cheetahs Rugby T-Shirt', 'تيشيرت تشيتاز رَغبي', 'Cheetahs Rugby T-Shirt.', 'تيشيرت تشيتاز رَغبي.', 8.000, 'men', 1),
  ('cloudsoft-jacket-army-green', 'Cloudsoft Jacket — Army Green', 'جاكيت كلاودسوفت — أخضر عسكري', 'Cloudsoft Jacket in army green.', 'جاكيت كلاودسوفت، أخضر عسكري.', 10.000, 'outerwear', 1),
  ('cloudsoft-jacket-cherry-red', 'Cloudsoft Jacket — Cherry Red', 'جاكيت كلاودسوفت — أحمر كرزي', 'Cloudsoft Jacket in cherry red.', 'جاكيت كلاودسوفت، أحمر كرزي.', 8.000, 'outerwear', 1),
  ('cloudsoft-jacket-coffee-brown', 'Cloudsoft Jacket — Coffee Brown', 'جاكيت كلاودسوفت — بني قهوة', 'Cloudsoft Jacket in coffee brown.', 'جاكيت كلاودسوفت، بني قهوة.', 10.000, 'outerwear', 1),
  ('cloudsoft-leggings-army-green', 'Cloudsoft Leggings — Army Green', 'ليقنز كلاودسوفت — أخضر عسكري', 'Cloudsoft Leggings in army green.', 'ليقنز كلاودسوفت، أخضر عسكري.', 8.000, 'women', 1),
  ('cloudsoft-leggings-cherry-red', 'Cloudsoft Leggings — Cherry Red', 'ليقنز كلاودسوفت — أحمر كرزي', 'Cloudsoft Leggings in cherry red.', 'ليقنز كلاودسوفت، أحمر كرزي.', 8.000, 'women', 1),
  ('cloudsoft-leggings-coffee-brown', 'Cloudsoft Leggings — Coffee Brown', 'ليقنز كلاودسوفت — بني قهوة', 'Cloudsoft Leggings in coffee brown.', 'ليقنز كلاودسوفت، بني قهوة.', 8.000, 'women', 1),
  ('cloudsoft-leggings-grey', 'Cloudsoft Leggings — Grey', 'ليقنز كلاودسوفت — رمادي', 'Cloudsoft Leggings in grey.', 'ليقنز كلاودسوفت، رمادي.', 4.500, 'women', 1),
  ('cloudsoft-leggings-navy', 'Cloudsoft Leggings — Navy', 'ليقنز كلاودسوفت — كحلي', 'Cloudsoft Leggings in navy.', 'ليقنز كلاودسوفت، كحلي.', 8.000, 'women', 1),
  ('cloudsoft-leggings-onyx-black', 'Cloudsoft Leggings — Onyx Black', 'ليقنز كلاودسوفت — أسود أونيكس', 'Cloudsoft Leggings in onyx black.', 'ليقنز كلاودسوفت، أسود أونيكس.', 8.000, 'women', 1),
  ('cloudsoft-top-grey', 'Cloudsoft Top — Grey', 'توب كلاودسوفت — رمادي', 'Cloudsoft Top in grey.', 'توب كلاودسوفت، رمادي.', 6.000, 'women', 1),
  ('cloudsoft-top-navy', 'Cloudsoft Top — Navy', 'توب كلاودسوفت — كحلي', 'Cloudsoft Top in navy.', 'توب كلاودسوفت، كحلي.', 6.000, 'women', 1),
  ('cloudsoft-top-onyx-black', 'Cloudsoft Top — Onyx Black', 'توب كلاودسوفت — أسود أونيكس', 'Cloudsoft Top in onyx black.', 'توب كلاودسوفت، أسود أونيكس.', 7.000, 'women', 1),
  ('define-jacket-iris-purple', 'Define Jacket — Iris Purple', 'جاكيت ديفاين — بنفسجي', 'Define Jacket in iris purple.', 'جاكيت ديفاين، بنفسجي.', 10.000, 'outerwear', 1),
  ('define-jacket-onyx-black', 'Define Jacket — Onyx Black', 'جاكيت ديفاين — أسود أونيكس', 'Define Jacket in onyx black.', 'جاكيت ديفاين، أسود أونيكس.', 10.000, 'outerwear', 1),
  ('define-jacket-steel-grey', 'Define Jacket — Steel Grey', 'جاكيت ديفاين — رمادي فولاذي', 'Define Jacket in steel grey.', 'جاكيت ديفاين، رمادي فولاذي.', 10.000, 'outerwear', 1),
  ('denver-nuggets-cap-navy', 'Denver Nuggets Cap — Navy', 'كاب دنفر ناغتس — كحلي', 'Denver Nuggets Cap in navy.', 'كاب دنفر ناغتس، كحلي.', 12.300, 'accessories', 1),
  ('energy-t-shirt-red-white', 'Energy T-Shirt — Red/White', 'تيشيرت إنرجي — أحمر وأبيض', 'Energy T-Shirt in red/white.', 'تيشيرت إنرجي، أحمر وأبيض.', 5.000, 'men', 1),
  ('flash-shorts-green', 'Flash Shorts — Green', 'شورت فلاش — أخضر', 'Flash Shorts in green.', 'شورت فلاش، أخضر.', 3.000, 'men', 1),
  ('flash-shorts-red', 'Flash Shorts — Red', 'شورت فلاش — أحمر', 'Flash Shorts in red.', 'شورت فلاش، أحمر.', 3.000, 'men', 1),
  ('gymshark-phone-strap', 'Gymshark Phone Strap', 'حزام هاتف جيمشارك', 'Gymshark Phone Strap.', 'حزام هاتف جيمشارك.', 6.500, 'accessories', 1),
  ('naples-leggings-black', 'Naples Leggings — Black', 'ليقنز نابولي — أسود', 'Naples Leggings in black.', 'ليقنز نابولي، أسود.', 7.000, 'women', 1),
  ('naples-sports-bra-pink', 'Naples Sports Bra — Pink', 'برا رياضية نابولي — وردي', 'Naples Sports Bra in pink.', 'برا رياضية نابولي، وردي.', 5.000, 'women', 1),
  ('sculpt-jacket-black', 'Sculpt Jacket — Black', 'جاكيت سكالبت — أسود', 'Sculpt Jacket in black.', 'جاكيت سكالبت، أسود.', 10.000, 'outerwear', 1),
  ('sculpt-jacket-grey', 'Sculpt Jacket — Grey', 'جاكيت سكالبت — رمادي', 'Sculpt Jacket in grey.', 'جاكيت سكالبت، رمادي.', 8.000, 'outerwear', 1),
  ('sculpt-jacket-navy', 'Sculpt Jacket — Navy', 'جاكيت سكالبت — كحلي', 'Sculpt Jacket in navy.', 'جاكيت سكالبت، كحلي.', 8.000, 'outerwear', 1),
  ('sculpt-jacket-taupe-brown', 'Sculpt Jacket — Taupe Brown', 'جاكيت سكالبت — بني فاتح', 'Sculpt Jacket in taupe brown.', 'جاكيت سكالبت، بني فاتح.', 6.000, 'outerwear', 1),
  ('sculpt-leggings-black', 'Sculpt Leggings — Black', 'ليقنز سكالبت — أسود', 'Sculpt Leggings in black.', 'ليقنز سكالبت، أسود.', 8.000, 'women', 1),
  ('sculpt-leggings-grey', 'Sculpt Leggings — Grey', 'ليقنز سكالبت — رمادي', 'Sculpt Leggings in grey.', 'ليقنز سكالبت، رمادي.', 8.000, 'women', 1),
  ('sculpt-leggings-navy', 'Sculpt Leggings — Navy', 'ليقنز سكالبت — كحلي', 'Sculpt Leggings in navy.', 'ليقنز سكالبت، كحلي.', 4.200, 'women', 1),
  ('sculpt-leggings-taupe-brown', 'Sculpt Leggings — Taupe Brown', 'ليقنز سكالبت — بني فاتح', 'Sculpt Leggings in taupe brown.', 'ليقنز سكالبت، بني فاتح.', 8.000, 'women', 1),
  ('sculpt-top-black', 'Sculpt Top — Black', 'توب سكالبت — أسود', 'Sculpt Top in black.', 'توب سكالبت، أسود.', 6.000, 'women', 1),
  ('sculpt-top-grey', 'Sculpt Top — Grey', 'توب سكالبت — رمادي', 'Sculpt Top in grey.', 'توب سكالبت، رمادي.', 8.000, 'women', 1),
  ('sculpt-top-navy', 'Sculpt Top — Navy', 'توب سكالبت — كحلي', 'Sculpt Top in navy.', 'توب سكالبت، كحلي.', 8.000, 'women', 1),
  ('sculpt-top-taupe-brown', 'Sculpt Top — Taupe Brown', 'توب سكالبت — بني فاتح', 'Sculpt Top in taupe brown.', 'توب سكالبت، بني فاتح.', 8.000, 'women', 1),
  ('sgomma-t-shirt-navy', 'Sgomma T-Shirt — Navy', 'تيشيرت سغوما — كحلي', 'Sgomma T-Shirt in navy.', 'تيشيرت سغوما، كحلي.', 5.000, 'men', 1),
  ('street-pants-navy', 'Street Pants — Navy', 'بنطال ستريت — كحلي', 'Street Pants in navy.', 'بنطال ستريت، كحلي.', 3.000, 'men', 1),
  ('tekno-shorts-black', 'Tekno Shorts — Black', 'شورت تكنو — أسود', 'Tekno Shorts in black.', 'شورت تكنو، أسود.', 3.000, 'men', 1),
  ('tekno-shorts-royal', 'Tekno Shorts — Royal', 'شورت تكنو — أزرق ملكي', 'Tekno Shorts in royal.', 'شورت تكنو، أزرق ملكي.', 3.000, 'men', 1),
  ('vanquish-stringer-vest-white', 'Vanquish Stringer Vest — White', 'ستراينجر فانكويش — أبيض', 'Vanquish Stringer Vest in white.', 'ستراينجر فانكويش، أبيض.', 8.000, 'men', 1),
  ('vanquish-t-shirt-navy-blue', 'Vanquish T-Shirt — Navy Blue', 'تيشيرت فانكويش — كحلي', 'Vanquish T-Shirt in navy blue.', 'تيشيرت فانكويش، كحلي.', 10.000, 'men', 1),
  ('vanquish-t-shirt-white', 'Vanquish T-Shirt — White', 'تيشيرت فانكويش — أبيض', 'Vanquish T-Shirt in white.', 'تيشيرت فانكويش، أبيض.', 8.000, 'men', 1),
  ('vanquish-tank-navy', 'Vanquish Tank — Navy', 'تانك فانكويش — كحلي', 'Vanquish Tank in navy.', 'تانك فانكويش، كحلي.', 9.000, 'men', 1)
-- NEVER CLOBBER A PRODUCT THAT IS ALREADY THERE. This clause used to copy the
-- seed's name, description, PRICE, category and active flag over the existing
-- row, and that made the promise at the top of IMPORT-THIS-ONE.sql — "does NOT
-- overwrite existing orders, prices or stock counts" — false for every price in
-- the shop.
--
-- It is not a theoretical risk. Measured on 2026-09-04 against a copy of the
-- live schema: a product hand-priced at 99.500 KWD with an edited name came
-- back as 10.000 and the seed's name after one import. The owner edits prices
-- in /backends, and this file is the one they are told to import into the live
-- database, so re-running it would have silently reset the whole catalogue to
-- development figures. Stock survived, because the variants clause below had
-- already been taught this lesson and says so in its own comment.
--
-- The no-op is the same idiom 1-schema and 4-promo already use. It keeps the
-- statement valid and keeps the file's real purpose intact: a MISSING product
-- is still inserted, which is what "repairs anything missing" means.
--
-- Changing seed copy therefore no longer propagates into a database that
-- already has the row. That is the correct trade: a developer can drop the row
-- and re-import, and a live shop cannot lose its prices by accident.
on duplicate key update slug = slug;   -- never clobber a value already set

insert into product_variants (sku, slug, size, stock, cost_aed) values
  ('A-CSJ-AR-L', 'cloudsoft-jacket-army-green', 'L', 1, 75),
  ('A-CSJ-AR-M', 'cloudsoft-jacket-army-green', 'M', 1, 75),
  ('A-CSJ-CH-L', 'cloudsoft-jacket-cherry-red', 'L', 1, 75),
  ('A-CSJ-CO-L', 'cloudsoft-jacket-coffee-brown', 'L', 1, 75),
  ('A-CSJ-CO-M', 'cloudsoft-jacket-coffee-brown', 'M', 2, 75),
  ('A-CSL-AR-L', 'cloudsoft-leggings-army-green', 'L', 1, 70),
  ('A-CSL-AR-M', 'cloudsoft-leggings-army-green', 'M', 1, 70),
  ('A-CSL-CH-L', 'cloudsoft-leggings-cherry-red', 'L', 1, 70),
  ('A-CSL-CO-L', 'cloudsoft-leggings-coffee-brown', 'L', 1, 70),
  ('A-CSL-CO-M', 'cloudsoft-leggings-coffee-brown', 'M', 2, 70),
  ('A-CSL-GR-L', 'cloudsoft-leggings-grey', 'L', 1, 70),
  ('A-CSL-NA-L', 'cloudsoft-leggings-navy', 'L', 1, 70),
  ('A-CSL-ON-L', 'cloudsoft-leggings-onyx-black', 'L', 2, 70),
  ('A-CSL-ON-M', 'cloudsoft-leggings-onyx-black', 'M', 2, 70),
  ('A-CST-GR-L', 'cloudsoft-top-grey', 'L', 1, 72),
  ('A-CST-NA-L', 'cloudsoft-top-navy', 'L', 1, 72),
  ('A-CST-ON-L', 'cloudsoft-top-onyx-black', 'L', 2, 72),
  ('A-CST-ON-M', 'cloudsoft-top-onyx-black', 'M', 2, 72),
  ('A-DFZJ-IR-L', 'define-jacket-iris-purple', 'L', 1, 87),
  ('A-DFZJ-IR-M', 'define-jacket-iris-purple', 'M', 1, 87),
  ('A-DFZJ-ON-L', 'define-jacket-onyx-black', 'L', 1, 87),
  ('A-DFZJ-ON-M', 'define-jacket-onyx-black', 'M', 1, 87),
  ('A-DFZJ-ST-L', 'define-jacket-steel-grey', 'L', 1, 87),
  ('A-DFZJ-ST-M', 'define-jacket-steel-grey', 'M', 1, 87),
  ('A-SJ-ON-L', 'sculpt-jacket-black', 'L', 1, 69),
  ('A-SJ-GR-L', 'sculpt-jacket-grey', 'L', 1, 69),
  ('A-SJ-GR-M', 'sculpt-jacket-grey', 'M', 1, 69),
  ('A-SJ-NA-M', 'sculpt-jacket-navy', 'M', 1, 69),
  ('A-SJ-TA-L', 'sculpt-jacket-taupe-brown', 'L', 1, 69),
  ('A-SJ-TA-M', 'sculpt-jacket-taupe-brown', 'M', 1, 69),
  ('A-SL-ON-L', 'sculpt-leggings-black', 'L', 1, 66),
  ('A-SL-GR-L', 'sculpt-leggings-grey', 'L', 1, 66),
  ('A-SL-GR-M', 'sculpt-leggings-grey', 'M', 1, 66),
  ('A-SL-NA-M', 'sculpt-leggings-navy', 'M', 1, 66),
  ('A-SL-TA-L', 'sculpt-leggings-taupe-brown', 'L', 1, 66),
  ('A-SL-TA-M', 'sculpt-leggings-taupe-brown', 'M', 1, 66),
  ('A-ST-ON-L', 'sculpt-top-black', 'L', 1, 62),
  ('A-ST-GR-L', 'sculpt-top-grey', 'L', 1, 62),
  ('A-ST-GR-M', 'sculpt-top-grey', 'M', 1, 62),
  ('A-ST-NA-M', 'sculpt-top-navy', 'M', 1, 62),
  ('A-ST-TA-L', 'sculpt-top-taupe-brown', 'L', 1, 62),
  ('A-ST-TA-M', 'sculpt-top-taupe-brown', 'M', 1, 62)
on duplicate key update
  slug = values(slug), size = values(size), cost_aed = values(cost_aed);
  -- stock deliberately NOT updated: re-seeding must not overwrite the count.

-- ---------------------------------------------------------------------------
-- What cannot be exchanged. Women's clothing is excluded by the shop's policy,
-- and "women's" is not the same set as category = 'women': the Sculpt,
-- Cloudsoft, Define and Naples JACKETS are women's line but sit under
-- 'outerwear', so a category rule alone would have left ten of them
-- exchangeable while the matching tops were not.
--
-- An UPDATE rather than a column in every INSERT above, so this stays readable
-- and re-running the seed cannot half-apply it. The owner can override any
-- single product afterwards in /backends.
update products set no_exchange = 1 where category = 'women';
update products set no_exchange = 1 where category = 'outerwear'
  and (slug like 'sculpt-%' or slug like 'cloudsoft-%' or slug like 'define-%' or slug like 'naples-%');
