-- Sporta — return and exchange requests.
--
-- Import after 1-schema.mysql.sql. Safe to re-run.
--
-- The /returns page has always been a policy page with an order number box and
-- a "send it on WhatsApp" button. Nothing was looked up and nothing was
-- recorded: the customer typed a number that was never checked against an
-- order, chose items from memory, and the whole request existed only as a
-- message in somebody's phone. Two of those are real problems — a request
-- against an order that does not exist is discovered by a driver at the door,
-- and a request nobody wrote down cannot be counted, chased or refused.
--
-- TWO TABLES, NOT COLUMNS ON `orders`. The comment on that table says why:
-- it already declares about 6.9 kB of InnoDB's 8126-byte row ceiling, and the
-- next few features to want a column there are the ones that hit the wall. A
-- request is also one-to-many over the order's lines, which is a table by
-- definition — a customer returns one of the three things they bought.

set names utf8mb4;

create table if not exists return_requests (
  id         int unsigned auto_increment primary key,
  -- What the customer is given and what the driver reads back. Generated by
  -- store_return_ref(): SPR + eight random base32 characters, unique.
  ref        varchar(20)  not null unique,
  order_id   int unsigned not null,
  -- 'return' asks for the money back, 'exchange' asks for a different size.
  -- They are one form and one table because they are one conversation with
  -- the customer, and one pickup either way.
  kind       varchar(10)  not null,
  status     varchar(12)  not null default 'new',
  reason     varchar(280) null,
  lang       varchar(2)   not null default 'ar',
  -- The phone the REQUEST was made from. Normally the order's own, and the
  -- lookup will not proceed unless it matches — but it is stored rather than
  -- joined because a customer who has changed number must still be reachable
  -- about this request, and the order's row is history.
  phone      varchar(15)  not null,
  staff_note varchar(280) null,
  created_at timestamp    not null default current_timestamp,
  decided_at timestamp    null,
  constraint fk_return_order foreign key (order_id) references orders (id) on delete cascade,
  constraint return_kind_ck   check (kind   in ('return','exchange')),
  -- new       the customer has asked, nobody has looked
  -- approved  a pickup is coming
  -- picked_up the courier has the parcel
  -- refunded  the money has gone back (or the exchange has shipped)
  -- rejected  refused, with a reason in staff_note
  -- cancelled the customer changed their mind
  constraint return_status_ck check (status in
    ('new','approved','picked_up','refunded','rejected','cancelled'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists return_request_items (
  id            int unsigned auto_increment primary key,
  request_id    int unsigned not null,
  -- The ORDER LINE, not the product. Which of the two mediums they bought is
  -- the whole question, and product_id cannot answer it.
  order_item_id int unsigned not null,
  qty           int not null,
  -- For an exchange: the size wanted instead. Null on a return, and null on an
  -- exchange for a different colour or a damaged piece, where the size is not
  -- what is wrong.
  want_size     varchar(4) null,
  constraint fk_ritem_request foreign key (request_id)    references return_requests (id) on delete cascade,
  constraint fk_ritem_line    foreign key (order_item_id) references order_items (id) on delete cascade,
  constraint ritem_qty_ck  check (qty between 1 and 99),
  constraint ritem_size_ck check (want_size is null or want_size in
    ('S','M','L','XL','2XL','3XL','4XL','5XL','ONE')),
  -- One row per line per request. A customer asking for two of the same line
  -- raises the qty; they do not get two rows, and the uniqueness is what keeps
  -- the "already requested" arithmetic in store_return_lookup() honest.
  constraint uq_ritem unique (request_id, order_item_id)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

-- The admin screen lists newest-first and filters by status; the customer-side
-- lookup asks "what has this order already had requested against it", which is
-- a scan per lookup without the second one.
create index if not exists idx_returns_status on return_requests (status, created_at);
create index if not exists idx_returns_order  on return_requests (order_id);
