#!/usr/bin/env python3
"""The Almuhallab mark as a pixel boum — the one source of the site's logo.

The ship is the same polygons the matrix-code pack draws in glyphs
(design/matrix_logo.py: BOUM), rasterised onto a cell grid:

  * wide form  — #i-boum in index.html and almuhallab/logo.svg (masthead, print)
  * square form — #i-sail in index.html and almuhallab/favicon.svg (tab, footer)

The square form is a hand-set 16×16 bitmap, not a rasterisation: at 16px
every cell is exactly one screen pixel, which is the only way a mark this
small stays sharp. It is cropped as the old square form was — one hull, one
stem, one mast, one lateen sail — and it is still a boum: double-ended, raked
stem forward, sail peaked high at the mast, sheer rising into both ends.

    python3 design/pixel_boum.py            # write all four places
    python3 design/pixel_boum.py --check    # exit 1 if any has drifted
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from matrix_logo import BOUM, on_boum  # noqa: E402  the one drawing of the ship

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "almuhallab"
PAGE = SITE / "index.html"

# ---------------------------------------------------------------- wide form
# 48×24 viewBox (the masthead's 2:1 box). The ship keeps her true 3:2
# proportions on a 36×24 grid, centred; nothing is stretched.
W_COLS, W_ROWS, W_X0 = 36, 24, 6
W_GAP = 0.18            # the gap between cells IS the code texture; one
                        # unit is ~3px at the masthead, so this reads as a seam

# ---------------------------------------------------------------- square form
# Bow to the left, as in the wide form. '#' = lit.
SQUARE = [
    "................",
    "..........#.....",
    ".........##.....",
    "........###.....",
    ".......####.....",
    "......#####.....",
    ".....######.....",
    "....#######.....",
    "...########.....",
    "..#########.....",
    ".#........#...#.",
    ".##.......#..##.",
    "..############..",
    "...##########...",
    "....########....",
    "................",
]
S_GAP = 0.06            # a hair at 16px (sub-pixel), a seam at 180px


def cells_path(cells, size, gap):
    """One path, one square subpath per lit cell."""
    s = size - gap
    return "".join(f"M{x * size + gap / 2:g} {y * size + gap / 2:g}h{s:g}v{s:g}h{-s:g}z"
                   for x, y in cells)


W_SAMPLES = 4          # 4×4 points per cell
W_COVER = 0.30         # lit when the ship covers this much of the cell: centre
                       # sampling alone dropped the thin stem into floating dots


def wide_cells():
    out, n = [], W_SAMPLES
    for r in range(W_ROWS):
        for c in range(W_COLS):
            hits = sum(on_boum((c + (i + 0.5) / n) / W_COLS, (r + (j + 0.5) / n) / W_ROWS)
                       for i in range(n) for j in range(n))
            if hits / (n * n) >= W_COVER:
                out.append((c + W_X0, r))
    return out


def square_cells():
    return [(x, y) for y, row in enumerate(SQUARE) for x, ch in enumerate(row) if ch == "#"]


def fmt(v):
    return f"{v:.3f}".rstrip("0").rstrip(".")


def wide_d():
    cells = wide_cells()
    s = 1 - W_GAP
    return "".join(f"M{fmt(x + W_GAP / 2)} {fmt(y + W_GAP / 2)}h{fmt(s)}v{fmt(s)}h-{fmt(s)}z"
                   for x, y in cells)


def square_d(unit):
    s = unit * (1 - S_GAP)
    g = unit * S_GAP / 2
    return "".join(f"M{fmt(x * unit + g)} {fmt(y * unit + g)}h{fmt(s)}v{fmt(s)}h-{fmt(s)}z"
                   for x, y in square_cells())


def symbols():
    boum = (f'<symbol id="i-boum" viewBox="0 0 48 24">'
            f'<path fill="currentColor" stroke="none" d="{wide_d()}"/></symbol>')
    sail = (f'<symbol id="i-sail" viewBox="0 0 24 24">'
            f'<path fill="currentColor" stroke="none" d="{square_d(1.5)}"/></symbol>')
    return boum, sail


def logo_svg():
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 24" role="img" aria-label="المهلب — Almuhallab">
  <!-- The Almuhallab mark, wide form: the Kuwaiti boum under sail, drawn as a
       grid of lit cells, white on the brand brown — the site-scale form of the matrix-code logo
       (design/matrix-logo/), rasterised from the same polygons. Four things
       make her a boum and all four survive the grid: she is double-ended with
       a raked stem, she carries filled lateen sails, the tall mainmast is
       forward and the short mizzen aft, and the sheer rises into both ends.
       Generated by design/pixel_boum.py — do not edit by hand. -->
  <rect width="48" height="24" fill="#6f3f1c"/>
  <path fill="#ffffff" d="{wide_d()}"/>
</svg>
'''


def favicon_svg():
    unit = 32   # 512 / 16: one cell is one pixel of a 16px tab icon
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  <!-- Almuhallab Code favicon: the square pixel boum, white on the brand
       brown (owner's request 2026-09-28: white mark, brown ground). Set on a 16×16 grid so that at 16px each cell is exactly one
       screen pixel. Kept in step with #i-sail by design/pixel_boum.py. -->
  <rect width="512" height="512" rx="96" fill="#6f3f1c"/>
  <path fill="#ffffff" d="{square_d(unit)}"/>
</svg>
'''


def with_symbols(html):
    boum, sail = symbols()
    html, n1 = re.subn(r'<symbol id="i-boum".*?</symbol>', lambda m: boum, html, count=1, flags=re.S)
    html, n2 = re.subn(r'<symbol id="i-sail".*?</symbol>', lambda m: sail, html, count=1, flags=re.S)
    if n1 != 1 or n2 != 1:
        sys.exit("#i-boum / #i-sail not found in index.html")
    return html


def main():
    check = "--check" in sys.argv
    want = {
        SITE / "logo.svg": logo_svg(),
        SITE / "favicon.svg": favicon_svg(),
        PAGE: with_symbols(PAGE.read_text()),
    }
    stale = [p.name for p, t in want.items() if p.read_text() != t]
    if check:
        if stale:
            print("pixel boum drifted: " + ", ".join(stale))
            sys.exit(1)
        print("pixel boum is current")
        return
    for p, t in want.items():
        p.write_text(t)
    print(f"wrote {len(want)} files — wide {len(wide_cells())} cells, "
          f"square {len(square_cells())} cells")


if __name__ == "__main__":
    main()
