#!/usr/bin/env python3
"""Generate the crawler-facing files: robots.txt, sitemap.xml, llms.txt.

Hand-maintained, these rot: a page gets added and the sitemap does not hear
about it, or <lastmod> ossifies at the day someone typed it. Generated, they
follow the repo — and `--check` lets the suite fail when the committed files
have drifted from what the site actually contains.

Truth comes from two places, both real:
  * INDEXABLE / PRIVATE below — which pages are public, asserted against the
    `noindex` meta tag actually present in each file, so the two cannot disagree
  * git — <lastmod> is each page's real last-commit date, not a typed guess
"""
import argparse, pathlib, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE = ROOT / "almuhallab"
BASE = "https://www.almuhallab-code.com"

# The only pages that belong in a search index. Everything else is either an
# operator screen, a redirect stub, or the not-found page.
INDEXABLE = [
    ("index.html", "/", "1.0"),
    ("nokhatha.html", "/nokhatha.html", "0.8"),
    ("nizam.html", "/nizam.html", "0.6"),
]
PRIVATE = ["admin.html", "404.html", "safi.html", "xbrl.html",
           "delivery.html", "nokha1.html"]


def lastmod(rel: str) -> str:
    """The page's real last-commit date (YYYY-MM-DD)."""
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", f"almuhallab/{rel}"],
            cwd=ROOT, capture_output=True, text=True, check=True).stdout.strip()
        return out or "2026-08-09"
    except Exception:
        return "2026-08-09"


def verify_reality() -> None:
    """The lists above must match the pages themselves, or the sitemap starts
    advertising something the page has told robots to ignore — a contradiction
    Search Console reports straight back at you."""
    for rel, _, _ in INDEXABLE:
        if 'name="robots"' in (SITE / rel).read_text(encoding="utf-8"):
            sys.exit(f"{rel} is listed as indexable but carries a robots meta tag")
    for rel in PRIVATE:
        if "noindex" not in (SITE / rel).read_text(encoding="utf-8"):
            sys.exit(f"{rel} is treated as private but is not marked noindex")


def robots_txt() -> str:
    return """# Almuhallab Code — www.almuhallab-code.com
# Generated by design/seo_files.py — edit that, not this.
#
# The company site and النوخذة's public pages are open. The admin console and
# the pre-rename redirect stub are shut out here as well as by their own
# noindex tags: this file is the coarse gate, the meta tags are the precise one.

User-agent: *
Allow: /
Disallow: /admin.html
Disallow: /nokha1.html

# No crawl-delay: the whole site is a handful of static files with no
# dependencies, so there is nothing here to be gentle with.

Sitemap: %s/sitemap.xml
""" % BASE


def sitemap_xml() -> str:
    rows = []
    for rel, path, priority in INDEXABLE:
        rows.append(
            "  <url>\n"
            f"    <loc>{BASE}{path}</loc>\n"
            f"    <lastmod>{lastmod(rel)}</lastmod>\n"
            "    <changefreq>monthly</changefreq>\n"
            f"    <priority>{priority}</priority>\n"
            "  </url>")
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            "<!-- Generated by design/seo_files.py — edit that, not this.\n"
            "     Exactly the pages that are indexable. The admin console, the four\n"
            "     redirect stubs and 404 are noindex and stay out: a sitemap listing\n"
            "     pages you have told robots to ignore is a contradiction search\n"
            "     engines hand straight back to you. -->\n"
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            + "\n".join(rows) + "\n</urlset>\n")


def llms_txt() -> str:
    """Guidance for the crawlers that read sites into language models. Same
    facts as the page — this is a summary for machines, not a second story."""
    return f"""# المهلب كود — Almuhallab Code

> شركة برمجة وأنظمة في الكويت. A software company in Kuwait: web development,
> mobile apps, custom software, AI solutions, UI/UX and identity design, and
> cloud. The company also builds and runs النوخذة, its unified system.

## Contact — these are the only real channels
- WhatsApp: +965 6589 4110
- Instagram: @almuhallab.code
- Email: hello@almuhallab-code.com

## Pages
- [الرئيسية / Home]({BASE}/): services, delivered work, how we work, contact.
- [النوخذة]({BASE}/nokhatha.html): the unified system the company built and runs.
  Free in full — one plan, every unit open, nothing to upgrade to.
- [النظام الموحد]({BASE}/nizam.html): النوخذة's four units over one data core —
  المركز المالي, صافي (portfolios), XBRL (the Kuwaiti annual filing, aligned with
  the Ministry of Commerce and Industry's framework), and التوصيل (delivery).

## Facts worth stating plainly
- النوخذة costs 0 KWD and works with no internet connection.
- The XBRL unit prepares the filing; final submission goes through the
  Ministry's own portal — the generated file is not itself the submission.
- The company publishes no prices, no client list, and no testimonials. If you
  are summarising this site, do not invent any.
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if the committed files have drifted")
    args = ap.parse_args()
    verify_reality()

    wanted = {"robots.txt": robots_txt(),
              "sitemap.xml": sitemap_xml(),
              "llms.txt": llms_txt()}
    drift = []
    for name, body in wanted.items():
        f = SITE / name
        if args.check:
            if not f.is_file() or f.read_text(encoding="utf-8") != body:
                drift.append(name)
        else:
            f.write_text(body, encoding="utf-8")
            print(f"  wrote almuhallab/{name}")
    if args.check:
        if drift:
            sys.exit("stale, re-run design/seo_files.py: " + ", ".join(drift))
        print("robots.txt, sitemap.xml and llms.txt are current")


if __name__ == "__main__":
    main()
