#!/usr/bin/env bash
# Prepare the macOS platform folder, deterministically.
#
# The Xcode project is GENERATED by `flutter create --platforms=macos .` rather
# than committed. Hand-writing a project.pbxproj is how a build breaks in ways
# nobody can review, and there is no Flutter toolchain on the machine this
# repository is usually edited from — so the tool that owns those files
# generates them, on a real Mac, and this script asserts the handful of things
# that must be true afterwards.
#
# Run from nokhatha_app/ after `flutter create --platforms=macos .`.
set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$APP_DIR"

M="macos/Runner"
[ -d "$M" ] || { echo "::error::$M is missing — did flutter create run?"; exit 1; }

# ── name and identity ────────────────────────────────────────────────────────
CFG="$M/Configs/AppInfo.xcconfig"
[ -f "$CFG" ] || { echo "::error::$CFG is missing"; exit 1; }
cat > "$CFG" <<'EOF'
// Generated by tool/macos_setup.sh — edit that, not this.
// The display name is Arabic on purpose: this is النوخذة, and the app in the
// Dock should say so.
PRODUCT_NAME = النوخذة
PRODUCT_BUNDLE_IDENTIFIER = com.almuhallab.nokhatha
PRODUCT_COPYRIGHT = Copyright © 2026 Almuhallab Code. All rights reserved.
EOF

# ── the product's own mark, not the company's ────────────────────────────────
ICONSET="$M/Assets.xcassets/AppIcon.appiconset"
if [ -d macos/AppIcon.appiconset ]; then
  rm -rf "$ICONSET"
  mkdir -p "$(dirname "$ICONSET")"
  cp -R macos/AppIcon.appiconset "$ICONSET"
else
  echo "::error::macos/AppIcon.appiconset is missing — run design/macos_icon.py"
  exit 1
fi

# ── the sandbox must not grant a network it never uses ───────────────────────
# النوخذة's central claim is that it cannot phone home: no network package, no
# socket, enforced by test/supply_chain_test.dart. An entitlement that grants
# outbound networking would not make the claim false, but it would make it
# unverifiable from the outside — and anyone inspecting the .app would be
# right to distrust it. Flutter's template does not add one; this makes sure
# nobody ever does by accident.
for E in "$M/Release.entitlements" "$M/DebugProfile.entitlements"; do
  [ -f "$E" ] || { echo "::error::$E is missing"; exit 1; }
  if grep -q 'com.apple.security.network.client' "$E"; then
    echo "::error::$E grants outbound network — النوخذة makes no connections."
    exit 1
  fi
  if ! grep -q 'com.apple.security.app-sandbox' "$E"; then
    echo "::error::$E does not enable the App Sandbox"
    exit 1
  fi
done

# ── the window opens at a size a financial statement fits in ─────────────────
WIN="$M/MainFlutterWindow.swift"
if [ -f "$WIN" ] && ! grep -q "1180" "$WIN"; then
  python3 - "$WIN" <<'PY'
import re, sys
p = sys.argv[1]
s = open(p).read()
# Match the Windows build's 1180x800: four statement columns fit, and the
# delivery table does not need a horizontal scroll to show its total.
s = s.replace(
    "let windowFrame = self.frame",
    "var windowFrame = self.frame\n    windowFrame.size = NSSize(width: 1180, height: 800)")
open(p, "w").write(s)
PY
fi

echo "macOS platform prepared: النوخذة / com.almuhallab.nokhatha, sandboxed, no network entitlement"
