// AHED brand product detail — features, fabric and the shipped size range.
//
// GENERATED by scripts/generate-ahed.mjs from data/ahed.json. Do not hand-edit.
//
// This is copy and specification only. Prices are never here: the database
// column products.price is the one create_order charges from, and a detail file
// must not be able to argue with it.
export const AHED_BRAND = {
    "en": "AHED",
    "ar": "عهد"
  }

// Wholesale was invoiced in dirhams and the shop sells in dinars, so margin
// needs a rate. Admin-only — see the note in data/ahed.json.
export const AHED_FX = {
    "aedPerKwd": 11.95,
    "asOf": "2025-05-24"
  }

// Wholesale cost of one piece, in KWD, or null if the SKU is not AHED. Used by
// the admin to show margin; never by anything a customer touches.
export function ahedCostKwd(sku) {
  const cost = AHED_COST_AED[sku]
  return cost == null ? null : Math.round((cost / AHED_FX.aedPerKwd) * 1000) / 1000
}

export const AHED_COST_AED = {
    "A-CSJ-AR-L": 75,
    "A-CSJ-AR-M": 75,
    "A-CSJ-CH-L": 75,
    "A-CSJ-CO-L": 75,
    "A-CSJ-CO-M": 75,
    "A-CSL-AR-L": 70,
    "A-CSL-AR-M": 70,
    "A-CSL-CH-L": 70,
    "A-CSL-CO-L": 70,
    "A-CSL-CO-M": 70,
    "A-CSL-GR-L": 70,
    "A-CSL-NA-L": 70,
    "A-CSL-ON-L": 70,
    "A-CSL-ON-M": 70,
    "A-CST-GR-L": 72,
    "A-CST-NA-L": 72,
    "A-CST-ON-L": 72,
    "A-CST-ON-M": 72,
    "A-DFZJ-IR-L": 87,
    "A-DFZJ-IR-M": 87,
    "A-DFZJ-ON-L": 87,
    "A-DFZJ-ON-M": 87,
    "A-DFZJ-ST-L": 87,
    "A-DFZJ-ST-M": 87,
    "A-SJ-ON-L": 69,
    "A-SJ-GR-L": 69,
    "A-SJ-GR-M": 69,
    "A-SJ-NA-M": 69,
    "A-SJ-TA-L": 69,
    "A-SJ-TA-M": 69,
    "A-SL-ON-L": 66,
    "A-SL-GR-L": 66,
    "A-SL-GR-M": 66,
    "A-SL-NA-M": 66,
    "A-SL-TA-L": 66,
    "A-SL-TA-M": 66,
    "A-ST-ON-L": 62,
    "A-ST-GR-L": 62,
    "A-ST-GR-M": 62,
    "A-ST-NA-M": 62,
    "A-ST-TA-L": 62,
    "A-ST-TA-M": 62
  }

export const AHED_COLLECTIONS = {
    "cloudsoft": {
      "name": {
        "en": "Cloudsoft",
        "ar": "كلاودسوفت"
      },
      "fabric": {
        "en": "78% Nylon · 22% Spandex",
        "ar": "٧٨٪ نايلون · ٢٢٪ إيلاستان"
      },
      "garments": {
        "top": {
          "features": [
            {
              "en": "Buttery-soft, second-skin feel",
              "ar": "ملمس ناعم كالحرير يلتصق بالجسم بلطف"
            },
            {
              "en": "Removable chest pads",
              "ar": "حشوات صدر قابلة للإزالة"
            },
            {
              "en": "High stretch, hard-wearing fabric",
              "ar": "قماش عالي المرونة ومتين"
            },
            {
              "en": "Ultimate mobility",
              "ar": "حرية حركة كاملة"
            }
          ]
        },
        "jacket": {
          "features": [
            {
              "en": "Buttery-soft, second-skin feel",
              "ar": "ملمس ناعم كالحرير يلتصق بالجسم بلطف"
            },
            {
              "en": "Sculpting cut",
              "ar": "قَصّة تُبرز القوام"
            },
            {
              "en": "High stretch, hard-wearing fabric",
              "ar": "قماش عالي المرونة ومتين"
            },
            {
              "en": "Thumbhole cuffs",
              "ar": "أكمام بفتحة إبهام"
            }
          ]
        },
        "leggings": {
          "features": [
            {
              "en": "Buttery-soft, second-skin feel",
              "ar": "ملمس ناعم كالحرير يلتصق بالجسم بلطف"
            },
            {
              "en": "High stretch, breathable fabric",
              "ar": "قماش عالي المرونة ويسمح بمرور الهواء"
            },
            {
              "en": "Discreet front-seam design",
              "ar": "قَصّة أمامية محتشمة"
            },
            {
              "en": "Ultimate mobility",
              "ar": "حرية حركة كاملة"
            }
          ]
        }
      }
    },
    "define": {
      "name": {
        "en": "Define",
        "ar": "ديفاين"
      },
      "fabric": {
        "en": "82.5% Polyester · 17.5% Spandex",
        "ar": "٨٢٫٥٪ بوليستر · ١٧٫٥٪ إيلاستان"
      },
      "garments": {
        "jacket": {
          "features": [
            {
              "en": "Soft and lightweight",
              "ar": "خفيف وناعم"
            },
            {
              "en": "High stretch, breathable fabric",
              "ar": "قماش عالي المرونة ويسمح بمرور الهواء"
            },
            {
              "en": "Sweat-wicking fabric",
              "ar": "قماش يطرد العرق"
            },
            {
              "en": "Thumbhole cuffs",
              "ar": "أكمام بفتحة إبهام"
            },
            {
              "en": "Sculpting cut",
              "ar": "قَصّة تُبرز القوام"
            },
            {
              "en": "Semi-standing collar",
              "ar": "رقبة نصف قائمة"
            },
            {
              "en": "Full-length zip",
              "ar": "سحّاب كامل"
            }
          ]
        }
      }
    },
    "sculpt": {
      "name": {
        "en": "Sculpt",
        "ar": "سكالبت"
      },
      "fabric": {
        "en": "90% Nylon · 10% Spandex",
        "ar": "٩٠٪ نايلون · ١٠٪ إيلاستان"
      },
      "garments": {
        "jacket": {
          "features": [
            {
              "en": "Soft and lightweight",
              "ar": "خفيف وناعم"
            },
            {
              "en": "High stretch, breathable fabric",
              "ar": "قماش عالي المرونة ويسمح بمرور الهواء"
            },
            {
              "en": "Sweat-wicking fabric",
              "ar": "قماش يطرد العرق"
            },
            {
              "en": "Thumbhole cuffs",
              "ar": "أكمام بفتحة إبهام"
            },
            {
              "en": "Sculpting cut",
              "ar": "قَصّة تُبرز القوام"
            },
            {
              "en": "Semi-standing collar",
              "ar": "رقبة نصف قائمة"
            }
          ]
        },
        "top": {
          "features": [
            {
              "en": "High neckline",
              "ar": "رقبة عالية"
            },
            {
              "en": "Removable chest pads",
              "ar": "حشوات صدر قابلة للإزالة"
            },
            {
              "en": "High stretch, hard-wearing fabric",
              "ar": "قماش عالي المرونة ومتين"
            },
            {
              "en": "Soft to the touch",
              "ar": "ملمس ناعم"
            }
          ]
        },
        "leggings": {
          "features": [
            {
              "en": "High waist",
              "ar": "خصر عالٍ"
            },
            {
              "en": "Lifting contour seams",
              "ar": "خياطة رافعة تُبرز القوام"
            },
            {
              "en": "Sweat-wicking fabric",
              "ar": "قماش يطرد العرق"
            },
            {
              "en": "Subtle ruched back",
              "ar": "كرمشة خفيفة من الخلف"
            }
          ]
        }
      }
    }
  }

export const AHED_COLOURS = {
    "army-green": {
      "en": "Army Green",
      "ar": "أخضر عسكري",
      "hex": "#4B5320"
    },
    "black": {
      "en": "Onyx Black",
      "ar": "أسود أونيكس",
      "hex": "#15171A"
    },
    "cherry-red": {
      "en": "Cherry Red",
      "ar": "أحمر كرزي",
      "hex": "#8E1F2B"
    },
    "coffee-brown": {
      "en": "Coffee Brown",
      "ar": "بني قهوة",
      "hex": "#4A2E21"
    },
    "grey": {
      "en": "Grey",
      "ar": "رمادي",
      "hex": "#6E7378"
    },
    "iris-purple": {
      "en": "Iris Purple",
      "ar": "بنفسجي",
      "hex": "#5B4B8A"
    },
    "navy": {
      "en": "Navy",
      "ar": "كحلي",
      "hex": "#23324D"
    },
    "onyx-black": {
      "en": "Onyx Black",
      "ar": "أسود أونيكس",
      "hex": "#15171A"
    },
    "steel-grey": {
      "en": "Steel Grey",
      "ar": "رمادي فولاذي",
      "hex": "#7C848C"
    },
    "taupe-brown": {
      "en": "Taupe Brown",
      "ar": "بني فاتح",
      "hex": "#8B7565"
    }
  }

// slug -> { collection, garment, colour, hsCode, grams, sizes[], skus{size:sku} }
export const AHED_PRODUCTS = {
    "cloudsoft-jacket-army-green": {
      "collection": "cloudsoft",
      "garment": "jacket",
      "colour": "Army",
      "hsCode": "6103320000",
      "grams": 182,
      "sizes": [
        "M",
        "L"
      ],
      "skus": {
        "L": "A-CSJ-AR-L",
        "M": "A-CSJ-AR-M"
      }
    },
    "cloudsoft-jacket-cherry-red": {
      "collection": "cloudsoft",
      "garment": "jacket",
      "colour": "Cherry",
      "hsCode": "6103320000",
      "grams": 182,
      "sizes": [
        "L"
      ],
      "skus": {
        "L": "A-CSJ-CH-L"
      }
    },
    "cloudsoft-jacket-coffee-brown": {
      "collection": "cloudsoft",
      "garment": "jacket",
      "colour": "Coffee",
      "hsCode": "6103320000",
      "grams": 182,
      "sizes": [
        "M",
        "L"
      ],
      "skus": {
        "L": "A-CSJ-CO-L",
        "M": "A-CSJ-CO-M"
      }
    },
    "cloudsoft-leggings-army-green": {
      "collection": "cloudsoft",
      "garment": "leggings",
      "colour": "Army",
      "hsCode": "6104630090",
      "grams": 159,
      "sizes": [
        "M",
        "L"
      ],
      "skus": {
        "L": "A-CSL-AR-L",
        "M": "A-CSL-AR-M"
      }
    },
    "cloudsoft-leggings-cherry-red": {
      "collection": "cloudsoft",
      "garment": "leggings",
      "colour": "Cherry",
      "hsCode": "6104630090",
      "grams": 159,
      "sizes": [
        "L"
      ],
      "skus": {
        "L": "A-CSL-CH-L"
      }
    },
    "cloudsoft-leggings-coffee-brown": {
      "collection": "cloudsoft",
      "garment": "leggings",
      "colour": "Coffee",
      "hsCode": "6104630090",
      "grams": 159,
      "sizes": [
        "M",
        "L"
      ],
      "skus": {
        "L": "A-CSL-CO-L",
        "M": "A-CSL-CO-M"
      }
    },
    "cloudsoft-leggings-grey": {
      "collection": "cloudsoft",
      "garment": "leggings",
      "colour": "Gray",
      "hsCode": "6104630090",
      "grams": 159,
      "sizes": [
        "L"
      ],
      "skus": {
        "L": "A-CSL-GR-L"
      }
    },
    "cloudsoft-leggings-navy": {
      "collection": "cloudsoft",
      "garment": "leggings",
      "colour": "Navy",
      "hsCode": "6104630090",
      "grams": 159,
      "sizes": [
        "L"
      ],
      "skus": {
        "L": "A-CSL-NA-L"
      }
    },
    "cloudsoft-leggings-onyx-black": {
      "collection": "cloudsoft",
      "garment": "leggings",
      "colour": "Onyx",
      "hsCode": "6104630090",
      "grams": 159,
      "sizes": [
        "M",
        "L"
      ],
      "skus": {
        "L": "A-CSL-ON-L",
        "M": "A-CSL-ON-M"
      }
    },
    "cloudsoft-top-grey": {
      "collection": "cloudsoft",
      "garment": "top",
      "colour": "Grey",
      "hsCode": "6109100021",
      "grams": 182,
      "sizes": [
        "L"
      ],
      "skus": {
        "L": "A-CST-GR-L"
      }
    },
    "cloudsoft-top-navy": {
      "collection": "cloudsoft",
      "garment": "top",
      "colour": "Navy",
      "hsCode": "6109100021",
      "grams": 182,
      "sizes": [
        "L"
      ],
      "skus": {
        "L": "A-CST-NA-L"
      }
    },
    "cloudsoft-top-onyx-black": {
      "collection": "cloudsoft",
      "garment": "top",
      "colour": "Onyx",
      "hsCode": "6109100021",
      "grams": 182,
      "sizes": [
        "M",
        "L"
      ],
      "skus": {
        "L": "A-CST-ON-L",
        "M": "A-CST-ON-M"
      }
    },
    "define-jacket-iris-purple": {
      "collection": "define",
      "garment": "jacket",
      "colour": "Iris",
      "hsCode": "6103320000",
      "grams": 249,
      "sizes": [
        "M",
        "L"
      ],
      "skus": {
        "L": "A-DFZJ-IR-L",
        "M": "A-DFZJ-IR-M"
      }
    },
    "define-jacket-onyx-black": {
      "collection": "define",
      "garment": "jacket",
      "colour": "Onyx",
      "hsCode": "6103320000",
      "grams": 269,
      "sizes": [
        "M",
        "L"
      ],
      "skus": {
        "L": "A-DFZJ-ON-L",
        "M": "A-DFZJ-ON-M"
      }
    },
    "define-jacket-steel-grey": {
      "collection": "define",
      "garment": "jacket",
      "colour": "Steel",
      "hsCode": "6103320000",
      "grams": 249,
      "sizes": [
        "M",
        "L"
      ],
      "skus": {
        "L": "A-DFZJ-ST-L",
        "M": "A-DFZJ-ST-M"
      }
    },
    "sculpt-jacket-black": {
      "collection": "sculpt",
      "garment": "jacket",
      "colour": "Onyx",
      "hsCode": "6103320000",
      "grams": 269,
      "sizes": [
        "L"
      ],
      "skus": {
        "L": "A-SJ-ON-L"
      }
    },
    "sculpt-jacket-grey": {
      "collection": "sculpt",
      "garment": "jacket",
      "colour": "Grey",
      "hsCode": "6103320000",
      "grams": 269,
      "sizes": [
        "M",
        "L"
      ],
      "skus": {
        "L": "A-SJ-GR-L",
        "M": "A-SJ-GR-M"
      }
    },
    "sculpt-jacket-navy": {
      "collection": "sculpt",
      "garment": "jacket",
      "colour": "Navy",
      "hsCode": "6103320000",
      "grams": 256,
      "sizes": [
        "M"
      ],
      "skus": {
        "M": "A-SJ-NA-M"
      }
    },
    "sculpt-jacket-taupe-brown": {
      "collection": "sculpt",
      "garment": "jacket",
      "colour": "Taupe",
      "hsCode": "6103320000",
      "grams": 269,
      "sizes": [
        "M",
        "L"
      ],
      "skus": {
        "L": "A-SJ-TA-L",
        "M": "A-SJ-TA-M"
      }
    },
    "sculpt-leggings-black": {
      "collection": "sculpt",
      "garment": "leggings",
      "colour": "Onyx",
      "hsCode": "6104630090",
      "grams": 234,
      "sizes": [
        "L"
      ],
      "skus": {
        "L": "A-SL-ON-L"
      }
    },
    "sculpt-leggings-grey": {
      "collection": "sculpt",
      "garment": "leggings",
      "colour": "Grey",
      "hsCode": "6104630090",
      "grams": 234,
      "sizes": [
        "M",
        "L"
      ],
      "skus": {
        "L": "A-SL-GR-L",
        "M": "A-SL-GR-M"
      }
    },
    "sculpt-leggings-navy": {
      "collection": "sculpt",
      "garment": "leggings",
      "colour": "Navy",
      "hsCode": "6104630090",
      "grams": 234,
      "sizes": [
        "M"
      ],
      "skus": {
        "M": "A-SL-NA-M"
      }
    },
    "sculpt-leggings-taupe-brown": {
      "collection": "sculpt",
      "garment": "leggings",
      "colour": "Taupe",
      "hsCode": "6104630090",
      "grams": 234,
      "sizes": [
        "M",
        "L"
      ],
      "skus": {
        "L": "A-SL-TA-L",
        "M": "A-SL-TA-M"
      }
    },
    "sculpt-top-black": {
      "collection": "sculpt",
      "garment": "top",
      "colour": "Onyx",
      "hsCode": "6109100021",
      "grams": 182,
      "sizes": [
        "L"
      ],
      "skus": {
        "L": "A-ST-ON-L"
      }
    },
    "sculpt-top-grey": {
      "collection": "sculpt",
      "garment": "top",
      "colour": "Grey",
      "hsCode": "6109100021",
      "grams": 182,
      "sizes": [
        "M",
        "L"
      ],
      "skus": {
        "L": "A-ST-GR-L",
        "M": "A-ST-GR-M"
      }
    },
    "sculpt-top-navy": {
      "collection": "sculpt",
      "garment": "top",
      "colour": "Navy",
      "hsCode": "6109100021",
      "grams": 182,
      "sizes": [
        "M"
      ],
      "skus": {
        "M": "A-ST-NA-M"
      }
    },
    "sculpt-top-taupe-brown": {
      "collection": "sculpt",
      "garment": "top",
      "colour": "Taupe",
      "hsCode": "6109100021",
      "grams": 182,
      "sizes": [
        "M",
        "L"
      ],
      "skus": {
        "L": "A-ST-TA-L",
        "M": "A-ST-TA-M"
      }
    }
  }

// Everything a product page needs about an AHED item, or null if the product is
// not one. Callers stay free of the collection/garment indirection.
export function ahedDetail(slug) {
  const p = AHED_PRODUCTS[slug]
  if (!p) return null
  const collection = AHED_COLLECTIONS[p.collection]
  const garment = collection?.garments?.[p.garment]
  if (!collection || !garment) return null
  return {
    brand: AHED_BRAND,
    collection: collection.name,
    collectionId: p.collection,
    fabric: collection.fabric,
    features: garment.features,
    colour: AHED_COLOURS[colourKey(slug, p)] ?? null,
    sizes: p.sizes,
    skus: p.skus,
    hsCode: p.hsCode,
    grams: p.grams,
  }
}

// The colour is the tail of the slug after the garment — 'sculpt-top-taupe-brown'
// is taupe-brown. Read from the slug rather than stored twice, so a renamed
// product cannot end up labelled with the old colour.
function colourKey(slug, p) {
  const prefix = `${p.collection}-${p.garment === 'leggings' ? 'leggings' : p.garment}-`
  return slug.startsWith(prefix) ? slug.slice(prefix.length) : slug.split('-').slice(2).join('-')
}

export const isAhed = (slug) => Boolean(AHED_PRODUCTS[slug])
