<?php
/**
 * Give the fifteen sizeless garments their size rows, at stock 0.
 *
 *   php /home/<user>/variants.php
 *
 * WHY THIS IS WORTH DOING AT ALL, given every row lands at zero and a zero
 * cannot be sold: /backends -> Stock reads and writes exactly these rows. With
 * none, there is nothing on that screen to type a count into, so the fifteen
 * garments are not merely out of stock — they are unreachable to the person
 * who would restock them. Creating the rows is what unblocks the owner; the
 * counts are theirs to enter and are not invented here.
 *
 * WHICH FIFTEEN. The live database has nineteen active products with no size
 * rows. Four are accessories — two backpacks, a cap, a phone strap — and a
 * backpack has no S/M/L, so they are deliberately NOT in this file and stay as
 * they are. The other fifteen are garments and are exactly the set
 * 5-missing-variants.sql was generated for; the sizes come from the shop's own
 * size_charts table.
 *
 * SAFE BY CONSTRUCTION. Fetched over plain HTTP from a PUBLIC repository, so
 * every statement is checked and refused unless it is
 *
 *     INSERT IGNORE INTO product_variants ...
 *
 * INSERT IGNORE leaves an existing row untouched, so this cannot overwrite a
 * stock count, and the table is pinned by name so nothing else can be written.
 * There is no UPDATE, DELETE or DROP here and the guard would refuse one.
 * Running it twice changes nothing.
 */

$SQL = <<<'SQLBODY'
-- Sporta — the size rows fifteen garments are missing.
--
-- GENERATED by scripts/make-missing-variants.mjs. Safe to re-run: every
-- statement is INSERT IGNORE, so a row that already exists is left alone
-- and nothing is overwritten. It does not touch orders, prices or stock
-- counts that already exist.
--
-- STOCK IS 0 ON EVERY ROW. Nothing here knows what is on the shelf, and a
-- guess would be worse than a zero: at zero the shop simply says "out of
-- stock" and cannot oversell. Enter the real counts in /backends -> Stock,
-- which reads and writes exactly these rows.
--
-- Sizes: S, M, L, XL, 2XL, 3XL, 4XL, 5XL — from this shop's own size_charts table.
-- Products: 15. Rows: 120.

set names utf8mb4;

-- cheetahs-rugby-t-shirt  (men)
insert ignore into product_variants (sku, slug, size, stock, cost_aed) values
  ('A-CHE-SH-S', 'cheetahs-rugby-t-shirt', 'S', 0, null),
  ('A-CHE-SH-M', 'cheetahs-rugby-t-shirt', 'M', 0, null),
  ('A-CHE-SH-L', 'cheetahs-rugby-t-shirt', 'L', 0, null),
  ('A-CHE-SH-XL', 'cheetahs-rugby-t-shirt', 'XL', 0, null),
  ('A-CHE-SH-2XL', 'cheetahs-rugby-t-shirt', '2XL', 0, null),
  ('A-CHE-SH-3XL', 'cheetahs-rugby-t-shirt', '3XL', 0, null),
  ('A-CHE-SH-4XL', 'cheetahs-rugby-t-shirt', '4XL', 0, null),
  ('A-CHE-SH-5XL', 'cheetahs-rugby-t-shirt', '5XL', 0, null);

-- energy-t-shirt-red-white  (men)
insert ignore into product_variants (sku, slug, size, stock, cost_aed) values
  ('A-ENE-WH-S', 'energy-t-shirt-red-white', 'S', 0, null),
  ('A-ENE-WH-M', 'energy-t-shirt-red-white', 'M', 0, null),
  ('A-ENE-WH-L', 'energy-t-shirt-red-white', 'L', 0, null),
  ('A-ENE-WH-XL', 'energy-t-shirt-red-white', 'XL', 0, null),
  ('A-ENE-WH-2XL', 'energy-t-shirt-red-white', '2XL', 0, null),
  ('A-ENE-WH-3XL', 'energy-t-shirt-red-white', '3XL', 0, null),
  ('A-ENE-WH-4XL', 'energy-t-shirt-red-white', '4XL', 0, null),
  ('A-ENE-WH-5XL', 'energy-t-shirt-red-white', '5XL', 0, null);

-- flash-shorts-green  (men)
insert ignore into product_variants (sku, slug, size, stock, cost_aed) values
  ('A-FLA-GR-S', 'flash-shorts-green', 'S', 0, null),
  ('A-FLA-GR-M', 'flash-shorts-green', 'M', 0, null),
  ('A-FLA-GR-L', 'flash-shorts-green', 'L', 0, null),
  ('A-FLA-GR-XL', 'flash-shorts-green', 'XL', 0, null),
  ('A-FLA-GR-2XL', 'flash-shorts-green', '2XL', 0, null),
  ('A-FLA-GR-3XL', 'flash-shorts-green', '3XL', 0, null),
  ('A-FLA-GR-4XL', 'flash-shorts-green', '4XL', 0, null),
  ('A-FLA-GR-5XL', 'flash-shorts-green', '5XL', 0, null);

-- flash-shorts-red  (men)
insert ignore into product_variants (sku, slug, size, stock, cost_aed) values
  ('A-FLA-RE-S', 'flash-shorts-red', 'S', 0, null),
  ('A-FLA-RE-M', 'flash-shorts-red', 'M', 0, null),
  ('A-FLA-RE-L', 'flash-shorts-red', 'L', 0, null),
  ('A-FLA-RE-XL', 'flash-shorts-red', 'XL', 0, null),
  ('A-FLA-RE-2XL', 'flash-shorts-red', '2XL', 0, null),
  ('A-FLA-RE-3XL', 'flash-shorts-red', '3XL', 0, null),
  ('A-FLA-RE-4XL', 'flash-shorts-red', '4XL', 0, null),
  ('A-FLA-RE-5XL', 'flash-shorts-red', '5XL', 0, null);

-- sgomma-t-shirt-navy  (men)
insert ignore into product_variants (sku, slug, size, stock, cost_aed) values
  ('A-SGO-NA-S', 'sgomma-t-shirt-navy', 'S', 0, null),
  ('A-SGO-NA-M', 'sgomma-t-shirt-navy', 'M', 0, null),
  ('A-SGO-NA-L', 'sgomma-t-shirt-navy', 'L', 0, null),
  ('A-SGO-NA-XL', 'sgomma-t-shirt-navy', 'XL', 0, null),
  ('A-SGO-NA-2XL', 'sgomma-t-shirt-navy', '2XL', 0, null),
  ('A-SGO-NA-3XL', 'sgomma-t-shirt-navy', '3XL', 0, null),
  ('A-SGO-NA-4XL', 'sgomma-t-shirt-navy', '4XL', 0, null),
  ('A-SGO-NA-5XL', 'sgomma-t-shirt-navy', '5XL', 0, null);

-- street-pants-navy  (men)
insert ignore into product_variants (sku, slug, size, stock, cost_aed) values
  ('A-STR-NA-S', 'street-pants-navy', 'S', 0, null),
  ('A-STR-NA-M', 'street-pants-navy', 'M', 0, null),
  ('A-STR-NA-L', 'street-pants-navy', 'L', 0, null),
  ('A-STR-NA-XL', 'street-pants-navy', 'XL', 0, null),
  ('A-STR-NA-2XL', 'street-pants-navy', '2XL', 0, null),
  ('A-STR-NA-3XL', 'street-pants-navy', '3XL', 0, null),
  ('A-STR-NA-4XL', 'street-pants-navy', '4XL', 0, null),
  ('A-STR-NA-5XL', 'street-pants-navy', '5XL', 0, null);

-- tekno-shorts-black  (men)
insert ignore into product_variants (sku, slug, size, stock, cost_aed) values
  ('A-TEK-BL-S', 'tekno-shorts-black', 'S', 0, null),
  ('A-TEK-BL-M', 'tekno-shorts-black', 'M', 0, null),
  ('A-TEK-BL-L', 'tekno-shorts-black', 'L', 0, null),
  ('A-TEK-BL-XL', 'tekno-shorts-black', 'XL', 0, null),
  ('A-TEK-BL-2XL', 'tekno-shorts-black', '2XL', 0, null),
  ('A-TEK-BL-3XL', 'tekno-shorts-black', '3XL', 0, null),
  ('A-TEK-BL-4XL', 'tekno-shorts-black', '4XL', 0, null),
  ('A-TEK-BL-5XL', 'tekno-shorts-black', '5XL', 0, null);

-- tekno-shorts-royal  (men)
insert ignore into product_variants (sku, slug, size, stock, cost_aed) values
  ('A-TEK-RO-S', 'tekno-shorts-royal', 'S', 0, null),
  ('A-TEK-RO-M', 'tekno-shorts-royal', 'M', 0, null),
  ('A-TEK-RO-L', 'tekno-shorts-royal', 'L', 0, null),
  ('A-TEK-RO-XL', 'tekno-shorts-royal', 'XL', 0, null),
  ('A-TEK-RO-2XL', 'tekno-shorts-royal', '2XL', 0, null),
  ('A-TEK-RO-3XL', 'tekno-shorts-royal', '3XL', 0, null),
  ('A-TEK-RO-4XL', 'tekno-shorts-royal', '4XL', 0, null),
  ('A-TEK-RO-5XL', 'tekno-shorts-royal', '5XL', 0, null);

-- vanquish-stringer-vest-white  (men)
insert ignore into product_variants (sku, slug, size, stock, cost_aed) values
  ('A-VAN-WH-S', 'vanquish-stringer-vest-white', 'S', 0, null),
  ('A-VAN-WH-M', 'vanquish-stringer-vest-white', 'M', 0, null),
  ('A-VAN-WH-L', 'vanquish-stringer-vest-white', 'L', 0, null),
  ('A-VAN-WH-XL', 'vanquish-stringer-vest-white', 'XL', 0, null),
  ('A-VAN-WH-2XL', 'vanquish-stringer-vest-white', '2XL', 0, null),
  ('A-VAN-WH-3XL', 'vanquish-stringer-vest-white', '3XL', 0, null),
  ('A-VAN-WH-4XL', 'vanquish-stringer-vest-white', '4XL', 0, null),
  ('A-VAN-WH-5XL', 'vanquish-stringer-vest-white', '5XL', 0, null);

-- vanquish-t-shirt-navy-blue  (men)
insert ignore into product_variants (sku, slug, size, stock, cost_aed) values
  ('A-VAN-BL-S', 'vanquish-t-shirt-navy-blue', 'S', 0, null),
  ('A-VAN-BL-M', 'vanquish-t-shirt-navy-blue', 'M', 0, null),
  ('A-VAN-BL-L', 'vanquish-t-shirt-navy-blue', 'L', 0, null),
  ('A-VAN-BL-XL', 'vanquish-t-shirt-navy-blue', 'XL', 0, null),
  ('A-VAN-BL-2XL', 'vanquish-t-shirt-navy-blue', '2XL', 0, null),
  ('A-VAN-BL-3XL', 'vanquish-t-shirt-navy-blue', '3XL', 0, null),
  ('A-VAN-BL-4XL', 'vanquish-t-shirt-navy-blue', '4XL', 0, null),
  ('A-VAN-BL-5XL', 'vanquish-t-shirt-navy-blue', '5XL', 0, null);

-- vanquish-t-shirt-white  (men)
insert ignore into product_variants (sku, slug, size, stock, cost_aed) values
  ('A-VAN-WHI-S', 'vanquish-t-shirt-white', 'S', 0, null),
  ('A-VAN-WHI-M', 'vanquish-t-shirt-white', 'M', 0, null),
  ('A-VAN-WHI-L', 'vanquish-t-shirt-white', 'L', 0, null),
  ('A-VAN-WHI-XL', 'vanquish-t-shirt-white', 'XL', 0, null),
  ('A-VAN-WHI-2XL', 'vanquish-t-shirt-white', '2XL', 0, null),
  ('A-VAN-WHI-3XL', 'vanquish-t-shirt-white', '3XL', 0, null),
  ('A-VAN-WHI-4XL', 'vanquish-t-shirt-white', '4XL', 0, null),
  ('A-VAN-WHI-5XL', 'vanquish-t-shirt-white', '5XL', 0, null);

-- vanquish-tank-navy  (men)
insert ignore into product_variants (sku, slug, size, stock, cost_aed) values
  ('A-VAN-NA-S', 'vanquish-tank-navy', 'S', 0, null),
  ('A-VAN-NA-M', 'vanquish-tank-navy', 'M', 0, null),
  ('A-VAN-NA-L', 'vanquish-tank-navy', 'L', 0, null),
  ('A-VAN-NA-XL', 'vanquish-tank-navy', 'XL', 0, null),
  ('A-VAN-NA-2XL', 'vanquish-tank-navy', '2XL', 0, null),
  ('A-VAN-NA-3XL', 'vanquish-tank-navy', '3XL', 0, null),
  ('A-VAN-NA-4XL', 'vanquish-tank-navy', '4XL', 0, null),
  ('A-VAN-NA-5XL', 'vanquish-tank-navy', '5XL', 0, null);

-- cagliari-calcio-sweatshirt-navy  (outerwear)
insert ignore into product_variants (sku, slug, size, stock, cost_aed) values
  ('A-CAG-NA-S', 'cagliari-calcio-sweatshirt-navy', 'S', 0, null),
  ('A-CAG-NA-M', 'cagliari-calcio-sweatshirt-navy', 'M', 0, null),
  ('A-CAG-NA-L', 'cagliari-calcio-sweatshirt-navy', 'L', 0, null),
  ('A-CAG-NA-XL', 'cagliari-calcio-sweatshirt-navy', 'XL', 0, null),
  ('A-CAG-NA-2XL', 'cagliari-calcio-sweatshirt-navy', '2XL', 0, null),
  ('A-CAG-NA-3XL', 'cagliari-calcio-sweatshirt-navy', '3XL', 0, null),
  ('A-CAG-NA-4XL', 'cagliari-calcio-sweatshirt-navy', '4XL', 0, null),
  ('A-CAG-NA-5XL', 'cagliari-calcio-sweatshirt-navy', '5XL', 0, null);

-- naples-leggings-black  (women)
insert ignore into product_variants (sku, slug, size, stock, cost_aed) values
  ('A-NAP-BL-S', 'naples-leggings-black', 'S', 0, null),
  ('A-NAP-BL-M', 'naples-leggings-black', 'M', 0, null),
  ('A-NAP-BL-L', 'naples-leggings-black', 'L', 0, null),
  ('A-NAP-BL-XL', 'naples-leggings-black', 'XL', 0, null),
  ('A-NAP-BL-2XL', 'naples-leggings-black', '2XL', 0, null),
  ('A-NAP-BL-3XL', 'naples-leggings-black', '3XL', 0, null),
  ('A-NAP-BL-4XL', 'naples-leggings-black', '4XL', 0, null),
  ('A-NAP-BL-5XL', 'naples-leggings-black', '5XL', 0, null);

-- naples-sports-bra-pink  (women)
insert ignore into product_variants (sku, slug, size, stock, cost_aed) values
  ('A-NAP-PI-S', 'naples-sports-bra-pink', 'S', 0, null),
  ('A-NAP-PI-M', 'naples-sports-bra-pink', 'M', 0, null),
  ('A-NAP-PI-L', 'naples-sports-bra-pink', 'L', 0, null),
  ('A-NAP-PI-XL', 'naples-sports-bra-pink', 'XL', 0, null),
  ('A-NAP-PI-2XL', 'naples-sports-bra-pink', '2XL', 0, null),
  ('A-NAP-PI-3XL', 'naples-sports-bra-pink', '3XL', 0, null),
  ('A-NAP-PI-4XL', 'naples-sports-bra-pink', '4XL', 0, null),
  ('A-NAP-PI-5XL', 'naples-sports-bra-pink', '5XL', 0, null);

-- ---------------------------------------------------------------------
-- THE ALTERNATIVE, if you would rather hide these until you have counts.
-- Run this INSTEAD of the above, not as well. They come back by setting
-- active = 1 again.
--
-- update products set active = 0 where slug in (
--   'cheetahs-rugby-t-shirt',
--   'energy-t-shirt-red-white',
--   'flash-shorts-green',
--   'flash-shorts-red',
--   'sgomma-t-shirt-navy',
--   'street-pants-navy',
--   'tekno-shorts-black',
--   'tekno-shorts-royal',
--   'vanquish-stringer-vest-white',
--   'vanquish-t-shirt-navy-blue',
--   'vanquish-t-shirt-white',
--   'vanquish-tank-navy',
--   'cagliari-calcio-sweatshirt-navy',
--   'naples-leggings-black',
--   'naples-sports-bra-pink'
-- );

SQLBODY;

$ROOT = '/home/u130124229/domains/sporta.com.kw/public_html';
$cfg = @include $ROOT . '/api/config.php';
if (!is_array($cfg)) { echo "VARIANTS config unreadable\n"; exit; }

try {
    $pdo = new PDO(
        "mysql:host={$cfg['db_host']};dbname={$cfg['db_name']};charset=utf8mb4",
        $cfg['db_user'], $cfg['db_pass'],
        [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_TIMEOUT => 15]
    );
} catch (Throwable $e) { echo "VARIANTS db unreachable\n"; exit; }

$before = (int) $pdo->query('select count(*) from product_variants')->fetchColumn();

$clean = preg_replace('/^\s*--.*$/m', '', $SQL);
$parts = array_filter(array_map('trim', explode(';', $clean)), 'strlen');

$ran = 0; $refused = []; $failed = [];
foreach ($parts as $stmt) {
    $flat = preg_replace('/\s+/', ' ', $stmt);
    if (!preg_match('/^insert ignore into product_variants /i', $flat)) {
        $refused[] = substr($flat, 0, 34);
        continue;
    }
    try { $pdo->exec($stmt); $ran++; }
    catch (Throwable $e) { $failed[] = substr($flat, 0, 34); }
}

$after = (int) $pdo->query('select count(*) from product_variants')->fetchColumn();
$nov   = (int) $pdo->query(
    'select count(*) from products p where p.active = 1 and not exists' .
    ' (select 1 from product_variants v where v.slug = p.slug)'
)->fetchColumn();

echo 'VARIANTS ran=' . $ran
   . ' rows=' . $before . '->' . $after
   . ' nosize=' . $nov
   . ' refused=' . count($refused)
   . ' failed=' . (count($failed) ? implode(',', $failed) : '0')
   . "\n";
