/**
 * Builds assets/sporta-ui.css from the per-feature files in sporta-site/css/,
 * and assets/sporta-dark.css from sporta-site/css/sporta-dark.css — both with
 * their comments removed (the reasoning lives in the sources, not on the wire).
 *
 *   node scripts/build-css.mjs           # write it
 *   node scripts/build-css.mjs --check   # fail if the built file is stale
 *
 * EDIT THE FILES IN sporta-site/css/, NEVER THE BUILT ONE. They are joined in
 * filename order, and order is cascade order — a later file wins a tie — so a
 * rule that overrides another must live in a higher-numbered file.
 *
 * ONE FILE ON THE SITE, NOT THIRTY-FOUR. Visitors still download a single
 * stylesheet: every extra <link> is another request on every page view, and
 * index.html, category.php, .htaccess, sw.js, the panel scripts and a dozen
 * rigs all name sporta-ui.css. The sources sit OUTSIDE public_html so they
 * are never served, published or cached as assets of their own.
 *
 * 21-brand-tokens.generated.css is written by make-brand-tokens.mjs and is
 * never edited by hand either. Hand-written rules used to be pasted INSIDE its
 * markers in the single file, where the generator's next run would have
 * deleted them — the category-tile rules were in there when this split was
 * made. A file of its own makes that impossible.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import postcss from 'postcss'

const ROOT = new URL('..', import.meta.url).pathname
const SRC = join(ROOT, 'sporta-site/css')
const ASSETS = join(ROOT, 'sporta-site/public_html/assets')

/* THE COMMENTS STAY IN THE SOURCES AND OFF THE WIRE, 2026-10-01. The sources
 * explain themselves at length, which is the point of them — and the built file
 * used to ship every word: sporta-ui.css was 244 KB of which 74% was comment,
 * 83 KB gzipped on the live server where the rules alone are about 10 KB, and
 * both stylesheets block the first paint. postcss removes comment NODES, so a
 * "/*" inside a string is safe, and every rule keeps its own formatting. */
const stripComments = (css) => {
  const root = postcss.parse(css)
  root.walkComments((c) => { c.remove() })
  return root.toString().replace(/[ \t]+\n/g, '\n').replace(/\n{3,}/g, '\n\n').replace(/^\n+/, '')
}

const files = readdirSync(SRC).filter((f) => /^\d\d-.+\.css$/.test(f)).sort()
// An empty source list would build an empty stylesheet and "pass" — the shop
// unstyled, and every check in this file satisfied.
if (files.length < 10) {
  console.log(`FAIL only ${files.length} source files in sporta-site/css — refusing to build`)
  process.exit(1)
}

const banner = (from) =>
  `/* GENERATED by scripts/build-css.mjs from ${from} — edit that,\n` +
  '   then run `npm run build:css`. Changes made here are overwritten. The\n' +
  '   comments that explain each rule are in the source, not shipped. */\n'
const body = files.map((f) => {
  const text = readFileSync(join(SRC, f), 'utf8')
  return text.endsWith('\n') ? text : text + '\n'
}).join('')

/* sporta-dark.css (the palette) is built the same way from its own source,
   which lived in assets/ and shipped its comments too (35 KB for ~7 KB of
   rules). It is not one of the numbered files: it loads as its own <link>. */
/* MOBILE AND DESKTOP IN THEIR OWN FILES, 2026-10-02 ("make the mobile version have native
 * setup css and desktop native separate"; the owner chose separate files). Every TOP-LEVEL
 * @media block that can only ever match a phone (max-width at most 767.98px) goes to
 * sporta-mobile.css, and every one that can only match a tablet or computer (min-width 768px
 * or more) goes to sporta-desktop.css; everything else — base rules, print, pointer,
 * reduced motion, the 1023px band — stays in sporta-ui.css. The @media wrappers stay ON the
 * moved rules, so a rule matches exactly where it did before; the <link media> on each file
 * is only a superset that lets the browser skip the other device's file.
 *
 * Load order is ui, mobile, desktop. Moving a rule later can only change the result where a
 * base rule of EQUAL specificity that came after it in the sources also styles the same
 * property — so the reorganisation was proved by a computed-style snapshot of every element,
 * 10 pages x 4 widths x 2 languages, identical before and after (scripts/_style-snap.mjs). */
const isMobile = (q) => { const m = /^\(max-width:\s*([\d.]+)px\)$/.exec(q.trim()); return !!m && +m[1] <= 767.98 }
const isDesktop = (q) => { const m = /^\(min-width:\s*([\d.]+)px\)$/.exec(q.trim()); return !!m && +m[1] >= 768 }
/* A block that a LATER shared rule overrides must not move, or it would come last and win.
 * Measured on the first build: the category section's gap and top padding came from
 * @media rules in 22- that a plain rule in 36- overrode; moved to the end, the @media won
 * and the tiles' gap went 8px -> 28px. So a block stays shared when any rule after it in
 * the sources (outside the moving blocks) sets one of its properties on one of its
 * selectors, compared by every selector in the list. */
/* Keyed by the SUBJECT of each selector (its last compound) broken into class, attribute,
 * id and pseudo-element tokens, plus the property: two rules conflict when they set the same
 * property on subjects that share any token. Exact selector text was not enough — the second
 * build kept the category blocks and still moved one whose override named the same element
 * differently (".sporta-home-products" against "main section.sporta-home-products"). Erring
 * wide only keeps more rules shared, which is always safe. */
const subjectTokens = (sel) => {
  const last = sel.replace(/\s*([>+~])\s*/g, ' ').trim().split(/\s+(?![^\[]*\])/).pop() || ''
  const t = last.match(/\.[\w\\:/\[\].-]+|\[[^\]]+\]|#[\w-]+|::?[\w-]+(\([^)]*\))?/g) || []
  const tag = /^[a-z][\w-]*/i.exec(last)
  return t.length ? t : [tag ? tag[0] : '*']
}
// a property FAMILY, so a longhand and its shorthand (padding-inline vs padding, row-gap vs
// gap, top vs inset) count as the same property
const family = (prop) => {
  if (prop.startsWith('--')) return prop
  if (/^(top|right|bottom|left|inset)/.test(prop)) return 'inset'
  if (/^(gap|row-gap|column-gap)$/.test(prop)) return 'gap'
  return prop.split('-')[0]
}
const keyset = (rule) => {
  const out = new Set()
  for (const sel of rule.selectors || []) {
    const toks = subjectTokens(sel)
    rule.each((d) => { if (d.type === 'decl') toks.forEach((tk) => out.add(tk + '{' + family(d.prop))) })
  }
  return out
}
const split = (css) => {
  const root = postcss.parse(css), mob = postcss.root(), desk = postcss.root()
  const nodes = root.nodes.slice()
  const target = nodes.map((n) => n.type === 'atrule' && n.name === 'media' ? (isMobile(n.params) ? 'm' : isDesktop(n.params) ? 'd' : '') : '')
  const keysOf = (n) => { const k = new Set(); if (n.type === 'rule') keyset(n).forEach((x) => k.add(x)); else if (n.nodes) n.walkRules((r) => keyset(r).forEach((x) => k.add(x))); return k }
  const keys = nodes.map(keysOf)
  /* EVERY phone/desktop block moves. Where a LATER shared rule overrode one, the cascade is
   * kept by COPYING that rule's conflicting declarations into the device file at the shared
   * rule's own place in the order, wrapped in the moved block's own media query — so it wins
   * exactly where, and only where, it won before. The shared rule stays where it is too. */
  const out = { m: [], d: [] }        // [position, node] pairs, sorted by original position
  let copies = 0
  for (let i = 0; i < nodes.length; i++) {
    const t = target[i]
    if (!t) continue
    out[t].push([i, 0, nodes[i]])
    const mine = keys[i]
    for (let j = i + 1; j < nodes.length; j++) {
      if (target[j] || ![...keys[j]].some((k) => mine.has(k))) continue
      const wrap = postcss.atRule({ name: 'media', params: nodes[i].params })
      const host = nodes[j].type === 'atrule' ? nodes[j].clone({ nodes: [] }) : null
      const add = (rule, into) => {
        const r = rule.clone({ nodes: [] })
        rule.each((d) => { if (d.type === 'decl' && (r.selectors || []).some((sel) => subjectTokens(sel).some((tk) => mine.has(tk + '{' + family(d.prop))))) r.append(d.clone()) })
        if (r.nodes.length) into.append(r)
      }
      if (nodes[j].type === 'rule') add(nodes[j], wrap)
      else { nodes[j].walkRules((r) => add(r, host)); if (host.nodes.length) wrap.append(host) }
      if (wrap.nodes.length) { out[t].push([j, i, wrap]); copies++ }
    }
  }
  for (const t of ['m', 'd']) {
    const dest = t === 'm' ? mob : desk
    out[t].sort((x, y) => x[0] - y[0] || x[1] - y[1]).forEach(([pos, , n]) => { if (n.parent) n.remove(); dest.append(n) })
  }
  console.log(`split: every phone/desktop block moved; ${copies} later override(s) copied after them to keep the cascade`)
  return [root.toString(), mob.toString(), desk.toString()]
}
const [uiCss, mobCss, deskCss] = split(stripComments(body))
const OUTPUTS = [
  { out: 'sporta-ui.css', css: banner('sporta-site/css/[0-9][0-9]-*.css') + uiCss.replace(/^\n+/, ''), from: `${files.length} sources (shared rules)` },
  { out: 'sporta-mobile.css', css: banner('sporta-site/css/[0-9][0-9]-*.css (phone-only @media)') + mobCss.replace(/^\n+/, '') + '\n', from: `${files.length} sources (phones, max-width 767.98px)` },
  { out: 'sporta-desktop.css', css: banner('sporta-site/css/[0-9][0-9]-*.css (768px+ @media)') + deskCss.replace(/^\n+/, '') + '\n', from: `${files.length} sources (768px and wider)` },
  { out: 'sporta-dark.css', css: banner('sporta-site/css/sporta-dark.css') + stripComments(readFileSync(join(SRC, 'sporta-dark.css'), 'utf8')), from: 'sporta-site/css/sporta-dark.css' },
]
for (const o of OUTPUTS) {
  // A stylesheet that parsed to nothing would also "build".
  if (o.css.length < (/mobile|desktop/.test(o.out) ? 400 : 2000)) { console.log(`FAIL ${o.out} built to ${o.css.length} bytes — refusing`); process.exit(1) }
}

if (process.argv.includes('--check')) {
  let bad = 0
  for (const o of OUTPUTS) {
    const same = readFileSync(join(ASSETS, o.out), 'utf8') === o.css
    if (!same) bad++
    console.log(same
      ? `ok   assets/${o.out} matches ${o.from}`
      : `FAIL assets/${o.out} does not match ${o.from} — edit the sources, then run: npm run build:css`)
  }
  process.exit(bad ? 1 : 0)
}

for (const o of OUTPUTS) {
  writeFileSync(join(ASSETS, o.out), o.css)
  console.log(`wrote assets/${o.out} from ${o.from} (${o.css.length} bytes)`)
}
