/**
 * Builds assets/sporta-ui.css from the per-feature files in sporta-site/css/.
 *
 *   node scripts/build-css.mjs           # write it
 *   node scripts/build-css.mjs --check   # fail if the built file is stale
 *
 * EDIT THE FILES IN sporta-site/css/, NEVER THE BUILT ONE. They are joined in
 * filename order, and order is cascade order — a later file wins a tie — so a
 * rule that overrides another must live in a higher-numbered file.
 *
 * ONE FILE ON THE SITE, NOT THIRTY-FOUR. Visitors still download a single
 * stylesheet: every extra <link> is another request on every page view, and
 * index.html, category.php, .htaccess, sw.js, the panel scripts and a dozen
 * rigs all name sporta-ui.css. The sources sit OUTSIDE public_html so they
 * are never served, published or cached as assets of their own.
 *
 * 21-brand-tokens.generated.css is written by make-brand-tokens.mjs and is
 * never edited by hand either. Hand-written rules used to be pasted INSIDE its
 * markers in the single file, where the generator's next run would have
 * deleted them — the category-tile rules were in there when this split was
 * made. A file of its own makes that impossible.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = new URL('..', import.meta.url).pathname
const SRC = join(ROOT, 'sporta-site/css')
const OUT = join(ROOT, 'sporta-site/public_html/assets/sporta-ui.css')

const files = readdirSync(SRC).filter((f) => /^\d\d-.+\.css$/.test(f)).sort()
// An empty source list would build an empty stylesheet and "pass" — the shop
// unstyled, and every check in this file satisfied.
if (files.length < 10) {
  console.log(`FAIL only ${files.length} source files in sporta-site/css — refusing to build`)
  process.exit(1)
}

const banner =
  '/* GENERATED by scripts/build-css.mjs from sporta-site/css/*.css — edit those,\n' +
  '   then run `npm run build:css`. Changes made here are overwritten. */\n'
const body = files.map((f) => {
  const text = readFileSync(join(SRC, f), 'utf8')
  return text.endsWith('\n') ? text : text + '\n'
}).join('')
const built = banner + body

if (process.argv.includes('--check')) {
  const same = readFileSync(OUT, 'utf8') === built
  console.log(same
    ? `ok   assets/sporta-ui.css matches its ${files.length} sources`
    : 'FAIL assets/sporta-ui.css does not match sporta-site/css/ — edit the sources, then run: npm run build:css')
  process.exit(same ? 0 : 1)
}

writeFileSync(OUT, built)
console.log(`wrote assets/sporta-ui.css from ${files.length} files (${built.length} bytes)`)
