/**
 * Builds assets/sporta-ui.css from the per-feature files in sporta-site/css/,
 * and assets/sporta-dark.css from sporta-site/css/sporta-dark.css — both with
 * their comments removed (the reasoning lives in the sources, not on the wire).
 *
 *   node scripts/build-css.mjs           # write it
 *   node scripts/build-css.mjs --check   # fail if the built file is stale
 *
 * EDIT THE FILES IN sporta-site/css/, NEVER THE BUILT ONE. They are joined in
 * filename order, and order is cascade order — a later file wins a tie — so a
 * rule that overrides another must live in a higher-numbered file.
 *
 * ONE FILE ON THE SITE, NOT THIRTY-FOUR. Visitors still download a single
 * stylesheet: every extra <link> is another request on every page view, and
 * index.html, category.php, .htaccess, sw.js, the panel scripts and a dozen
 * rigs all name sporta-ui.css. The sources sit OUTSIDE public_html so they
 * are never served, published or cached as assets of their own.
 *
 * 21-brand-tokens.generated.css is written by make-brand-tokens.mjs and is
 * never edited by hand either. Hand-written rules used to be pasted INSIDE its
 * markers in the single file, where the generator's next run would have
 * deleted them — the category-tile rules were in there when this split was
 * made. A file of its own makes that impossible.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import postcss from 'postcss'

const ROOT = new URL('..', import.meta.url).pathname
const SRC = join(ROOT, 'sporta-site/css')
const ASSETS = join(ROOT, 'sporta-site/public_html/assets')

/* THE COMMENTS STAY IN THE SOURCES AND OFF THE WIRE, 2026-10-01. The sources
 * explain themselves at length, which is the point of them — and the built file
 * used to ship every word: sporta-ui.css was 244 KB of which 74% was comment,
 * 83 KB gzipped on the live server where the rules alone are about 10 KB, and
 * both stylesheets block the first paint. postcss removes comment NODES, so a
 * "/*" inside a string is safe, and every rule keeps its own formatting. */
const stripComments = (css) => {
  const root = postcss.parse(css)
  root.walkComments((c) => { c.remove() })
  return root.toString().replace(/[ \t]+\n/g, '\n').replace(/\n{3,}/g, '\n\n').replace(/^\n+/, '')
}

const files = readdirSync(SRC).filter((f) => /^\d\d-.+\.css$/.test(f)).sort()
// An empty source list would build an empty stylesheet and "pass" — the shop
// unstyled, and every check in this file satisfied.
if (files.length < 10) {
  console.log(`FAIL only ${files.length} source files in sporta-site/css — refusing to build`)
  process.exit(1)
}

const banner = (from) =>
  `/* GENERATED by scripts/build-css.mjs from ${from} — edit that,\n` +
  '   then run `npm run build:css`. Changes made here are overwritten. The\n' +
  '   comments that explain each rule are in the source, not shipped. */\n'
const body = files.map((f) => {
  const text = readFileSync(join(SRC, f), 'utf8')
  return text.endsWith('\n') ? text : text + '\n'
}).join('')

/* sporta-dark.css (the palette) is built the same way from its own source,
   which lived in assets/ and shipped its comments too (35 KB for ~7 KB of
   rules). It is not one of the numbered files: it loads as its own <link>. */
const OUTPUTS = [
  { out: 'sporta-ui.css', css: banner('sporta-site/css/[0-9][0-9]-*.css') + stripComments(body), from: `${files.length} sources` },
  { out: 'sporta-dark.css', css: banner('sporta-site/css/sporta-dark.css') + stripComments(readFileSync(join(SRC, 'sporta-dark.css'), 'utf8')), from: 'sporta-site/css/sporta-dark.css' },
]
for (const o of OUTPUTS) {
  // A stylesheet that parsed to nothing would also "build".
  if (o.css.length < 2000) { console.log(`FAIL ${o.out} built to ${o.css.length} bytes — refusing`); process.exit(1) }
}

if (process.argv.includes('--check')) {
  let bad = 0
  for (const o of OUTPUTS) {
    const same = readFileSync(join(ASSETS, o.out), 'utf8') === o.css
    if (!same) bad++
    console.log(same
      ? `ok   assets/${o.out} matches ${o.from}`
      : `FAIL assets/${o.out} does not match ${o.from} — edit the sources, then run: npm run build:css`)
  }
  process.exit(bad ? 1 : 0)
}

for (const o of OUTPUTS) {
  writeFileSync(join(ASSETS, o.out), o.css)
  console.log(`wrote assets/${o.out} from ${o.from} (${o.css.length} bytes)`)
}
