/**
 * Emits supabase/schema.sql, seeded from the current src/lib/places.ts so the
 * database starts as an exact copy of what the site already ships.
 * Run: npm run db:schema
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const src = readFileSync("src/lib/places.ts", "utf8");
const body = src.slice(src.indexOf("export const places"));
const blocks = body.split(/\n  \{\n/).slice(1);

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
// \s* after the colon, because a long value wraps onto its own line:
//   descriptionAr:
//     "الأبراج الثلاثة …",
// Without it every description matched nothing and every seeded row went in
// carrying the literal string 'undefined'.
const field = (b, k) => (b.match(new RegExp(`${k}:\\s*"((?:[^"\\\\]|\\\\.)*)"`)) || [])[1];
const num = (b, k) => (b.match(new RegExp(`${k}: ([-\\d.]+)`)) || [])[1];

const rows = blocks.map((b, i) => {
  const arr = (b.match(/highlightsAr: \[([^\]]*)\]/) || [])[1] || "";
  const items = [...arr.matchAll(/"((?:[^"\\]|\\.)*)"/g)].map((m) => q(m[1]));
  return `  (${q(field(b,'slug'))}, ${q(field(b,'name'))}, ${q(field(b,'nameAr'))}, ${q(field(b,'category'))}, ${q(field(b,'area'))}, ${q(field(b,'areaAr'))}, ${num(b,'lat')}, ${num(b,'lng')}, ${num(b,'rating')}, ${num(b,'priceLevel')}, ${q(field(b,'emoji'))}, ${q(field(b,'taglineAr'))}, ${q(field(b,'descriptionAr'))}, ARRAY[${items.join(", ")}]::text[], ${q(field(b,'bestTimeAr'))}, ${/featured: true/.test(b)}, ${i * 10})`;
});

const sql = `-- Wain — database schema for the admin panel.
-- Generated by scripts/gen-schema.mjs from src/lib/places.ts. Do not hand-edit;
-- re-run \`npm run db:schema\` instead.
--
-- Paste this whole file into the Supabase SQL editor and run it once.

-- ---------------------------------------------------------------------------
-- Who may administer the site.
--
-- Membership here — not merely "is signed in" — is what grants write access.
-- Leaving it at "any authenticated user" would mean anyone who can create an
-- account could edit the site.
-- ---------------------------------------------------------------------------
create table if not exists public.admins (
  user_id uuid primary key references auth.users (id) on delete cascade,
  email   text not null,
  added_at timestamptz not null default now()
);
alter table public.admins enable row level security;

-- Matched directly on the row, NOT via "is the asker an admin?" — a policy on
-- admins that queries admins recurses, and PostgreSQL refuses:
--   ERROR: infinite recursion detected in policy for relation "admins"
-- That error does not stay local. Every policy on places and submissions asks
-- this table whether the user is an admin, so the recursive version took the
-- whole admin panel down with it while the public site kept working.
-- Verified against PostgreSQL 16, both the failure and this fix.
--
-- Consequence worth knowing: an admin sees only their own row here, not the
-- full list. The panel only ever asks about itself, and one admin does not
-- need to enumerate the others.
drop policy if exists "admins can see the admin list" on public.admins;
create policy "an admin can see their own row"
  on public.admins for select
  using (user_id = auth.uid());

-- ---------------------------------------------------------------------------
-- Places
-- ---------------------------------------------------------------------------
create table if not exists public.places (
  id             uuid primary key default gen_random_uuid(),
  slug           text unique not null check (slug ~ '^[a-z0-9-]+$'),
  name           text not null,
  name_ar        text not null,
  category       text not null check (category in
                   ('landmarks','restaurants','fastfood','coffee',
                    'outdoors','shopping','culture','family')),
  area           text not null,
  area_ar        text not null,
  lat            double precision not null check (lat between -90 and 90),
  lng            double precision not null check (lng between -180 and 180),
  rating         numeric(2,1) not null check (rating between 0 and 5),
  price_level    smallint not null check (price_level between 1 and 3),
  emoji          text not null default '📍',
  tagline_ar     text not null,
  description_ar text not null,
  highlights_ar  text[] not null default '{}',
  best_time_ar   text not null,
  -- Business profile. Null on the seeded places, so their pages are unchanged.
  logo_url       text,
  bio_ar         text not null default '',
  image_urls     text[] not null default '{}',
  featured       boolean not null default false,
  published      boolean not null default true,
  sort_order     integer not null default 0,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists places_category_idx on public.places (category);
create index if not exists places_sort_idx     on public.places (sort_order, created_at);

-- Keep updated_at honest.
create or replace function public.touch_updated_at() returns trigger
language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

drop trigger if exists places_touch on public.places;
create trigger places_touch before update on public.places
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- Row level security
--
-- Visitors read published rows with the anon key and can do nothing else.
-- Every write requires an authenticated session that is also in admins.
-- ---------------------------------------------------------------------------
alter table public.places enable row level security;

drop policy if exists "anyone can read published places" on public.places;
create policy "anyone can read published places"
  on public.places for select
  using (published = true);

drop policy if exists "admins read every place" on public.places;
create policy "admins read every place"
  on public.places for select
  using (exists (select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admins insert places" on public.places;
create policy "admins insert places"
  on public.places for insert
  with check (exists (select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admins update places" on public.places;
create policy "admins update places"
  on public.places for update
  using (exists (select 1 from public.admins a where a.user_id = auth.uid()))
  with check (exists (select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admins delete places" on public.places;
create policy "admins delete places"
  on public.places for delete
  using (exists (select 1 from public.admins a where a.user_id = auth.uid()));

-- ---------------------------------------------------------------------------
-- Business submissions — "سجّل مكانك"
--
-- Anyone in Kuwait can submit their business from /add/, free, without an
-- account. That means this is the one table the anon key may write to, so the
-- policies are the security boundary and are deliberately narrow:
--
--   * insert only. There is no anon select policy, so a submitter cannot read
--     back this table — not their own row, not anyone else's. Submissions carry
--     phone numbers and emails, and an open select would publish the lot.
--   * the insert check pins status to 'pending' and review fields to null, so
--     nobody can post a row that is already approved.
--   * a submission is NOT a place. Nothing here reaches the site until an admin
--     approves it, which copies the fields into public.places.
-- ---------------------------------------------------------------------------
create table if not exists public.submissions (
  id             uuid primary key default gen_random_uuid(),
  status         text not null default 'pending'
                   check (status in ('pending','approved','rejected')),

  -- the business
  name           text not null check (length(btrim(name)) between 2 and 120),
  name_ar        text not null check (length(btrim(name_ar)) between 2 and 120),
  category       text not null check (category in
                   ('landmarks','restaurants','fastfood','coffee',
                    'outdoors','shopping','culture','family')),
  area_ar        text not null check (length(btrim(area_ar)) between 2 and 80),
  address_ar     text not null default '' check (length(address_ar) <= 300),
  lat            double precision check (lat between 28.5 and 30.2),
  lng            double precision check (lng between 46.5 and 48.6),
  price_level    smallint not null default 2 check (price_level between 1 and 3),
  tagline_ar     text not null check (length(btrim(tagline_ar)) between 4 and 160),
  description_ar text not null default '' check (length(description_ar) <= 1200),

  -- how to reach the business publicly
  phone          text not null default '' check (length(phone) <= 40),
  instagram      text not null default '' check (length(instagram) <= 80),
  -- Scheme-checked at rest. Nothing renders this today, but the day someone
  -- puts it in an href, a stored 'javascript:…' becomes stored XSS. Rejecting
  -- it here means that day is safe by default rather than by remembering.
  website        text not null default ''
                   check (website = '' or
                          (length(website) <= 200 and website ~* '^https?://[^[:space:]]{3,}$')),

  -- how to reach whoever submitted it (never shown on the site)
  contact_name   text not null check (length(btrim(contact_name)) between 2 and 120),
  contact_email  text not null check (contact_email ~ '^[^@[:space:]]+@[^@[:space:]]+\\.[^@[:space:]]+$'),
  contact_phone  text not null default '' check (length(contact_phone) <= 40),

  -- what the business sent, as storage paths in the private bucket. Nothing
  -- here is public: an admin approves images one by one, and only the approved
  -- ones are copied into the public bucket.
  logo_path      text,
  image_paths    text[] not null default '{}' check (array_length(image_paths, 1) is null
                                                     or array_length(image_paths, 1) <= 8),
  bio_ar         text not null default '' check (length(bio_ar) <= 800),

  -- moderation
  admin_note     text not null default '',
  reviewed_at    timestamptz,
  reviewed_by    uuid references auth.users (id) on delete set null,
  published_slug text,

  created_at     timestamptz not null default now()
);

create index if not exists submissions_status_idx on public.submissions (status, created_at desc);

-- The same business submitted twice while the first is still pending is almost
-- always a double-tap on the button, not a second business.
create unique index if not exists submissions_pending_unique
  on public.submissions (lower(btrim(name_ar)), lower(btrim(area_ar)))
  where status = 'pending';

alter table public.submissions enable row level security;

drop policy if exists "anyone may submit a business" on public.submissions;
create policy "anyone may submit a business"
  on public.submissions for insert
  to anon, authenticated
  with check (
    status = 'pending'
    and reviewed_at is null
    and reviewed_by is null
    and published_slug is null
    and admin_note = ''
  );

drop policy if exists "admins read submissions" on public.submissions;
create policy "admins read submissions"
  on public.submissions for select
  using (exists (select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admins update submissions" on public.submissions;
create policy "admins update submissions"
  on public.submissions for update
  using (exists (select 1 from public.admins a where a.user_id = auth.uid()))
  with check (exists (select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admins delete submissions" on public.submissions;
create policy "admins delete submissions"
  on public.submissions for delete
  using (exists (select 1 from public.admins a where a.user_id = auth.uid()));

-- ---------------------------------------------------------------------------
-- Business media — logos and photos
--
-- Two buckets, because "approved" has to be a property of where a file lives,
-- not a flag someone remembers to check:
--
--   business-pending : PRIVATE. Anyone may upload here, nobody but an admin
--                      can read it. An unreviewed photo of someone's shop is
--                      not public just because its URL is hard to guess.
--   business-media   : PUBLIC. Only admins may write. A file is here only
--                      because a human approved it, so anything the site
--                      renders has been seen.
--
-- Approving copies the bytes across and records the public URL on the place.
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('business-pending', 'business-pending', false, 5242880,
   array['image/jpeg','image/png','image/webp']),
  ('business-media',   'business-media',   true,  5242880,
   array['image/jpeg','image/png','image/webp'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "anyone may upload media for review" on storage.objects;
create policy "anyone may upload media for review"
  on storage.objects for insert
  to anon, authenticated
  with check (bucket_id = 'business-pending');

drop policy if exists "admins read pending media" on storage.objects;
create policy "admins read pending media"
  on storage.objects for select
  using (bucket_id = 'business-pending'
         and exists (select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admins delete pending media" on storage.objects;
create policy "admins delete pending media"
  on storage.objects for delete
  using (bucket_id = 'business-pending'
         and exists (select 1 from public.admins a where a.user_id = auth.uid()));

-- The public bucket serves reads without consulting policies; these govern who
-- may put something in it, which is the part that matters.
drop policy if exists "admins publish media" on storage.objects;
create policy "admins publish media"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'business-media'
              and exists (select 1 from public.admins a where a.user_id = auth.uid()));

drop policy if exists "admins remove published media" on storage.objects;
create policy "admins remove published media"
  on storage.objects for delete
  using (bucket_id = 'business-media'
         and exists (select 1 from public.admins a where a.user_id = auth.uid()));

-- ---------------------------------------------------------------------------
-- Seed: the ${rows.length} places the site ships with today.
-- ---------------------------------------------------------------------------
insert into public.places
  (slug, name, name_ar, category, area, area_ar, lat, lng, rating, price_level,
   emoji, tagline_ar, description_ar, highlights_ar, best_time_ar, featured, sort_order)
values
${rows.join(",\n")}
on conflict (slug) do nothing;
`;

mkdirSync("supabase", { recursive: true });
writeFileSync("supabase/schema.sql", sql);
console.log(`supabase/schema.sql written — ${rows.length} places seeded`);
