<?php
/**
 * Bring the live database up to what the current site expects.
 *
 *   php /home/<user>/migrate.php
 *
 * WHY THIS EXISTS. The shop's PHP was updated; schema-check.php then reported
 * the live database missing FOUR TABLES and FIVE COLUMNS against a fresh
 * install — return_requests, return_request_items, wallet_passes, assistant_qa,
 * and the five email_otp columns on admin_users. Those are the migrations
 * CLAUDE.md records as having been handed over as "run these two by hand"
 * every time. Until they exist, a customer submitting a return meets a missing
 * table, the admin's emailed sign-in code cannot be stored, Wallet passes have
 * nowhere to live and the سبورتا AI cannot answer a taught question.
 *
 * IT IS SAFE BY CONSTRUCTION, NOT BY PROMISE. This file is fetched over plain
 * HTTP from a PUBLIC repository by a cron job, so anything it can do, anyone
 * able to influence that fetch can do. Every statement is therefore checked
 * before it runs and REFUSED unless it is one of exactly two shapes:
 *
 *     CREATE TABLE IF NOT EXISTS ...
 *     ALTER TABLE ... ADD COLUMN IF NOT EXISTS ...
 *
 * Both are additive and both are no-ops when the thing already exists. There
 * is no DROP, no DELETE, no UPDATE and no INSERT here, and the guard means one
 * cannot be smuggled in by editing the SQL below — it would be refused and
 * named. The worst this can do, run by anyone, any number of times, is nothing.
 *
 * It prints what it created and anything refused. FOUR REFUSALS ARE EXPECTED
 * and are not a problem: each source file opens with `set names utf8mb4`, which
 * is a session setting the PDO connection above already makes through
 * charset=utf8mb4 in its DSN. Refusing it costs nothing; allowing arbitrary SET
 * would widen the guard for no gain.
 */

$SQL = <<<'SQLBODY'
-- ==== 7-returns.sql ====
-- Sporta — return and exchange requests.
--
-- Import after 1-schema.mysql.sql. Safe to re-run.
--
-- The /returns page has always been a policy page with an order number box and
-- a "send it on WhatsApp" button. Nothing was looked up and nothing was
-- recorded: the customer typed a number that was never checked against an
-- order, chose items from memory, and the whole request existed only as a
-- message in somebody's phone. Two of those are real problems — a request
-- against an order that does not exist is discovered by a driver at the door,
-- and a request nobody wrote down cannot be counted, chased or refused.
--
-- TWO TABLES, NOT COLUMNS ON `orders`. The comment on that table says why:
-- it already declares about 6.9 kB of InnoDB's 8126-byte row ceiling, and the
-- next few features to want a column there are the ones that hit the wall. A
-- request is also one-to-many over the order's lines, which is a table by
-- definition — a customer returns one of the three things they bought.

set names utf8mb4;

create table if not exists return_requests (
  id         int unsigned auto_increment primary key,
  -- What the customer is given and what the driver reads back. Generated by
  -- store_return_ref(): SPR + eight random base32 characters, unique.
  ref        varchar(20)  not null unique,
  order_id   int unsigned not null,
  -- 'return' asks for the money back, 'exchange' asks for a different size.
  -- They are one form and one table because they are one conversation with
  -- the customer, and one pickup either way.
  kind       varchar(10)  not null,
  status     varchar(12)  not null default 'new',
  reason     varchar(280) null,
  lang       varchar(2)   not null default 'ar',
  -- The phone the REQUEST was made from. Normally the order's own, and the
  -- lookup will not proceed unless it matches — but it is stored rather than
  -- joined because a customer who has changed number must still be reachable
  -- about this request, and the order's row is history.
  phone      varchar(15)  not null,
  staff_note varchar(280) null,
  created_at timestamp    not null default current_timestamp,
  decided_at timestamp    null,
  constraint fk_return_order foreign key (order_id) references orders (id) on delete cascade,
  constraint return_kind_ck   check (kind   in ('return','exchange')),
  -- new       the customer has asked, nobody has looked
  -- approved  a pickup is coming
  -- picked_up the courier has the parcel
  -- refunded  the money has gone back (or the exchange has shipped)
  -- rejected  refused, with a reason in staff_note
  -- cancelled the customer changed their mind
  constraint return_status_ck check (status in
    ('new','approved','picked_up','refunded','rejected','cancelled'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists return_request_items (
  id            int unsigned auto_increment primary key,
  request_id    int unsigned not null,
  -- The ORDER LINE, not the product. Which of the two mediums they bought is
  -- the whole question, and product_id cannot answer it.
  order_item_id int unsigned not null,
  qty           int not null,
  -- For an exchange: the size wanted instead. Null on a return, and null on an
  -- exchange for a different colour or a damaged piece, where the size is not
  -- what is wrong.
  want_size     varchar(4) null,
  constraint fk_ritem_request foreign key (request_id)    references return_requests (id) on delete cascade,
  constraint fk_ritem_line    foreign key (order_item_id) references order_items (id) on delete cascade,
  constraint ritem_qty_ck  check (qty between 1 and 99),
  constraint ritem_size_ck check (want_size is null or want_size in
    ('S','M','L','XL','2XL','3XL','4XL','5XL','ONE')),
  -- One row per line per request. A customer asking for two of the same line
  -- raises the qty; they do not get two rows, and the uniqueness is what keeps
  -- the "already requested" arithmetic in store_return_lookup() honest.
  constraint uq_ritem unique (request_id, order_item_id)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

-- The admin screen lists newest-first and filters by status; the customer-side
-- lookup asks "what has this order already had requested against it", which is
-- a scan per lookup without the second one.
create index if not exists idx_returns_status on return_requests (status, created_at);
create index if not exists idx_returns_order  on return_requests (order_id);

-- ==== 8-email-otp.sql ====
-- Sporta — a one-time code by email, as a second factor for the admin panel.
--
-- Import after 1-schema.mysql.sql. Safe to re-run.
--
-- WHY, WHEN TOTP ALREADY EXISTS. The panel has had TOTP since it was written
-- and it is the stronger factor — an authenticator app holds a secret that
-- never travels, while an emailed code is only as safe as the mailbox. But
-- TOTP costs the owner a phone, an app, a scanned QR and a saved recovery
-- path, and an owner who will not do that ends up with ONE factor rather than
-- two. A code to the address they already read every day is the second factor
-- they will actually turn on, and one factor plus a mailbox beats one factor.
--
-- Only one of the two is ever in force. TOTP wins where both are enrolled:
-- store_login() checks it first, and this is never reached.
--
-- COLUMNS ON admin_users RATHER THAN A TABLE OF THEIR OWN. Unlike `orders`,
-- which the schema warns is near InnoDB's row ceiling, admin_users is eleven
-- narrow columns and holds one row per person who can sign in. The state here
-- is strictly one-per-account and dies with the account, so a second table
-- would be a join to say what a column says.

set names utf8mb4;

-- Whether this account uses an emailed code at all. Off by default: turning it
-- on is a deliberate act that costs the current password and, if TOTP is
-- already on, a fresh code — the same price as every other change to who can
-- sign in.
alter table admin_users
  add column if not exists email_otp_enabled tinyint(1) not null default 0;

-- THE CODE IS NEVER STORED. What is stored is HMAC-SHA256 of it, keyed on
-- cron_key from api/config.php — the same construction store_review_sig() uses
-- for review links.
--
-- A plain hash would not be enough. Six digits is a million possibilities, and
-- sha256 over a million inputs is the work of a moment on any laptop, so a
-- leaked database row would hand over the live code. Keyed on a secret the
-- database does not contain, the row is worth nothing without config.php as
-- well — and store_email_otp_issue() refuses to work at all when cron_key is
-- empty rather than quietly keying everything on "".
alter table admin_users
  add column if not exists email_otp_hash char(64) null;

-- When it stops being accepted. Ten minutes: long enough to open a mail app on
-- a phone, short enough that a code read over someone's shoulder is stale
-- before it can be typed somewhere else.
alter table admin_users
  add column if not exists email_otp_expires timestamp null;

-- When the last one was sent, so "send it again" cannot be used to post a
-- thousand messages to an address, or to keep a code alive for ever by
-- refreshing it.
alter table admin_users
  add column if not exists email_otp_sent_at timestamp null;

-- Wrong guesses against the CURRENT code. Five and the code is destroyed, so a
-- guesser has to make the shop send a new one — which is itself throttled —
-- rather than grinding a single code a million times. Separate from
-- failed_attempts, which counts against the account lock and is not reset when
-- a new code is issued.
alter table admin_users
  add column if not exists email_otp_attempts int not null default 0;

-- ==== wallet.mysql.sql ====
-- Sporta — Apple Wallet passes.
--
-- ADDITIVE, and safe to re-run. phpMyAdmin -> your database -> Import.
--
-- It also rides in database-sql/IMPORT-THIS-ONE.sql, so a fresh install needs
-- nothing done by hand. This used to say "fresh installs get this from
-- schema.mysql.sql" and that was simply not true: schema.mysql.sql has never
-- created wallet_passes. Measured by importing every part into an empty
-- database and diffing it against the working shop — the table was in one and
-- not the other, and because db-audit.php lists it as optional the only sign
-- was a warning that read like a feature nobody had switched on.

set names utf8mb4;

-- ONE SERIAL PER CUSTOMER, FOR EVER.
--
-- The serial is what the till scans and what Wallet uses to update a pass. If
-- it were minted per request, a customer who re-added their card would have two
-- cards with two histories and a shop assistant with no way to tell which is
-- the real one. So it is issued once, stored, and returned unchanged every time
-- afterwards.
--
-- Keyed by PHONE because that is what the shop already identifies a customer
-- by: orders carry customer_phone, there is no accounts table, and a phone is
-- what somebody reads out at a till.
create table if not exists wallet_passes (
  id           int unsigned auto_increment primary key,
  kind         varchar(10)  not null default 'loyalty',
  -- The serial on the pass and in the barcode. Unique across kinds: a till
  -- scanning one should never have to ask which sort of card it was.
  serial       varchar(40)  not null unique,
  -- Eight digits, no country code — the same normalisation store.php does.
  phone        varchar(16)  null,
  name         varchar(80)  null,
  -- Points are DERIVED from paid orders, not stored, so they cannot drift from
  -- what the customer actually spent. This is the balance at the moment the
  -- pass was last issued, kept only so a push notification can say what
  -- changed.
  points_at_issue int unsigned not null default 0,
  issued_at    timestamp    not null default current_timestamp,
  updated_at   timestamp    not null default current_timestamp on update current_timestamp,
  -- Wallet gives every installed pass a device id and a push token when it
  -- registers. Both are null until the web service exists; the columns are here
  -- so adding it later is not another migration on a live table.
  device_id    varchar(64)  null,
  push_token   varchar(128) null,
  constraint wallet_kind_ck check (kind in ('loyalty','coupon','giftcard'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create index if not exists idx_wallet_phone on wallet_passes (kind, phone);

-- ==== assistantqa.mysql.sql ====
-- سبورتا AI — the answers the shop writes itself. Additive: safe to run on a
-- live shop.
--
-- WHY THIS TABLE EXISTS. The assistant answers from a fixed set of intents —
-- delivery, payment, returns, sizes, stock, orders — and everything outside
-- that set falls through to "a colleague will follow up" and lands in
-- assistant_outbox. That outbox is already the list of questions the shop
-- could not handle; this table is where the shop writes the answer so the same
-- question is never handed off twice.
--
-- It is NOT a second brain. A row here is the owner's own sentence, returned
-- verbatim — not a prompt, not a hint to a model, not something rephrased on
-- the way out. The assistant's whole design is that a plausible answer is
-- worse than none; a curated answer is the one case where the shop has already
-- decided what the true answer is, so it ships exactly as written.
--
-- TWO LANGUAGES, BOTH REQUIRED. A shop that answers Arabic questions in
-- English has not answered them. The screen asks for both.

set names utf8mb4;

create table if not exists assistant_qa (
  id          int unsigned auto_increment primary key,

  -- WHAT THE CUSTOMER MIGHT ASK, in the owner's words. Matching folds both
  -- sides through assistant_normalise() and then requires every significant
  -- word of this line to appear in the customer's message, so this is a
  -- shortest-form phrase ("هل تفتحون يوم الجمعة" / "open on friday"), not a
  -- sentence to be matched literally. Either language may be left empty when
  -- the question only ever arrives in one of them.
  q_ar        varchar(200) not null default '',
  q_en        varchar(200) not null default '',

  -- WHAT THE SHOP SAYS BACK. Capped at the same 1000 as assistant_outbox.reply
  -- so a curated answer can never be longer than what the outbox can record.
  a_ar        varchar(1000) not null,
  a_en        varchar(1000) not null,

  -- Hidden rather than deleted, the same convention as brands: an answer that
  -- turned out to be wrong should stop being given immediately, and be
  -- readable afterwards by whoever asks why the shop said it.
  active      tinyint(1)   not null default 1,

  -- READ BY THE SCREEN, not by the matcher. "This answer has been used 40
  -- times" is how the owner knows which ones are earning their place, and a
  -- row that has never matched is usually a phrase nobody types.
  hits        int unsigned not null default 0,
  last_hit_at timestamp    null,

  created_at  timestamp    not null default current_timestamp,
  updated_at  timestamp    not null default current_timestamp on update current_timestamp
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

-- The matcher reads every active row on a miss-heavy path, so the index that
-- matters is the one that keeps hidden rows out of that scan.
create index if not exists idx_assistant_qa_active on assistant_qa (active, id);

SQLBODY;

$ROOT = '/home/u130124229/domains/sporta.com.kw/public_html';
$cfg = @include $ROOT . '/api/config.php';
if (!is_array($cfg)) { echo "MIGRATE config unreadable\n"; exit; }

try {
    $pdo = new PDO(
        "mysql:host={$cfg['db_host']};dbname={$cfg['db_name']};charset=utf8mb4",
        $cfg['db_user'], $cfg['db_pass'],
        [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION, PDO::ATTR_TIMEOUT => 15]
    );
} catch (Throwable $e) { echo "MIGRATE db unreachable\n"; exit; }

// Strip line comments, then split on the statement terminator. These files
// contain no strings carrying a semicolon, which is why this is adequate here
// and would not be in general.
$clean = preg_replace('/^\s*--.*$/m', '', $SQL);
$parts = array_filter(array_map('trim', explode(';', $clean)), 'strlen');

$ran = 0; $refused = []; $failed = [];
foreach ($parts as $stmt) {
    $flat = preg_replace('/\s+/', ' ', $stmt);
    $ok = preg_match('/^create table if not exists /i', $flat)
       || preg_match('/^alter table [`a-z0-9_]+ add column if not exists /i', $flat)
       // Indexes belong to the tables above and are just as additive. Left out
       // of the first version of this guard, which created return_requests
       // without either of its indexes and reported success — the tables were
       // right and every query against them would have been a full scan.
       || preg_match('/^create (unique )?index if not exists /i', $flat);
    if (!$ok) { $refused[] = substr($flat, 0, 40); continue; }
    try { $pdo->exec($stmt); $ran++; }
    catch (Throwable $e) { $failed[] = substr($flat, 0, 40); }
}

echo 'MIGRATE ran=' . $ran
   . ' refused=' . (count($refused) ? count($refused) . '[' . implode('|', array_slice($refused, 0, 3)) . ']' : '0')
   . ' failed=' . (count($failed) ? count($failed) . '[' . implode('|', array_slice($failed, 0, 3)) . ']' : '0')
   . "\n";
