<?php
/**
 * Schema drift: what the LIVE database is missing against a fresh install.
 *
 *   php scripts/schema-check.php          (from a checkout; against the sandbox locally)
 *
 * RETIRED 2026-10-08 — NOW A THIN WRAPPER OF scripts/live/live-schema-full.php, which does the
 * whole job and is the only copy of it. Kept, rather than deleted, because other files name this
 * one (scripts/migrate-live.php's header) and a name that still runs is a name that still means
 * something.
 *
 * WHY IT WAS RETIRED. This file carried a hand-typed list of "every table and column a fresh
 * install has": 28 tables, 307 columns, taken once from IMPORT-THIS-ONE.sql and never again. By
 * the time it was retired the shop had 55 tables and 499 columns, so a live database missing every
 * one of the 27 newer tables would have read as complete — the hardcoded-manifest failure CLAUDE.md
 * records twice ("The second hardcoded manifest"), on a third surface. live-schema-full.php's list
 * is GENERATED by scripts/make-schema-manifest.mjs, whose --check fails when it drifts, and it also
 * compares column types and indexes and names the migrate-*.php that repairs each gap.
 *
 * ON THE SERVER, fetch live-schema-full.php itself (the cron channel fetches exactly one file, so a
 * copy of this wrapper alone has nothing to require — it says so in one line rather than dying in
 * silence):
 *
 *   wget -nv -O r.php https://raw.githubusercontent.com/hkspower/wain/<40-char-sha>/scripts/live/live-schema-full.php && php r.php
 *
 * READ-ONLY, as before: live-schema-full.php reads information_schema and writes nothing.
 */
declare(strict_types=1);

$full = __DIR__ . '/live/live-schema-full.php';
if (!is_file($full)) {
    echo "DRIFT retired - this checker is now scripts/live/live-schema-full.php; fetch and run that file\n";
    exit;
}
require $full;
