-- Sporta — product catalogue.
--
-- GENERATED by scripts/generate-seed.mjs from sporta-html5/assets/products.js.
-- Do not hand-edit: change the catalogue and regenerate, or the site will show
-- one price while the database charges another. The database price is the one
-- that wins — create_order reads it and the browser never sends a price.
--
-- Safe to re-run. Matching is on slug, so re-running updates prices and names
-- in place and never duplicates a product.
--
-- 20 products. Generated from the catalogue, not typed by hand.

insert into public.products
  (slug, name_en, name_ar, desc_en, desc_ar, price, category, active)
values
  ('rheo-seamless-set', 'RHEO Seamless Set', 'طقم ريو سيملس', 'Women’s seamless leggings + top set.', 'طقم ليقنز وتوب حريمي سيملس.', 24.000, 'women', true),
  ('rheo-zip-top', 'RHEO Zip Top', 'توب ريو بسحاب', 'Long-sleeve zip training top.', 'توب تدريب بأكمام طويلة وسحاب.', 14.500, 'women', true),
  ('sporta-compression-tee', 'SPORTA Compression Tee', 'تيشيرت سبورتا ضاغط', 'Men’s performance compression tee.', 'تيشيرت رجالي ضاغط للأداء.', 11.000, 'men', true),
  ('vanquish-tank', 'Vanquish Training Tank', 'فانكويش تانك', 'Breathable sleeveless training tank.', 'تانك تدريب خفيف وقابل للتهوية.', 9.500, 'men', true),
  ('ate-felpa-hoodie', 'ATE Felpa Hoodie — Navy', 'هودي ATE فيلبا — كحلي', 'Heavyweight cotton-blend hoodie.', 'هودي قطني ثقيل عالي الجودة.', 19.000, 'outerwear', true),
  ('ate-smart-jacket', 'ATE Smart Jacket', 'جاكيت ATE سمارت', 'Lightweight zip training jacket.', 'جاكيت تدريب خفيف بسحاب.', 22.000, 'outerwear', true),
  ('nba-cap', 'NBA Team Cap', 'كاب NBA', 'Official-style team snapback cap.', 'كاب فريق بتصميم رسمي.', 8.000, 'accessories', true),
  ('rheo-flex-leggings', 'RHEO Flex Leggings', 'ليقنز ريو فليكس', 'High-waist squat-proof leggings.', 'ليقنز بخصر عالٍ غير شفاف.', 16.000, 'women', true),
  ('rheo-sports-bra', 'RHEO Sports Bra', 'حمالة رياضية ريو', 'Medium-support training bra.', 'حمالة تدريب بدعم متوسط.', 10.500, 'women', true),
  ('rheo-crop-tee', 'RHEO Crop Tee', 'تيشيرت كروب ريو', 'Soft cropped training tee.', 'تيشيرت تدريب قصير وناعم.', 8.500, 'women', true),
  ('eyesport-shorts', 'Eyesportwear Training Shorts', 'شورت تدريب آي سبورت', 'Quick-dry 7" training shorts.', 'شورت تدريب سريع الجفاف.', 9.000, 'men', true),
  ('sporta-joggers', 'SPORTA Joggers', 'بنطلون سبورتا جوجر', 'Tapered fleece joggers.', 'بنطلون رياضي بقصة مضيّقة.', 15.000, 'men', true),
  ('vanquish-long-sleeve', 'Vanquish Long Sleeve', 'فانكويش أكمام طويلة', 'Fitted long-sleeve training top.', 'توب تدريب ضيق بأكمام طويلة.', 13.000, 'men', true),
  ('sporta-zip-hoodie', 'SPORTA Zip Hoodie', 'هودي سبورتا بسحاب', 'Full-zip brushed-back hoodie.', 'هودي بسحاب كامل ومبطن.', 21.000, 'outerwear', true),
  ('ate-windbreaker', 'ATE Windbreaker', 'جاكيت ATE ويندبريكر', 'Water-resistant packable shell.', 'جاكيت خفيف مقاوم للماء.', 24.000, 'outerwear', true),
  ('sporta-gym-bag', 'SPORTA Gym Bag', 'حقيبة سبورتا الرياضية', 'Duffel with shoe compartment.', 'حقيبة رياضية بجيب للأحذية.', 12.000, 'accessories', true),
  ('shaker-bottle', 'Protein Shaker 700ml', 'شيكر بروتين ٧٠٠ مل', 'Leak-proof shaker with mixer.', 'شيكر محكم الإغلاق مع خلاط.', 3.500, 'accessories', true),
  ('lifting-straps', 'Lifting Straps', 'أربطة رفع الأثقال', 'Padded cotton lifting straps.', 'أربطة رفع قطنية مبطّنة.', 4.500, 'accessories', true),
  ('sporta-socks-3pack', 'SPORTA Socks (3 pack)', 'جوارب سبورتا (٣ أزواج)', 'Cushioned crew training socks.', 'جوارب تدريب مبطّنة.', 5.000, 'accessories', true),
  ('gymshark-phone-strap', 'Gymshark Phone Strap', 'علاقة جوال جيمشارك', 'Running arm phone strap.', 'حزام ذراع للجوال أثناء الجري.', 5.500, 'accessories', true)
on conflict (slug) do update set
  name_en  = excluded.name_en,
  name_ar  = excluded.name_ar,
  desc_en  = excluded.desc_en,
  desc_ar  = excluded.desc_ar,
  price    = excluded.price,
  category = excluded.category,
  active   = excluded.active,
  -- Never clobber a real photo URL with the placeholder's NULL. Once a product
  -- has artwork, re-running the seed leaves it alone.
  image    = coalesce(public.products.image, excluded.image);

-- What the catalogue now looks like to checkout.
select count(*) filter (where active) as active_products,
       min(price) as cheapest, max(price) as dearest
from public.products;
