-- Sporta — complete Supabase setup, in one file.
--
-- HOW TO RUN
--   Supabase dashboard -> SQL Editor -> New query -> paste all of this -> Run.
--
-- Safe to run again at any time. Every statement is idempotent: tables are
-- created only if missing, policies and functions are replaced, and products
-- match on slug so prices update in place and nothing is duplicated.
--
-- It is ONE file because the parts must run in order, and running them out of
-- order fails silently: the shop still renders, and every checkout is refused.
--
-- The last statement prints a report. Read it — it says what is set up and what
-- is still missing.
--
-- GENERATED by scripts/generate-setup-sql.mjs. Do not hand-edit; change the
-- file it came from and regenerate.

-- ==========================================================================
-- schema.sql — Tables, row-level security and the public read policy
-- ==========================================================================

-- Sporta — products/orders schema with SERVER-SIDE price authority + RLS.
-- Run in Supabase SQL editor. The client can never set the price it pays:
-- item prices are copied from the products table by a trigger, and the order
-- amount is recomputed server-side from the items.

-- ============================ TABLES ============================

create table if not exists public.products (
  id         uuid primary key default gen_random_uuid(),
  slug       text unique not null,
  name_en    text not null,
  name_ar    text not null,
  desc_en    text,
  desc_ar    text,
  price      numeric(10,3) not null check (price >= 0),  -- KWD, source of truth
  category   text,
  image      text,
  active     boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id             uuid primary key default gen_random_uuid(),
  track_id       text unique not null,
  amount         numeric(10,3) not null default 0,   -- computed by trigger, NOT client
  payment_status text not null default 'pending'
                 check (payment_status in ('pending','paid','failed')),
  cbk_status text, cbk_message text, cbk_paymentid text, cbk_transaction text,
  cbk_authcode text, cbk_reference text, cbk_receipt text, cbk_paytype text,
  paid_at    timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id         uuid primary key default gen_random_uuid(),
  order_id   uuid not null references public.orders(id) on delete cascade,
  product_id uuid not null references public.products(id),
  qty        int  not null check (qty > 0),
  unit_price numeric(10,3) not null default 0          -- set server-side by trigger
);

create index if not exists idx_order_items_order on public.order_items(order_id);

-- ===================== SERVER-SIDE PRICING ======================

-- On item insert, copy the authoritative price from products (ignore any
-- client-supplied unit_price) and reject inactive/unknown products.
create or replace function public.set_item_price()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  select price into new.unit_price
  from public.products
  where id = new.product_id and active = true;
  if new.unit_price is null then
    raise exception 'Invalid or inactive product %', new.product_id;
  end if;
  return new;
end $$;

drop trigger if exists trg_set_item_price on public.order_items;
create trigger trg_set_item_price
  before insert on public.order_items
  for each row execute function public.set_item_price();

-- Recompute the order total from its items after any change.
create or replace function public.recompute_order_amount()
returns trigger language plpgsql security definer set search_path = public as $$
declare oid uuid := coalesce(new.order_id, old.order_id);
begin
  update public.orders o
     set amount = coalesce((select sum(unit_price * qty)
                            from public.order_items where order_id = oid), 0)
   where o.id = oid;
  return null;
end $$;

drop trigger if exists trg_recompute_amount on public.order_items;
create trigger trg_recompute_amount
  after insert or update or delete on public.order_items
  for each row execute function public.recompute_order_amount();

-- ============================ RLS ==============================

alter table public.products    enable row level security;
alter table public.orders      enable row level security;
alter table public.order_items enable row level security;

-- Products: anyone may read active products.
drop policy if exists products_read on public.products;
create policy products_read on public.products
  for select using (active = true);

-- Authenticated admins may read ALL products and manage them (add/edit/delete).
-- (Admin routes are behind Supabase Auth; tighten to a role/claim if you add one.)
drop policy if exists products_admin_read on public.products;
create policy products_admin_read on public.products
  for select to authenticated using (true);

drop policy if exists products_admin_write on public.products;
create policy products_admin_write on public.products
  for all to authenticated using (true) with check (true);

-- Orders: clients may CREATE a pending order (amount is forced to 0 here and
-- computed by the trigger). Clients may NOT update/delete/select directly —
-- status is set server-side (service key), and reads go through an RPC.
drop policy if exists orders_insert on public.orders;
create policy orders_insert on public.orders
  for insert with check (payment_status = 'pending' and amount = 0);

-- Order items: clients may insert items for their just-created order.
drop policy if exists order_items_insert on public.order_items;
create policy order_items_insert on public.order_items
  for insert with check (true);

-- ===================== SAFE STATUS LOOKUP =======================

-- The result page reads status via this RPC (no broad table SELECT exposure).
create or replace function public.get_order_status(p_track_id text)
returns table (track_id text, amount numeric, payment_status text)
language sql stable security definer set search_path = public as $$
  select track_id, amount, payment_status
  from public.orders where track_id = p_track_id
$$;

revoke all on function public.get_order_status(text) from public;
grant execute on function public.get_order_status(text) to anon, authenticated;

-- ================= (optional) seed sample products ==============
-- insert into public.products (slug,name_en,name_ar,price,category,active) values
--   ('pro-match-ball','Pro Match Football','كرة قدم احترافية',18.500,'football',true);


-- ==========================================================================
-- admin-migration.sql — Admin reads, order stats and the fulfilment fields
-- ==========================================================================

-- Sporta — admin console migration.
-- Run this in the Supabase SQL editor AFTER schema.sql.
-- Safe to re-run: every statement is idempotent.
--
-- Three things this fixes or adds:
--   1. 'review' is a real payment status. callback.php writes it when a payment
--      cannot be verified, but the CHECK constraint rejected it, so the write
--      failed and the order silently stayed 'pending'.
--   2. The admin can actually READ orders. Only an insert policy existed, so a
--      signed-in admin could not select a single order — which is why the
--      Orders screen was showing hardcoded sample rows.
--   3. Orders carry fulfilment state and customer details, so the admin is
--      useful for shipping and not just for watching payments arrive.

-- ============ 1. payment_status: allow 'review' ============

alter table public.orders drop constraint if exists orders_payment_status_check;
alter table public.orders
  add constraint orders_payment_status_check
  check (payment_status in ('pending', 'paid', 'failed', 'review'));

comment on column public.orders.payment_status is
  'pending | paid | failed | review. "review" means the bank may have captured '
  'the payment but the server could not verify the amount or find the order — '
  'never treat it as unpaid without checking the KNET portal first.';

-- ============ 2. fulfilment + customer columns ============

alter table public.orders
  add column if not exists fulfilment_status text not null default 'unfulfilled',
  add column if not exists fulfilled_at    timestamptz,
  add column if not exists customer_name   text,
  add column if not exists customer_phone  text,
  add column if not exists customer_area   text,
  add column if not exists customer_note   text;

alter table public.orders drop constraint if exists orders_fulfilment_status_check;
alter table public.orders
  add constraint orders_fulfilment_status_check
  check (fulfilment_status in ('unfulfilled', 'packed', 'shipped', 'delivered', 'cancelled'));

-- Stamp fulfilled_at automatically so the admin never has to set two fields.
create or replace function public.touch_fulfilled_at()
returns trigger language plpgsql as $$
begin
  if new.fulfilment_status is distinct from old.fulfilment_status then
    new.fulfilled_at := case
      when new.fulfilment_status in ('shipped', 'delivered') then now()
      else null
    end;
  end if;
  return new;
end $$;

drop trigger if exists trg_touch_fulfilled_at on public.orders;
create trigger trg_touch_fulfilled_at
  before update on public.orders
  for each row execute function public.touch_fulfilled_at();

-- The admin lists newest-first and filters by status constantly.
create index if not exists idx_orders_created  on public.orders (created_at desc);
create index if not exists idx_orders_payment  on public.orders (payment_status);
create index if not exists idx_orders_fulfil   on public.orders (fulfilment_status);

-- ============ 3. RLS: let signed-in admins read and fulfil ============
--
-- Anonymous visitors still cannot select orders at all — the storefront reads a
-- single order through the get_order_status RPC. These policies apply only to
-- the `authenticated` role, i.e. someone who signed in to /admin.
--
-- If you later add more Supabase users who should NOT see orders, tighten the
-- USING clause to a claim, e.g.  using (auth.jwt() ->> 'role' = 'admin').

drop policy if exists orders_admin_read on public.orders;
create policy orders_admin_read on public.orders
  for select to authenticated using (true);

drop policy if exists order_items_admin_read on public.order_items;
create policy order_items_admin_read on public.order_items
  for select to authenticated using (true);

-- Admins update fulfilment and customer details. Payment fields stay the
-- server's job (callback.php uses the service key and bypasses RLS), so the
-- WITH CHECK below refuses any admin edit that would change the money.
drop policy if exists orders_admin_update on public.orders;
create policy orders_admin_update on public.orders
  for update to authenticated
  using (true)
  with check (
    amount         = (select o.amount         from public.orders o where o.id = orders.id)
    and payment_status = (select o.payment_status from public.orders o where o.id = orders.id)
  );

-- ============ 4. dashboard counters in one round trip ============

create or replace function public.admin_order_stats()
returns table (
  paid_count        bigint,
  paid_revenue      numeric,
  pending_count     bigint,
  review_count      bigint,
  failed_count      bigint,
  unfulfilled_count bigint,
  paid_today        bigint,
  revenue_today     numeric,
  paid_7d           bigint,
  revenue_7d        numeric
)
language sql stable security definer set search_path = public as $$
  select
    count(*) filter (where payment_status = 'paid'),
    coalesce(sum(amount) filter (where payment_status = 'paid'), 0),
    count(*) filter (where payment_status = 'pending'),
    count(*) filter (where payment_status = 'review'),
    count(*) filter (where payment_status = 'failed'),
    count(*) filter (where payment_status = 'paid' and fulfilment_status = 'unfulfilled'),
    count(*) filter (where payment_status = 'paid' and paid_at >= date_trunc('day', now())),
    coalesce(sum(amount) filter (where payment_status = 'paid' and paid_at >= date_trunc('day', now())), 0),
    count(*) filter (where payment_status = 'paid' and paid_at >= now() - interval '7 days'),
    coalesce(sum(amount) filter (where payment_status = 'paid' and paid_at >= now() - interval '7 days'), 0)
  from public.orders
$$;

revoke all on function public.admin_order_stats() from public, anon;
grant execute on function public.admin_order_stats() to authenticated;

-- Daily paid revenue for the dashboard chart.
create or replace function public.admin_revenue_daily(p_days int default 14)
returns table (day date, orders bigint, revenue numeric)
language sql stable security definer set search_path = public as $$
  select d::date,
         count(o.id),
         coalesce(sum(o.amount), 0)
  from generate_series(
         date_trunc('day', now()) - ((p_days - 1) || ' days')::interval,
         date_trunc('day', now()),
         '1 day'
       ) d
  left join public.orders o
    on o.payment_status = 'paid'
   and o.paid_at >= d
   and o.paid_at <  d + interval '1 day'
  group by d
  order by d
$$;

revoke all on function public.admin_revenue_daily(int) from public, anon;
grant execute on function public.admin_revenue_daily(int) to authenticated;


-- ==========================================================================
-- checkout-migration.sql — create_order — without this every checkout fails
-- ==========================================================================

-- Sporta — checkout: capture delivery details, and fix order creation.
--
-- Run in the Supabase SQL editor AFTER schema.sql and admin-migration.sql.
-- Safe to re-run.
--
-- WHY THIS EXISTS
--
-- 1. Web checkout was broken. src/lib/checkout.js created the order with
--    `insert(...).select('id')`, which makes PostgREST use INSERT ... RETURNING.
--    Postgres applies SELECT policies to a RETURNING clause, and `orders` has
--    no SELECT policy for anon — so the insert raised
--    "new row violates row-level security policy" and rolled back. The error
--    was swallowed by a best-effort try/catch, the browser was redirected to
--    pay.php anyway, and pay.php (correctly fail-closed) answered 404 Unknown
--    order. Every web customer hit a bare 404 at the moment of payment.
--    Reproduced against a real PostgreSQL 16 with these exact policies.
--
-- 2. Orders carried no delivery details. The admin has always shown name,
--    phone and address fields, but nothing ever wrote them, so a paid order
--    could not be fulfilled.
--
-- Both are fixed by moving order creation into one SECURITY DEFINER function.
-- It runs as the owner, so RETURNING works without exposing orders to anon; it
-- validates everything server-side, where the browser cannot bypass it; and it
-- creates the order and its items in a single transaction, so a cart can never
-- half-record.

-- ============ 1. structured delivery address ============
--
-- Kuwait addresses are not street-address shaped: they are
-- governorate → area → block → street → building, plus floor/flat for
-- apartments. Storing them as separate columns keeps them sortable and
-- filterable (deliveries are routed by area) instead of one prose blob.
-- customer_area is kept as the plain area name so the existing admin screens
-- and the mobile API keep working unchanged.

alter table public.orders
  add column if not exists customer_governorate text,
  add column if not exists customer_block       text,
  add column if not exists customer_street      text,
  add column if not exists customer_building    text,
  add column if not exists customer_floor       text,
  add column if not exists customer_flat        text;

comment on column public.orders.customer_phone is
  'Normalised to 965XXXXXXXX. Kuwait mobiles are 8 digits starting 5, 6 or 9.';

create index if not exists idx_orders_area on public.orders (customer_area);

-- ============ 2. validation helpers ============

-- Kuwait mobile numbers: 8 digits beginning 5, 6 or 9. Accepts what people
-- actually type — +965, 00965, spaces, dashes — and returns the canonical
-- 965XXXXXXXX, or null if it is not a valid Kuwaiti mobile.
create or replace function public.normalise_kw_phone(p text)
returns text language plpgsql immutable as $$
declare d text;
begin
  d := regexp_replace(coalesce(p, ''), '\D', '', 'g');
  if d like '00965%' then d := substr(d, 6);
  elsif length(d) = 11 and d like '965%' then d := substr(d, 4);
  end if;
  if d ~ '^[569]\d{7}$' then return '965' || d; end if;
  return null;
end $$;

-- Trimmed, length-checked text. Raises a stable machine token the client maps
-- to a translated message — never a raw Postgres error shown to a shopper.
create or replace function public.checkout_text(
  p_value text, p_field text, p_min int, p_max int
) returns text language plpgsql immutable as $$
declare v text;
begin
  v := btrim(coalesce(p_value, ''));
  v := regexp_replace(v, '\s+', ' ', 'g');
  if length(v) < p_min then raise exception 'missing_%', p_field using errcode = 'P0001'; end if;
  if length(v) > p_max then raise exception 'too_long_%', p_field using errcode = 'P0001'; end if;
  return v;
end $$;

-- ============ 3. create_order ============
--
-- The one entry point for creating an order from an untrusted client.
--
-- Prices are never accepted from the caller: items are given as slugs, the
-- existing trg_set_item_price copies the price from products, and
-- trg_recompute_amount sets the total. The function returns that computed
-- total so the browser can show the customer the real figure and stop before
-- redirecting if it is zero.

create or replace function public.create_order(
  p_track_id text,
  p_items    jsonb,   -- [{"slug":"rheo-zip-top","qty":2}, ...]
  p_customer jsonb    -- {name, phone, governorate, area, block, street, building, floor, flat, note}
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_id     uuid;
  v_track  text;
  v_phone  text;
  v_gov    text;
  v_amount numeric;
  v_status text;
  v_count  int;
  v_item   jsonb;
  v_pid    uuid;
  v_qty    int;
begin
  -- ---- track id ----
  v_track := btrim(coalesce(p_track_id, ''));
  if v_track !~ '^[A-Za-z0-9]{6,30}$' then
    raise exception 'invalid_track_id' using errcode = 'P0001';
  end if;

  -- Idempotency. A double submit, or a customer who backs out of the bank page
  -- and retries, must not create a second order or duplicate the items.
  select o.id, o.amount, o.payment_status into v_id, v_amount, v_status
    from public.orders o where o.track_id = v_track;
  if found then
    if v_status <> 'pending' then
      raise exception 'order_not_pending' using errcode = 'P0001';
    end if;
    return jsonb_build_object('order_id', v_id, 'track_id', v_track, 'amount', v_amount);
  end if;

  -- ---- cart ----
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'empty_cart' using errcode = 'P0001';
  end if;
  if jsonb_array_length(p_items) > 50 then
    raise exception 'cart_too_large' using errcode = 'P0001';
  end if;

  -- ---- customer ----
  v_phone := public.normalise_kw_phone(p_customer ->> 'phone');
  if v_phone is null then
    raise exception 'invalid_phone' using errcode = 'P0001';
  end if;

  v_gov := btrim(coalesce(p_customer ->> 'governorate', ''));
  if v_gov not in ('capital', 'hawalli', 'farwaniya', 'mubarak-al-kabeer', 'ahmadi', 'jahra') then
    raise exception 'invalid_governorate' using errcode = 'P0001';
  end if;

  insert into public.orders (
    track_id, payment_status,
    customer_name, customer_phone, customer_governorate, customer_area,
    customer_block, customer_street, customer_building,
    customer_floor, customer_flat, customer_note
  ) values (
    v_track, 'pending',
    public.checkout_text(p_customer ->> 'name',     'name',     2, 80),
    v_phone,
    v_gov,
    public.checkout_text(p_customer ->> 'area',     'area',     2, 60),
    public.checkout_text(p_customer ->> 'block',    'block',    1, 12),
    public.checkout_text(p_customer ->> 'street',   'street',   1, 40),
    public.checkout_text(p_customer ->> 'building', 'building', 1, 24),
    nullif(btrim(coalesce(p_customer ->> 'floor', '')), ''),
    nullif(btrim(coalesce(p_customer ->> 'flat',  '')), ''),
    nullif(btrim(coalesce(p_customer ->> 'note',  '')), '')
  ) returning id into v_id;

  -- ---- items ----
  --
  -- An unknown or inactive slug raises instead of being skipped. The old code
  -- skipped it, which produced an order totalling zero and an opaque
  -- "Order has no payable amount" at the payment step. Failing here means the
  -- shopper is told the item is unavailable while they can still act on it,
  -- and the admin Catalogue screen explains why (the product is not in the
  -- database yet).
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_qty := coalesce((v_item ->> 'qty')::int, 1);
    if v_qty < 1 or v_qty > 99 then
      raise exception 'invalid_qty' using errcode = 'P0001';
    end if;
    select p.id into v_pid from public.products p
      where p.slug = (v_item ->> 'slug') and p.active = true;
    if not found then
      raise exception 'unavailable_%', coalesce(v_item ->> 'slug', '?') using errcode = 'P0001';
    end if;
    insert into public.order_items (order_id, product_id, qty) values (v_id, v_pid, v_qty);
  end loop;

  -- trg_recompute_amount has now set the total from the stored prices.
  select o.amount into v_amount from public.orders o where o.id = v_id;
  if coalesce(v_amount, 0) <= 0 then
    raise exception 'zero_amount' using errcode = 'P0001';
  end if;

  select count(*) into v_count from public.order_items where order_id = v_id;
  return jsonb_build_object(
    'order_id', v_id, 'track_id', v_track, 'amount', v_amount, 'items', v_count
  );
end $$;

revoke all on function public.create_order(text, jsonb, jsonb) from public;
grant execute on function public.create_order(text, jsonb, jsonb) to anon, authenticated;

-- ============ 4. close the direct insert path ============
--
-- With create_order in place nothing needs to insert into these tables with
-- the anon key. Dropping the policies means an attacker holding the public
-- anon key can no longer write arbitrary orders — or arbitrary personal data —
-- straight into the table, bypassing every validation above. Order creation
-- now has exactly one door, and it is guarded.
drop policy if exists orders_insert      on public.orders;
drop policy if exists order_items_insert on public.order_items;


-- ==========================================================================
-- passcode-migration.sql — Admin device quick-unlock
-- ==========================================================================

-- Sporta — admin device passcode (quick unlock).
--
-- Run in the Supabase SQL editor after schema.sql. Safe to re-run.
--
-- WHY THIS EXISTS
--
-- The admin has always called set_device_passcode, verify_device_passcode and
-- has_device_passcode, and SECURITY.md documents the feature as server-side
-- with attempt limits and lockout — but nothing created any of it. The only
-- SQL in the repo was has_device_passcode.sql, and on a fresh database that
-- file does not even load: its body reads admin_device_passcodes, which no
-- migration creates, so it fails with
--   ERROR: relation "public.admin_device_passcodes" does not exist
-- and the two GRANT statements after it fail in turn. Quick unlock was
-- non-functional on any project built from this repo.
--
-- This file supersedes has_device_passcode.sql, which has been removed: split
-- across two files, the table and the function that reads it could get out of
-- step exactly as they did.

-- crypt()/gen_salt() live in pgcrypto. Supabase usually installs it into the
-- `extensions` schema; a plain PostgreSQL puts it in public. The functions
-- below carry both on their search_path so this works either way.
create extension if not exists pgcrypto;

-- ============ 1. table ============
--
-- One row per enrolled device. The passcode itself is never stored — only a
-- bcrypt hash — so a leak of this table cannot be replayed as a login.

create table if not exists public.admin_device_passcodes (
  device_id     text primary key,
  passcode_hash text        not null,
  label         text,
  attempts      int         not null default 0,
  locked_until  timestamptz,
  created_at    timestamptz not null default now(),
  last_used_at  timestamptz
);

comment on table public.admin_device_passcodes is
  'Admin quick-unlock. Bcrypt hashes only. Reachable exclusively through the '
  'security-definer RPCs below — RLS is on with no policies, so even a leaked '
  'service key path has to go through the attempt limiter.';

-- RLS on with NO policies: the table is unreachable by any client role. Every
-- read and write goes through the SECURITY DEFINER functions, which is what
-- makes the lockout counter impossible to bypass.
alter table public.admin_device_passcodes enable row level security;

-- ============ 2. policy knobs ============

create or replace function public.passcode_max_attempts() returns int
  language sql immutable as $$ select 5 $$;

create or replace function public.passcode_lockout() returns interval
  language sql immutable as $$ select interval '5 minutes' $$;

-- ============ 3. enrol ============
--
-- Six digits, matching the admin UI, enforced here as well because the UI can
-- be bypassed. Re-enrolling replaces the hash and clears any active lockout.

create or replace function public.set_device_passcode(
  p_device_id text,
  p_passcode  text,
  p_label     text default null
) returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
begin
  if coalesce(p_device_id, '') = '' then
    raise exception 'device_id_required' using errcode = 'P0001';
  end if;
  if p_passcode !~ '^\d{6}$' then
    raise exception 'passcode_must_be_6_digits' using errcode = 'P0001';
  end if;

  insert into public.admin_device_passcodes (device_id, passcode_hash, label)
  values (p_device_id, crypt(p_passcode, gen_salt('bf', 10)), nullif(btrim(coalesce(p_label, '')), ''))
  on conflict (device_id) do update
    set passcode_hash = excluded.passcode_hash,
        label         = coalesce(excluded.label, public.admin_device_passcodes.label),
        attempts      = 0,
        locked_until  = null,
        created_at    = now();

  return jsonb_build_object('ok', true);
end $$;

-- ============ 4. verify ============
--
-- Returns exactly the shape the lock screen reads:
--   { ok, reason, attempts_left, locked_until }
--
-- The counter lives server-side. A client that reloads the page, clears
-- storage or calls the RPC directly still burns an attempt, and the lockout
-- window is wall-clock, not something the browser can wait out locally.

create or replace function public.verify_device_passcode(
  p_device_id text,
  p_passcode  text
) returns jsonb
language plpgsql security definer set search_path = public, extensions as $$
declare
  r        public.admin_device_passcodes%rowtype;
  v_max    int := public.passcode_max_attempts();
  v_ok     boolean;
begin
  select * into r from public.admin_device_passcodes
    where device_id = p_device_id for update;

  if not found then
    -- Deliberately not distinguished from a wrong code at the UI level; the
    -- reason is here for the "enrol first" path, not to enumerate devices.
    return jsonb_build_object('ok', false, 'reason', 'not_enrolled',
                              'attempts_left', null, 'locked_until', null);
  end if;

  if r.locked_until is not null and r.locked_until > now() then
    return jsonb_build_object('ok', false, 'reason', 'locked',
                              'attempts_left', 0, 'locked_until', r.locked_until);
  end if;

  -- A lockout that has expired resets the counter before this attempt counts.
  if r.locked_until is not null and r.locked_until <= now() then
    update public.admin_device_passcodes
       set attempts = 0, locked_until = null
     where device_id = p_device_id;
    r.attempts := 0;
  end if;

  v_ok := (r.passcode_hash = crypt(p_passcode, r.passcode_hash));

  if v_ok then
    update public.admin_device_passcodes
       set attempts = 0, locked_until = null, last_used_at = now()
     where device_id = p_device_id;
    return jsonb_build_object('ok', true, 'reason', null,
                              'attempts_left', v_max, 'locked_until', null);
  end if;

  update public.admin_device_passcodes
     set attempts = r.attempts + 1,
         locked_until = case when r.attempts + 1 >= v_max
                             then now() + public.passcode_lockout() else null end
   where device_id = p_device_id
   returning * into r;

  if r.locked_until is not null then
    return jsonb_build_object('ok', false, 'reason', 'locked',
                              'attempts_left', 0, 'locked_until', r.locked_until);
  end if;
  return jsonb_build_object('ok', false, 'reason', 'wrong',
                            'attempts_left', v_max - r.attempts, 'locked_until', null);
end $$;

-- ============ 5. enrolment check ============
--
-- Read-only, returns a bare boolean, and does NOT consume an attempt. The
-- admin uses it to decide between the lock screen and the enrol screen; the
-- local flag in the browser is only a hint.

create or replace function public.has_device_passcode(p_device_id text)
returns boolean
language sql stable security definer set search_path = public, extensions as $$
  select exists (
    select 1 from public.admin_device_passcodes where device_id = p_device_id
  );
$$;

-- ============ 6. grants ============
--
-- authenticated only. Quick unlock re-locks an admin who already has a
-- Supabase session — it is not a login — so anon has no business calling any
-- of these, and denying it keeps the passcode surface off the public API.

revoke all on function public.set_device_passcode(text, text, text)    from public;
revoke all on function public.verify_device_passcode(text, text)       from public;
revoke all on function public.has_device_passcode(text)                from public;

grant execute on function public.set_device_passcode(text, text, text) to authenticated;
grant execute on function public.verify_device_passcode(text, text)    to authenticated;
grant execute on function public.has_device_passcode(text)             to authenticated;


-- ==========================================================================
-- seed-products.sql — The 46 products, and retirement of anything older
-- ==========================================================================

-- Sporta — product catalogue.
--
-- GENERATED by scripts/generate-seed.mjs from sporta-html5/assets/products.js.
-- Do not hand-edit: change the catalogue and regenerate, or the site will show
-- one price while the database charges another. The database price is the one
-- that wins — create_order reads it and the browser never sends a price.
--
-- Safe to re-run. Matching is on slug, so re-running updates prices and names
-- in place and never duplicates a product.
--
-- 46 products. Generated from the catalogue, not typed by hand.

insert into public.products
  (slug, name_en, name_ar, desc_en, desc_ar, price, category, active)
values
  ('cagliari-calcio-backpack', 'Cagliari Calcio Backpack', 'حقيبة ظهر كالياري كالتشو', 'Cagliari Calcio Backpack.', 'حقيبة ظهر كالياري كالتشو.', 4.000, 'accessories', true),
  ('cagliari-calcio-backpack-navy', 'Cagliari Calcio Backpack — Navy', 'حقيبة ظهر كالياري كالتشو — كحلي', 'Cagliari Calcio Backpack in navy.', 'حقيبة ظهر كالياري كالتشو، كحلي.', 9.000, 'accessories', true),
  ('cagliari-calcio-sweatshirt-navy', 'Cagliari Calcio Sweatshirt — Navy', 'سويت شيرت كالياري كالتشو — كحلي', 'Cagliari Calcio Sweatshirt in navy.', 'سويت شيرت كالياري كالتشو، كحلي.', 10.000, 'outerwear', true),
  ('cheetahs-rugby-t-shirt', 'Cheetahs Rugby T-Shirt', 'تيشيرت تشيتاز رَغبي', 'Cheetahs Rugby T-Shirt.', 'تيشيرت تشيتاز رَغبي.', 8.000, 'men', true),
  ('cloudsoft-jacket-army-green', 'Cloudsoft Jacket — Army Green', 'جاكيت كلاودسوفت — أخضر عسكري', 'Cloudsoft Jacket in army green.', 'جاكيت كلاودسوفت، أخضر عسكري.', 10.000, 'outerwear', true),
  ('cloudsoft-jacket-cherry-red', 'Cloudsoft Jacket — Cherry Red', 'جاكيت كلاودسوفت — أحمر كرزي', 'Cloudsoft Jacket in cherry red.', 'جاكيت كلاودسوفت، أحمر كرزي.', 8.000, 'outerwear', true),
  ('cloudsoft-jacket-coffee-brown', 'Cloudsoft Jacket — Coffee Brown', 'جاكيت كلاودسوفت — بني قهوة', 'Cloudsoft Jacket in coffee brown.', 'جاكيت كلاودسوفت، بني قهوة.', 10.000, 'outerwear', true),
  ('cloudsoft-leggings-army-green', 'Cloudsoft Leggings — Army Green', 'ليقنز كلاودسوفت — أخضر عسكري', 'Cloudsoft Leggings in army green.', 'ليقنز كلاودسوفت، أخضر عسكري.', 8.000, 'women', true),
  ('cloudsoft-leggings-cherry-red', 'Cloudsoft Leggings — Cherry Red', 'ليقنز كلاودسوفت — أحمر كرزي', 'Cloudsoft Leggings in cherry red.', 'ليقنز كلاودسوفت، أحمر كرزي.', 8.000, 'women', true),
  ('cloudsoft-leggings-coffee-brown', 'Cloudsoft Leggings — Coffee Brown', 'ليقنز كلاودسوفت — بني قهوة', 'Cloudsoft Leggings in coffee brown.', 'ليقنز كلاودسوفت، بني قهوة.', 8.000, 'women', true),
  ('cloudsoft-leggings-grey', 'Cloudsoft Leggings — Grey', 'ليقنز كلاودسوفت — رمادي', 'Cloudsoft Leggings in grey.', 'ليقنز كلاودسوفت، رمادي.', 4.500, 'women', true),
  ('cloudsoft-leggings-navy', 'Cloudsoft Leggings — Navy', 'ليقنز كلاودسوفت — كحلي', 'Cloudsoft Leggings in navy.', 'ليقنز كلاودسوفت، كحلي.', 8.000, 'women', true),
  ('cloudsoft-leggings-onyx-black', 'Cloudsoft Leggings — Onyx Black', 'ليقنز كلاودسوفت — أسود أونيكس', 'Cloudsoft Leggings in onyx black.', 'ليقنز كلاودسوفت، أسود أونيكس.', 8.000, 'women', true),
  ('cloudsoft-top-grey', 'Cloudsoft Top — Grey', 'توب كلاودسوفت — رمادي', 'Cloudsoft Top in grey.', 'توب كلاودسوفت، رمادي.', 6.000, 'women', true),
  ('cloudsoft-top-navy', 'Cloudsoft Top — Navy', 'توب كلاودسوفت — كحلي', 'Cloudsoft Top in navy.', 'توب كلاودسوفت، كحلي.', 6.000, 'women', true),
  ('cloudsoft-top-onyx-black', 'Cloudsoft Top — Onyx Black', 'توب كلاودسوفت — أسود أونيكس', 'Cloudsoft Top in onyx black.', 'توب كلاودسوفت، أسود أونيكس.', 7.000, 'women', true),
  ('define-jacket-iris-purple', 'Define Jacket — Iris Purple', 'جاكيت ديفاين — بنفسجي', 'Define Jacket in iris purple.', 'جاكيت ديفاين، بنفسجي.', 10.000, 'outerwear', true),
  ('define-jacket-onyx-black', 'Define Jacket — Onyx Black', 'جاكيت ديفاين — أسود أونيكس', 'Define Jacket in onyx black.', 'جاكيت ديفاين، أسود أونيكس.', 10.000, 'outerwear', true),
  ('define-jacket-steel-grey', 'Define Jacket — Steel Grey', 'جاكيت ديفاين — رمادي فولاذي', 'Define Jacket in steel grey.', 'جاكيت ديفاين، رمادي فولاذي.', 10.000, 'outerwear', true),
  ('denver-nuggets-cap-navy', 'Denver Nuggets Cap — Navy', 'كاب دنفر ناغتس — كحلي', 'Denver Nuggets Cap in navy.', 'كاب دنفر ناغتس، كحلي.', 12.300, 'accessories', true),
  ('energy-t-shirt-red-white', 'Energy T-Shirt — Red/White', 'تيشيرت إنرجي — أحمر وأبيض', 'Energy T-Shirt in red/white.', 'تيشيرت إنرجي، أحمر وأبيض.', 5.000, 'men', true),
  ('flash-shorts-green', 'Flash Shorts — Green', 'شورت فلاش — أخضر', 'Flash Shorts in green.', 'شورت فلاش، أخضر.', 3.000, 'men', true),
  ('flash-shorts-red', 'Flash Shorts — Red', 'شورت فلاش — أحمر', 'Flash Shorts in red.', 'شورت فلاش، أحمر.', 3.000, 'men', true),
  ('gymshark-phone-strap', 'Gymshark Phone Strap', 'حزام هاتف جيمشارك', 'Gymshark Phone Strap.', 'حزام هاتف جيمشارك.', 6.500, 'accessories', true),
  ('naples-leggings-black', 'Naples Leggings — Black', 'ليقنز نابولي — أسود', 'Naples Leggings in black.', 'ليقنز نابولي، أسود.', 7.000, 'women', true),
  ('naples-sports-bra-pink', 'Naples Sports Bra — Pink', 'برا رياضية نابولي — وردي', 'Naples Sports Bra in pink.', 'برا رياضية نابولي، وردي.', 5.000, 'women', true),
  ('sculpt-jacket-black', 'Sculpt Jacket — Black', 'جاكيت سكالبت — أسود', 'Sculpt Jacket in black.', 'جاكيت سكالبت، أسود.', 10.000, 'outerwear', true),
  ('sculpt-jacket-grey', 'Sculpt Jacket — Grey', 'جاكيت سكالبت — رمادي', 'Sculpt Jacket in grey.', 'جاكيت سكالبت، رمادي.', 8.000, 'outerwear', true),
  ('sculpt-jacket-navy', 'Sculpt Jacket — Navy', 'جاكيت سكالبت — كحلي', 'Sculpt Jacket in navy.', 'جاكيت سكالبت، كحلي.', 8.000, 'outerwear', true),
  ('sculpt-jacket-taupe-brown', 'Sculpt Jacket — Taupe Brown', 'جاكيت سكالبت — بني فاتح', 'Sculpt Jacket in taupe brown.', 'جاكيت سكالبت، بني فاتح.', 6.000, 'outerwear', true),
  ('sculpt-leggings-black', 'Sculpt Leggings — Black', 'ليقنز سكالبت — أسود', 'Sculpt Leggings in black.', 'ليقنز سكالبت، أسود.', 8.000, 'women', true),
  ('sculpt-leggings-grey', 'Sculpt Leggings — Grey', 'ليقنز سكالبت — رمادي', 'Sculpt Leggings in grey.', 'ليقنز سكالبت، رمادي.', 8.000, 'women', true),
  ('sculpt-leggings-navy', 'Sculpt Leggings — Navy', 'ليقنز سكالبت — كحلي', 'Sculpt Leggings in navy.', 'ليقنز سكالبت، كحلي.', 4.200, 'women', true),
  ('sculpt-leggings-taupe-brown', 'Sculpt Leggings — Taupe Brown', 'ليقنز سكالبت — بني فاتح', 'Sculpt Leggings in taupe brown.', 'ليقنز سكالبت، بني فاتح.', 8.000, 'women', true),
  ('sculpt-top-black', 'Sculpt Top — Black', 'توب سكالبت — أسود', 'Sculpt Top in black.', 'توب سكالبت، أسود.', 6.000, 'women', true),
  ('sculpt-top-grey', 'Sculpt Top — Grey', 'توب سكالبت — رمادي', 'Sculpt Top in grey.', 'توب سكالبت، رمادي.', 8.000, 'women', true),
  ('sculpt-top-navy', 'Sculpt Top — Navy', 'توب سكالبت — كحلي', 'Sculpt Top in navy.', 'توب سكالبت، كحلي.', 8.000, 'women', true),
  ('sculpt-top-taupe-brown', 'Sculpt Top — Taupe Brown', 'توب سكالبت — بني فاتح', 'Sculpt Top in taupe brown.', 'توب سكالبت، بني فاتح.', 8.000, 'women', true),
  ('sgomma-t-shirt-navy', 'Sgomma T-Shirt — Navy', 'تيشيرت سغوما — كحلي', 'Sgomma T-Shirt in navy.', 'تيشيرت سغوما، كحلي.', 5.000, 'men', true),
  ('street-pants-navy', 'Street Pants — Navy', 'بنطال ستريت — كحلي', 'Street Pants in navy.', 'بنطال ستريت، كحلي.', 3.000, 'men', true),
  ('tekno-shorts-black', 'Tekno Shorts — Black', 'شورت تكنو — أسود', 'Tekno Shorts in black.', 'شورت تكنو، أسود.', 3.000, 'men', true),
  ('tekno-shorts-royal', 'Tekno Shorts — Royal', 'شورت تكنو — أزرق ملكي', 'Tekno Shorts in royal.', 'شورت تكنو، أزرق ملكي.', 3.000, 'men', true),
  ('vanquish-stringer-vest-white', 'Vanquish Stringer Vest — White', 'ستراينجر فانكويش — أبيض', 'Vanquish Stringer Vest in white.', 'ستراينجر فانكويش، أبيض.', 8.000, 'men', true),
  ('vanquish-t-shirt-navy-blue', 'Vanquish T-Shirt — Navy Blue', 'تيشيرت فانكويش — كحلي', 'Vanquish T-Shirt in navy blue.', 'تيشيرت فانكويش، كحلي.', 10.000, 'men', true),
  ('vanquish-t-shirt-white', 'Vanquish T-Shirt — White', 'تيشيرت فانكويش — أبيض', 'Vanquish T-Shirt in white.', 'تيشيرت فانكويش، أبيض.', 8.000, 'men', true),
  ('vanquish-tank-navy', 'Vanquish Tank — Navy', 'تانك فانكويش — كحلي', 'Vanquish Tank in navy.', 'تانك فانكويش، كحلي.', 9.000, 'men', true)
on conflict (slug) do update set
  name_en  = excluded.name_en,
  name_ar  = excluded.name_ar,
  desc_en  = excluded.desc_en,
  desc_ar  = excluded.desc_ar,
  price    = excluded.price,
  category = excluded.category,
  active   = excluded.active,
  -- Never clobber a real photo URL with the placeholder's NULL. Once a product
  -- has artwork, re-running the seed leaves it alone.
  image    = coalesce(public.products.image, excluded.image);

-- Retire anything the catalogue no longer contains.
--
-- Without this the seed only ever ADDS. Replacing the 20 placeholder products
-- with the 46 real ones would have left 66 active in the database — and the
-- shop lists from the database, not from the bundle, so twenty items that do
-- not exist would have stayed on sale.
--
-- Deactivated, never deleted: order_items.product_id references products(id),
-- so deleting a product would take the order history with it. Inactive
-- products are invisible to the shop and refused by create_order, which is
-- exactly what is wanted, and the rows stay for past orders to point at.
update public.products
   set active = false
 where active
   and slug not in ('cagliari-calcio-backpack', 'cagliari-calcio-backpack-navy', 'cagliari-calcio-sweatshirt-navy', 'cheetahs-rugby-t-shirt', 'cloudsoft-jacket-army-green', 'cloudsoft-jacket-cherry-red', 'cloudsoft-jacket-coffee-brown', 'cloudsoft-leggings-army-green', 'cloudsoft-leggings-cherry-red', 'cloudsoft-leggings-coffee-brown', 'cloudsoft-leggings-grey', 'cloudsoft-leggings-navy', 'cloudsoft-leggings-onyx-black', 'cloudsoft-top-grey', 'cloudsoft-top-navy', 'cloudsoft-top-onyx-black', 'define-jacket-iris-purple', 'define-jacket-onyx-black', 'define-jacket-steel-grey', 'denver-nuggets-cap-navy', 'energy-t-shirt-red-white', 'flash-shorts-green', 'flash-shorts-red', 'gymshark-phone-strap', 'naples-leggings-black', 'naples-sports-bra-pink', 'sculpt-jacket-black', 'sculpt-jacket-grey', 'sculpt-jacket-navy', 'sculpt-jacket-taupe-brown', 'sculpt-leggings-black', 'sculpt-leggings-grey', 'sculpt-leggings-navy', 'sculpt-leggings-taupe-brown', 'sculpt-top-black', 'sculpt-top-grey', 'sculpt-top-navy', 'sculpt-top-taupe-brown', 'sgomma-t-shirt-navy', 'street-pants-navy', 'tekno-shorts-black', 'tekno-shorts-royal', 'vanquish-stringer-vest-white', 'vanquish-t-shirt-navy-blue', 'vanquish-t-shirt-white', 'vanquish-tank-navy');

-- What the catalogue now looks like to checkout.
select count(*) filter (where active)     as active_products,
       count(*) filter (where not active) as retired_products,
       min(price) filter (where active)   as cheapest,
       max(price) filter (where active)   as dearest
from public.products;


-- ==========================================================================
-- Did it work?
-- ==========================================================================

select
  (select count(*) from public.products where active)              as products_on_sale,
  (select count(*) from public.products where not active)          as products_retired,
  (select count(*) from pg_proc where proname = 'create_order')    as checkout_function,
  (select count(*) from pg_proc where proname = 'verify_device_passcode') as passcode_function,
  (select count(*) from auth.users)                                as admin_users;

-- What those numbers should say:
--
--   products_on_sale    46      the catalogue. 0 means seed-products did not run.
--   products_retired     0+     old products hidden, not deleted. 0 on a new project.
--   checkout_function    1      0 means checkout will fail with "404 Unknown order".
--   passcode_function    1      0 means the admin quick-unlock screen cannot work.
--   admin_users          1+     0 means NOBODY CAN SIGN IN to /admin yet.
--                               Fix: Authentication -> Users -> Add user.
--                               Any email works; it does not need a real inbox.
