-- Sporta — COMPLETE database install, in one file.
--
-- GENERATED by scripts/make-install-sql.mjs from the four part files that
-- ship beside it. Do not edit this file; edit the part and rebuild.
--
-- HOW TO USE IT
--   hPanel -> Databases -> phpMyAdmin -> pick your database (the one named in
--   api/config.php) -> Import -> choose this file -> Go.
--
-- That is the whole database step. It replaces "import these four in this
-- exact order", which is four chances to make one mistake that fails quietly.
--
-- SAFE TO RE-RUN. Every statement is CREATE TABLE IF NOT EXISTS or an insert
-- that ignores duplicates, so importing it a second time changes nothing and
-- repairs anything missing. It does NOT delete or overwrite existing orders.
--
-- Parts, in dependency order:
--   1. schema.mysql.sql   tables, indexes and constraints
--   2. seed.mysql.sql     the catalogue and its sizes
--   3. brands.mysql.sql   the brands list
--   4. promo.mysql.sql    hero slides, settings, promotions and discounts


-- ========================================================================
-- schema.mysql.sql — tables, indexes and constraints
-- ========================================================================

-- Sporta native backend — MySQL schema.
--
-- Import once in hPanel -> Databases -> phpMyAdmin -> Import (or paste into the
-- SQL tab). Safe to re-run: everything is IF NOT EXISTS and the seed matches on
-- slug, so prices update in place and nothing duplicates.
--
-- This carries every rule the Postgres schema this shop started on carried,
-- the same decisions: DECIMAL(10,3) because KWD has three decimal places and
-- floats lose fils; sizes and fits as CHECK lists because a text column fed
-- from a JSON body must not be free storage; utf8mb4 because the catalogue is
-- Arabic and utf8mb3 silently truncates at the first 4-byte glyph.

set names utf8mb4;

create table if not exists products (
  id        int unsigned auto_increment primary key,
  slug      varchar(80)  not null unique,
  name_en   varchar(160) not null,
  name_ar   varchar(160) not null,
  desc_en   text         null,
  desc_ar   text         null,
  price     decimal(10,3) not null,
  category  varchar(40)  null,
  image     varchar(500) null,
  active    tinyint(1)   not null default 1,
  created_at timestamp   not null default current_timestamp
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists orders (
  id             int unsigned auto_increment primary key,
  track_id       varchar(30) not null unique,
  amount         decimal(10,3) not null default 0,
  payment_status varchar(10) not null default 'pending',
  payment_method varchar(10) not null default 'knet',
  fulfilment_status varchar(12) not null default 'unfulfilled',
  -- The bank's answer, written by callback.php. Same cbk_* names as the
  -- Postgres schema so the callback code differs only in its storage driver.
  cbk_status      varchar(30)  null,
  cbk_message     varchar(200) null,
  cbk_paymentid   varchar(60)  null,
  cbk_transaction varchar(60)  null,
  cbk_authcode    varchar(30)  null,
  cbk_reference   varchar(60)  null,
  cbk_receipt     varchar(60)  null,
  cbk_paytype     varchar(20)  null,
  customer_name        varchar(80) null,
  customer_phone       varchar(15) null,
  customer_governorate varchar(20) null,
  customer_area        varchar(60) null,
  customer_block       varchar(12) null,
  customer_street      varchar(40) null,
  customer_building    varchar(24) null,
  customer_floor       varchar(16) null,
  customer_flat        varchar(16) null,
  customer_note        varchar(280) null,
  paid_at    timestamp null,
  fulfilled_at timestamp null,
  created_at timestamp not null default current_timestamp,
  constraint orders_payment_status_ck  check (payment_status  in ('pending','paid','failed','review')),
  constraint orders_payment_method_ck  check (payment_method  in ('knet','tpay','cod')),
  constraint orders_fulfilment_ck      check (fulfilment_status in ('unfulfilled','packed','shipped','delivered','cancelled'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create index if not exists idx_orders_created on orders (created_at);

create table if not exists order_items (
  id         int unsigned auto_increment primary key,
  order_id   int unsigned not null,
  product_id int unsigned not null,
  qty        int not null,
  unit_price decimal(10,3) not null default 0,
  size       varchar(4) null,
  fit        varchar(10) null,
  constraint fk_items_order   foreign key (order_id)   references orders (id) on delete cascade,
  constraint fk_items_product foreign key (product_id) references products (id),
  constraint items_qty_ck  check (qty between 1 and 99),
  constraint items_size_ck check (size is null or size in ('S','M','L','XL','2XL','3XL','4XL','5XL','ONE')),
  constraint items_fit_ck  check (fit  is null or fit  in ('normal','slim','loose','oversize','boxy','tank'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create index if not exists idx_items_order on order_items (order_id);

create table if not exists product_variants (
  sku    varchar(30) not null primary key,
  slug   varchar(80) not null,
  size   varchar(4)  not null,
  stock  int not null default 0,
  -- Wholesale cost. The public stock endpoint NEVER selects this column — it
  -- is the one commercially sensitive number in the schema.
  cost_aed decimal(10,2) null,
  constraint variants_stock_ck check (stock >= 0)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create index if not exists idx_variants_slug on product_variants (slug);

create table if not exists admin_users (
  id            int unsigned auto_increment primary key,
  email         varchar(120) not null unique,
  password_hash varchar(255) not null,
  failed_attempts int not null default 0,
  locked_until  timestamp null,
  last_login_at timestamp null,
  created_at    timestamp not null default current_timestamp
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

-- The transactional outbox — see FULFILMENT.md for the design,
-- same reasoning: the message row is written in the order's own transaction so
-- an order cannot exist without its warehouse message, and sending is a
-- separate job (cron-fulfilment.php) that drains and marks.
create table if not exists fulfilment_outbox (
  id         int unsigned auto_increment primary key,
  order_id   int unsigned not null,
  kind       varchar(10) not null,
  payload    json not null,
  created_at timestamp not null default current_timestamp,
  sent_at    timestamp null,
  attempts   int not null default 0,
  last_error varchar(500) null,
  -- MySQL has no partial indexes, and a plain UNIQUE(order_id, kind) would be
  -- wrong: an order can FAIL and then be PAID on a retry of the same track id,
  -- which is legitimately two 'payment' messages. Only 'new' must be unique —
  -- one picking list per order — so a generated column carries the order_id
  -- only for 'new' rows, and the unique index ignores the NULLs on the rest.
  new_once   int unsigned generated always as (case when kind = 'new' then order_id else null end) stored,
  constraint fk_outbox_order foreign key (order_id) references orders (id) on delete cascade,
  constraint outbox_kind_ck check (kind in ('new','payment'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

-- One picking list per order, guaranteed by the index rather than by memory.
create unique index if not exists uq_outbox_new on fulfilment_outbox (new_once);

-- ---------------------------------------------------------------- brands
-- The brands the shop carries, managed from the admin: name, logo, and
-- whether the storefront shows them.
--
-- THE LOGO LIVES IN THIS TABLE, as a `data:image/...;base64,…` URL, and that
-- is deliberate. Uploading a file would mean a PHP endpoint that WRITES to the
-- web root, and this project has a standing rule against exactly that — the
-- live server once carried a sporta-deploy.php that answered to anyone on the
-- internet. A row in a table cannot be executed, cannot be fetched directly,
-- and is backed up with everything else. store_data_image() caps the size and
-- allows only png/jpeg/webp — never SVG, which can carry script.
--
-- Brands are admin-managed; the logo is a capped data: URI in the row,
-- so the admin screen cannot tell the two backends apart.
create table if not exists brands (
  id        int unsigned auto_increment primary key,
  slug      varchar(80)  not null unique,
  name_en   varchar(80)  not null,
  name_ar   varchar(80)  not null,
  -- mediumtext, not text: a 64 KB text column silently TRUNCATES a base64
  -- logo, and a truncated data URL renders as a broken image with no error
  -- anywhere. mediumtext holds 16 MB; store_data_image() caps it long before.
  logo      mediumtext   null,
  active    tinyint(1)   not null default 1,
  sort      int          not null default 0,
  created_at timestamp   not null default current_timestamp,
  updated_at timestamp   not null default current_timestamp on update current_timestamp
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

-- ===========================================================================
-- Hero slides, settings, promotions and discounts.
--
-- Byte-for-byte the same statements as promo.mysql.sql, which exists so a shop
-- set up BEFORE this feature can add it without re-importing the whole schema.
-- Both are `if not exists` / `add column if not exists`, so importing either or
-- both, in any order, any number of times, converges on the same database.
-- Keep them in step: a divergence here means a fresh install and an upgraded
-- one disagree about the shape of the shop, and only one of them is tested.
-- ===========================================================================

-- ---------------------------------------------------------------- hero slides
--
-- The image lives IN THE ROW, not as a file. That is the same rule the brand
-- logos follow and it exists because an upload endpoint has to write into the
-- web root, which this project forbids outright — the live server already had
-- one such endpoint answering to the whole internet.
--
-- But a hero photograph is two orders of magnitude bigger than a brand logo,
-- so it is NOT inlined into the storefront's JSON the way a logo is. The
-- catalogue response carries a URL; api.php?r=slide_image serves the bytes
-- with a content hash in the query string and a one-year immutable cache. The
-- home page therefore pays one cacheable image request per slide, which is
-- what it would have paid for a file, and nothing writes to disk.
create table if not exists hero_slides (
  id         int unsigned auto_increment primary key,
  sort       int          not null default 0,
  active     tinyint(1)   not null default 1,

  title_en   varchar(120) null,
  title_ar   varchar(120) null,
  subtitle_en varchar(200) null,
  subtitle_ar varchar(200) null,
  cta_label_en varchar(40) null,
  cta_label_ar varchar(40) null,
  cta_href   varchar(200) null,

  -- The bytes, base64 in a data: URI exactly as store_data_image() validates
  -- it. longtext because mediumtext (16 MB) is ample but the base64 of a large
  -- photograph plus the prefix should never be the thing that truncates.
  image      longtext     null,
  -- sha256 of the image, used as the cache-busting ?v= so a replaced photo is
  -- picked up immediately despite the immutable cache on the old URL.
  image_hash char(64)     null,
  image_w    int          null,
  image_h    int          null,

  -- Where the subject sits, as percentages. This is the "area" control: the
  -- slide crops to fill, so a subject near an edge gets cut without it.
  focal_x    tinyint unsigned not null default 50,
  focal_y    tinyint unsigned not null default 50,

  created_at timestamp    not null default current_timestamp,
  updated_at timestamp    not null default current_timestamp on update current_timestamp,
  constraint hero_focal_x_ck check (focal_x between 0 and 100),
  constraint hero_focal_y_ck check (focal_y between 0 and 100)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create index if not exists idx_hero_sort on hero_slides (active, sort);

-- ------------------------------------------------------------------- settings
--
-- Small, named pieces of site configuration the owner changes without a
-- deploy: the slider's speed, whether it shuffles, how tall it is, and the
-- promo bar's text. A key/value table rather than a column per setting, so
-- adding one is an INSERT and not a migration on a live shop.
--
-- The value is JSON so a setting can be a record (the promo bar is bilingual
-- and scheduled) without inventing a table for each.
create table if not exists settings (
  name       varchar(40) primary key,
  value      text        not null,
  updated_at timestamp   not null default current_timestamp on update current_timestamp
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

-- Defaults that match what the site does today, so importing this changes
-- nothing until the owner edits it. 6500 ms is the interval HeroSlider shipped
-- with; 'tall' is its current height.
insert into settings (name, value) values
  ('hero', '{"speed_ms":6500,"shuffle":false,"size":"tall","autoplay":true}'),
  ('promo_bar', '{"enabled": true, "text_en": "Same-day delivery in Kuwait · KNET, cards & cash on delivery", "text_ar": "توصيل في نفس اليوم داخل الكويت · كي نت والبطاقات والدفع عند الاستلام", "href": "", "starts_at": null, "ends_at": null}')
on duplicate key update name = name;   -- never clobber a value already set

-- ------------------------------------------------- promotions on the products
--
-- A sale price alongside the real one, so the shop can show "was 12.000, now
-- 9.000" and go back afterwards without anybody retyping the original. The
-- window may be open-ended at either end: no start = live now, no end = until
-- switched off.
--
-- `if not exists` on add column is MariaDB 10.2+ and MySQL 8.0.29+; Hostinger
-- runs MariaDB, and re-running this file is therefore safe.
alter table products add column if not exists sale_price     decimal(10,3) null after price;
alter table products add column if not exists sale_starts_at datetime      null after sale_price;
alter table products add column if not exists sale_ends_at   datetime      null after sale_starts_at;
alter table products add column if not exists featured       tinyint(1)    not null default 0;
alter table products add column if not exists featured_sort  int           not null default 0;

create index if not exists idx_products_featured on products (featured, featured_sort);

-- --------------------------------------------------------------- rate limiting
--
-- A fixed-window counter, keyed by a HASH of bucket + client IP. It exists for
-- `?r=discount`, which is a public endpoint that answers "is this code real?"
-- — an oracle, and an unthrottled oracle is a code generator.
--
-- In MySQL rather than a cache server or a file, because this runs on shared
-- hosting where neither exists and the request is already holding a database
-- connection. The IP is hashed: this is abuse control, not a visitor log, and
-- a table of who-asked-what is a liability with no use.
--
-- Swept opportunistically by store_throttle(), so it needs no cron.
create table if not exists rate_limit (
  bucket_key   char(32)     not null,
  window_start int unsigned not null,
  hits         int unsigned not null default 0,
  primary key (bucket_key, window_start)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create index if not exists idx_rate_limit_sweep on rate_limit (window_start);

-- ------------------------------------------------------------------ discounts
--
-- Two kinds in one table, because they are the same arithmetic and splitting
-- them would mean writing the validity window, the minimum, the limits and the
-- money maths twice — and one copy would drift. `kind` says whether a customer
-- has to type it:
--
--   'code'  the customer enters it at checkout
--   'auto'  it applies itself when the order qualifies
--
-- There is no free-delivery type because delivery is already free; adding one
-- would be a discount off nothing.
create table if not exists discounts (
  id          int unsigned auto_increment primary key,
  kind        varchar(6)   not null default 'code',
  -- Stored uppercase and unique, so SAVE10 and save10 cannot both exist.
  -- NULL for automatic rules, and MySQL lets NULLs repeat in a unique index.
  code        varchar(24)  null unique,
  label       varchar(80)  not null,
  type        varchar(8)   not null default 'percent',
  -- percent: 1-90. fixed: an amount in KWD.
  value       decimal(10,3) not null,
  -- Only orders at or above this subtotal qualify. 0 = no minimum.
  min_order   decimal(10,3) not null default 0,
  -- Restrict to one category, or NULL for the whole shop. When set, the
  -- discount is computed on the qualifying lines only.
  category    varchar(40)  null,
  starts_at   datetime     null,
  ends_at     datetime     null,
  -- 0 = unlimited. used_count is incremented in the SAME transaction as the
  -- order, so two simultaneous checkouts cannot both take the last one.
  usage_limit int unsigned not null default 0,
  used_count  int unsigned not null default 0,
  active      tinyint(1)   not null default 1,
  created_at  timestamp    not null default current_timestamp,
  updated_at  timestamp    not null default current_timestamp on update current_timestamp,
  constraint discounts_kind_ck  check (kind in ('code','auto')),
  constraint discounts_type_ck  check (type in ('percent','fixed')),
  constraint discounts_value_ck check (value > 0),
  -- An automatic rule has no code; a code rule must have one. Enforced here so
  -- a bad row cannot be created by any path, admin or otherwise.
  constraint discounts_code_ck  check ((kind = 'auto' and code is null)
                                    or (kind = 'code' and code is not null))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create index if not exists idx_discounts_live on discounts (active, kind);

-- ------------------------------------------------------- what the order kept
--
-- The order records what was actually charged and why. subtotal is the price
-- of the goods before any discount; amount stays what the customer pays and
-- what the bank is asked for, so nothing in the payment path has to know that
-- discounts exist. discount_label is a snapshot: renaming or deleting a
-- discount later must not rewrite the history of an order.
alter table orders add column if not exists subtotal        decimal(10,3) not null default 0 after amount;
alter table orders add column if not exists discount_amount decimal(10,3) not null default 0 after subtotal;
alter table orders add column if not exists discount_code   varchar(24)   null after discount_amount;

-- Delivery is 1.000 KWD flat, every governorate, every payment method. Stored
-- per order rather than assumed from a constant, because an order is a record
-- of what was actually charged: if the fee changes next year, every invoice
-- and every warehouse message already written must keep saying what that
-- customer really paid. Added AFTER the discount — see STORE_DELIVERY_FEE_FILS.
alter table orders add column if not exists delivery_fee decimal(10,3) not null default 0 after discount_amount;

-- Some products cannot be exchanged at all — women's clothing, by the shop's
-- policy. A flag on the row, not a category rule: the women's Sculpt, Cloudsoft
-- and Define JACKETS live under category 'outerwear', so `category = 'women'`
-- would have left ten of them exchangeable while the matching tops were not.
-- The owner can also change one product's mind in /backends without moving it
-- between categories, which would reshuffle the shop.
alter table products add column if not exists no_exchange tinyint(1) not null default 0 after active;
alter table orders add column if not exists discount_label  varchar(200)  null after discount_code;

-- Existing orders predate discounts: their subtotal is simply their amount.
update orders set subtotal = amount where subtotal = 0 and amount > 0;

-- ------------------------------------------------------------------- indexes
--
-- Added when the shop was small and every plan looked fine. They are here for
-- the shape the tables grow into, not the shape they have:
--
--   orders          the admin's Orders screen filters by payment or fulfilment
--                   status and always sorts newest-first. Without a composite
--                   index each filtered view is a full scan plus a filesort,
--                   and it gets slower with every order ever taken.
--   fulfilment_outbox  the cron claims work every five minutes, forever, from a
--                   table that only grows — sent rows are KEPT, deliberately,
--                   because they are the record that the warehouse was told.
--                   Measured before this index: type ALL, Using filesort.
--   orders.discount_code  the guard that refuses to delete a discount an order
--                   was placed with. A scan per delete.
create index if not exists idx_orders_payment    on orders (payment_status, created_at);
create index if not exists idx_orders_fulfilment on orders (fulfilment_status, created_at);
create index if not exists idx_orders_discount   on orders (discount_code);
create index if not exists idx_outbox_pending    on fulfilment_outbox (sent_at, attempts, created_at);

-- ===========================================================================
-- WhatsApp order updates to the customer.
--
-- Byte-for-byte the same statements as whatsapp.mysql.sql, which exists so a
-- shop set up BEFORE this feature can add it without re-importing. Keep them
-- in step: a divergence means a fresh install and an upgraded one disagree
-- about the shape of the shop, and only one of them is tested.
-- ===========================================================================
alter table orders add column if not exists customer_lang varchar(2) null after customer_note;

-- ------------------------------------------------------------ whatsapp_outbox
create table if not exists whatsapp_outbox (
  id         int unsigned auto_increment primary key,
  order_id   int unsigned not null,
  -- 'confirmed' the bank settled and the order is real
  -- 'shipped'   it left the warehouse
  kind       varchar(12) not null,
  -- E.164 WITHOUT the plus, which is what the Cloud API wants: 96599887766.
  -- Snapshotted at queue time rather than joined at send time, so correcting a
  -- customer's number in the admin cannot silently redirect a message that was
  -- already queued for the old one.
  to_e164    varchar(20) not null,
  -- The approved template name and the language it was queued for, both
  -- snapshotted for the same reason: renaming a template in Meta's console
  -- must not rewrite what an already-queued message claims to be.
  template   varchar(80) not null,
  lang       varchar(5)  not null default 'ar',
  payload    json not null,
  created_at timestamp not null default current_timestamp,
  sent_at    timestamp null,
  attempts   int not null default 0,
  last_error varchar(500) null,
  -- The message id Meta hands back, so a delivery question has an answer that
  -- does not depend on anyone's memory.
  wa_message_id varchar(120) null,
  -- ONE message per order per kind, enforced by the index and not by care.
  -- A callback that fires twice — which KNET's does, through the customer's
  -- browser — must not send the customer two confirmations. Unlike the
  -- warehouse's 'payment' rows there is no legitimate repeat here: an order
  -- is confirmed once and shipped once.
  constraint uq_wa_once unique (order_id, kind),
  constraint fk_wa_order foreign key (order_id) references orders (id) on delete cascade,
  constraint wa_kind_ck check (kind in ('confirmed','shipped','review'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

-- The cron claims pending work every few minutes from a table that only grows
-- — sent rows are KEPT, because they are the record that the customer was
-- told. Same index shape, and same reason, as idx_outbox_pending.
create index if not exists idx_wa_pending on whatsapp_outbox (sent_at, attempts, created_at);

-- ===========================================================================
-- Where the order came from — ad attribution.
--
-- Byte-for-byte the same statements as attribution.mysql.sql, which exists so
-- a shop set up BEFORE this feature can add it without re-importing. Keep them
-- in step.
-- ===========================================================================
alter table orders add column if not exists utm_source   varchar(60)  null after customer_lang;
alter table orders add column if not exists utm_medium   varchar(60)  null after utm_source;
alter table orders add column if not exists utm_campaign varchar(80)  null after utm_medium;

-- The site the visitor arrived FROM, host only — never the full URL, which can
-- carry a search query or a private page path. It answers the organic half of
-- the question: an order tagged instagram.com with no campaign came from a
-- post, not from a paid ad, and those are two different budgets.
alter table orders add column if not exists referrer_host varchar(120) null after utm_campaign;

-- The owner's real question is "how did LAST MONTH's campaigns do", which is a
-- scan over dates filtered by source. Indexed accordingly.
create index if not exists idx_orders_source on orders (utm_source, created_at);

-- ===========================================================================
-- Cash-on-delivery abuse control.
--
-- Byte-for-byte the same statements as antifraud.mysql.sql, which exists so a
-- shop set up BEFORE this feature can add it without re-importing. Keep them
-- in step.
-- ===========================================================================
create table if not exists blocked_customers (
  id          int unsigned auto_increment primary key,
  -- The CANONICAL phone, exactly as store_phone() returns it: 965 followed by
  -- eight digits. Storing what the customer typed would let 99887766,
  -- +965 99887766 and 00965-99887766 be three different people to this table
  -- and one person to the courier.
  phone       varchar(15)  not null unique,
  -- 'cod' refuses cash on delivery only; 'all' refuses every order.
  --
  -- 'cod' is the default and the proportionate answer. A prepaid KNET order
  -- from a blocked number costs the shop nothing — the money is in before
  -- anything ships — so refusing it turns a serial no-show into a lost
  -- customer for no gain. 'all' is there for the case where the person is the
  -- problem rather than the payment method.
  scope       varchar(3)   not null default 'cod',
  -- Why, in the owner's words. Not decoration: in six months this is the only
  -- thing that says whether a block was a fraud pattern or a bad afternoon.
  reason      varchar(200) null,
  -- Which admin did it, for the same reason.
  blocked_by  varchar(120) null,
  created_at  timestamp    not null default current_timestamp,
  constraint blocked_scope_ck check (scope in ('cod', 'all'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

-- The open-order cap counts a phone's unsettled COD orders on every checkout,
-- so it must not be a table scan on a table that only grows.
create index if not exists idx_orders_phone_open
  on orders (customer_phone, payment_method, payment_status);

-- ===========================================================================
-- A unique reference per PAYMENT ATTEMPT, so a declined card can be retried.
--
-- Byte-for-byte the same statement as payattempt.mysql.sql, which exists so a
-- shop set up BEFORE this fix can add it without re-importing.
-- ===========================================================================
alter table orders add column if not exists pay_attempt int unsigned not null default 0
  after cbk_status;

-- ===========================================================================
-- Customer reviews, and the thank-you discount.
--
-- Byte-for-byte the same statement as reviews.mysql.sql, which exists so a
-- shop set up before this feature can add it without re-importing.
--
-- The reward is for reviewing SPORTA, not for reviewing on Google: Google's
-- policy forbids paying for reviews and the penalty is removal of the reviews
-- and possible suspension of the Business Profile. Google is invited AFTER the
-- review, with nothing attached. Any rating earns the discount — paying only
-- for good ones is review gating, which is against policy in its own right and
-- makes the shop's own average meaningless.
-- ===========================================================================
create table if not exists reviews (
  id          int unsigned auto_increment primary key,
  order_id    int unsigned not null,
  rating      tinyint unsigned not null,
  comment     varchar(1000) null,
  lang        varchar(2)   not null default 'ar',
  reward_code varchar(24)  null,
  published   tinyint(1)   not null default 0,
  created_at  timestamp    not null default current_timestamp,
  -- One row per order, in the database: the only thing standing between this
  -- and a discount-code printer, and the one place a race cannot get around.
  unique key uq_reviews_order (order_id),
  key idx_reviews_created (created_at),
  constraint reviews_rating_ck check (rating between 1 and 5),
  constraint reviews_lang_ck   check (lang in ('ar','en'))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

-- ===========================================================================
-- Which BRAND a product belongs to.
--
-- Byte-for-byte the same statements as productbrand.mysql.sql, which exists so
-- a shop set up before this feature can add it without re-importing.
--
-- A slug rather than an id, because the catalogue is re-imported from the
-- supplier's export and an auto-increment id is not stable across that.
-- Deliberately not a foreign key: deleting a brand must not delete products or
-- fail because a garment still points at it. An unmatched slug shows no brand,
-- which is what every product shows today.
-- ===========================================================================
alter table products add column if not exists brand_slug varchar(64) null after category;
create index if not exists idx_products_brand on products (brand_slug);

-- Extra photographs, comma-separated, in display order. The main `image` stays
-- first. Paths to files the owner puts on the server by hand — this shop has no
-- image upload by design.
alter table products add column if not exists images text null after image;


-- ========================================================================
-- seed.mysql.sql — the catalogue and its sizes
-- ========================================================================

-- Sporta native backend — catalogue + inventory seed.
--
-- GENERATED by scripts/generate-mysql-seed.mjs. Do not hand-edit.
-- Import in phpMyAdmin AFTER schema.mysql.sql. Safe to re-run: matching is on
-- slug / sku, so prices and names update in place and nothing duplicates.
-- Stock is NOT overwritten on re-run — the shelf count belongs to the shop,
-- not to this file.

set names utf8mb4;

insert into products (slug, name_en, name_ar, desc_en, desc_ar, price, category, active) values
  ('cagliari-calcio-backpack', 'Cagliari Calcio Backpack', 'حقيبة ظهر كالياري كالتشو', 'Cagliari Calcio Backpack.', 'حقيبة ظهر كالياري كالتشو.', 4.000, 'accessories', 1),
  ('cagliari-calcio-backpack-navy', 'Cagliari Calcio Backpack — Navy', 'حقيبة ظهر كالياري كالتشو — كحلي', 'Cagliari Calcio Backpack in navy.', 'حقيبة ظهر كالياري كالتشو، كحلي.', 9.000, 'accessories', 1),
  ('cagliari-calcio-sweatshirt-navy', 'Cagliari Calcio Sweatshirt — Navy', 'سويت شيرت كالياري كالتشو — كحلي', 'Cagliari Calcio Sweatshirt in navy.', 'سويت شيرت كالياري كالتشو، كحلي.', 10.000, 'outerwear', 1),
  ('cheetahs-rugby-t-shirt', 'Cheetahs Rugby T-Shirt', 'تيشيرت تشيتاز رَغبي', 'Cheetahs Rugby T-Shirt.', 'تيشيرت تشيتاز رَغبي.', 8.000, 'men', 1),
  ('cloudsoft-jacket-army-green', 'Cloudsoft Jacket — Army Green', 'جاكيت كلاودسوفت — أخضر عسكري', 'Cloudsoft Jacket in army green.', 'جاكيت كلاودسوفت، أخضر عسكري.', 10.000, 'outerwear', 1),
  ('cloudsoft-jacket-cherry-red', 'Cloudsoft Jacket — Cherry Red', 'جاكيت كلاودسوفت — أحمر كرزي', 'Cloudsoft Jacket in cherry red.', 'جاكيت كلاودسوفت، أحمر كرزي.', 8.000, 'outerwear', 1),
  ('cloudsoft-jacket-coffee-brown', 'Cloudsoft Jacket — Coffee Brown', 'جاكيت كلاودسوفت — بني قهوة', 'Cloudsoft Jacket in coffee brown.', 'جاكيت كلاودسوفت، بني قهوة.', 10.000, 'outerwear', 1),
  ('cloudsoft-leggings-army-green', 'Cloudsoft Leggings — Army Green', 'ليقنز كلاودسوفت — أخضر عسكري', 'Cloudsoft Leggings in army green.', 'ليقنز كلاودسوفت، أخضر عسكري.', 8.000, 'women', 1),
  ('cloudsoft-leggings-cherry-red', 'Cloudsoft Leggings — Cherry Red', 'ليقنز كلاودسوفت — أحمر كرزي', 'Cloudsoft Leggings in cherry red.', 'ليقنز كلاودسوفت، أحمر كرزي.', 8.000, 'women', 1),
  ('cloudsoft-leggings-coffee-brown', 'Cloudsoft Leggings — Coffee Brown', 'ليقنز كلاودسوفت — بني قهوة', 'Cloudsoft Leggings in coffee brown.', 'ليقنز كلاودسوفت، بني قهوة.', 8.000, 'women', 1),
  ('cloudsoft-leggings-grey', 'Cloudsoft Leggings — Grey', 'ليقنز كلاودسوفت — رمادي', 'Cloudsoft Leggings in grey.', 'ليقنز كلاودسوفت، رمادي.', 4.500, 'women', 1),
  ('cloudsoft-leggings-navy', 'Cloudsoft Leggings — Navy', 'ليقنز كلاودسوفت — كحلي', 'Cloudsoft Leggings in navy.', 'ليقنز كلاودسوفت، كحلي.', 8.000, 'women', 1),
  ('cloudsoft-leggings-onyx-black', 'Cloudsoft Leggings — Onyx Black', 'ليقنز كلاودسوفت — أسود أونيكس', 'Cloudsoft Leggings in onyx black.', 'ليقنز كلاودسوفت، أسود أونيكس.', 8.000, 'women', 1),
  ('cloudsoft-top-grey', 'Cloudsoft Top — Grey', 'توب كلاودسوفت — رمادي', 'Cloudsoft Top in grey.', 'توب كلاودسوفت، رمادي.', 6.000, 'women', 1),
  ('cloudsoft-top-navy', 'Cloudsoft Top — Navy', 'توب كلاودسوفت — كحلي', 'Cloudsoft Top in navy.', 'توب كلاودسوفت، كحلي.', 6.000, 'women', 1),
  ('cloudsoft-top-onyx-black', 'Cloudsoft Top — Onyx Black', 'توب كلاودسوفت — أسود أونيكس', 'Cloudsoft Top in onyx black.', 'توب كلاودسوفت، أسود أونيكس.', 7.000, 'women', 1),
  ('define-jacket-iris-purple', 'Define Jacket — Iris Purple', 'جاكيت ديفاين — بنفسجي', 'Define Jacket in iris purple.', 'جاكيت ديفاين، بنفسجي.', 10.000, 'outerwear', 1),
  ('define-jacket-onyx-black', 'Define Jacket — Onyx Black', 'جاكيت ديفاين — أسود أونيكس', 'Define Jacket in onyx black.', 'جاكيت ديفاين، أسود أونيكس.', 10.000, 'outerwear', 1),
  ('define-jacket-steel-grey', 'Define Jacket — Steel Grey', 'جاكيت ديفاين — رمادي فولاذي', 'Define Jacket in steel grey.', 'جاكيت ديفاين، رمادي فولاذي.', 10.000, 'outerwear', 1),
  ('denver-nuggets-cap-navy', 'Denver Nuggets Cap — Navy', 'كاب دنفر ناغتس — كحلي', 'Denver Nuggets Cap in navy.', 'كاب دنفر ناغتس، كحلي.', 12.300, 'accessories', 1),
  ('energy-t-shirt-red-white', 'Energy T-Shirt — Red/White', 'تيشيرت إنرجي — أحمر وأبيض', 'Energy T-Shirt in red/white.', 'تيشيرت إنرجي، أحمر وأبيض.', 5.000, 'men', 1),
  ('flash-shorts-green', 'Flash Shorts — Green', 'شورت فلاش — أخضر', 'Flash Shorts in green.', 'شورت فلاش، أخضر.', 3.000, 'men', 1),
  ('flash-shorts-red', 'Flash Shorts — Red', 'شورت فلاش — أحمر', 'Flash Shorts in red.', 'شورت فلاش، أحمر.', 3.000, 'men', 1),
  ('gymshark-phone-strap', 'Gymshark Phone Strap', 'حزام هاتف جيمشارك', 'Gymshark Phone Strap.', 'حزام هاتف جيمشارك.', 6.500, 'accessories', 1),
  ('naples-leggings-black', 'Naples Leggings — Black', 'ليقنز نابولي — أسود', 'Naples Leggings in black.', 'ليقنز نابولي، أسود.', 7.000, 'women', 1),
  ('naples-sports-bra-pink', 'Naples Sports Bra — Pink', 'برا رياضية نابولي — وردي', 'Naples Sports Bra in pink.', 'برا رياضية نابولي، وردي.', 5.000, 'women', 1),
  ('sculpt-jacket-black', 'Sculpt Jacket — Black', 'جاكيت سكالبت — أسود', 'Sculpt Jacket in black.', 'جاكيت سكالبت، أسود.', 10.000, 'outerwear', 1),
  ('sculpt-jacket-grey', 'Sculpt Jacket — Grey', 'جاكيت سكالبت — رمادي', 'Sculpt Jacket in grey.', 'جاكيت سكالبت، رمادي.', 8.000, 'outerwear', 1),
  ('sculpt-jacket-navy', 'Sculpt Jacket — Navy', 'جاكيت سكالبت — كحلي', 'Sculpt Jacket in navy.', 'جاكيت سكالبت، كحلي.', 8.000, 'outerwear', 1),
  ('sculpt-jacket-taupe-brown', 'Sculpt Jacket — Taupe Brown', 'جاكيت سكالبت — بني فاتح', 'Sculpt Jacket in taupe brown.', 'جاكيت سكالبت، بني فاتح.', 6.000, 'outerwear', 1),
  ('sculpt-leggings-black', 'Sculpt Leggings — Black', 'ليقنز سكالبت — أسود', 'Sculpt Leggings in black.', 'ليقنز سكالبت، أسود.', 8.000, 'women', 1),
  ('sculpt-leggings-grey', 'Sculpt Leggings — Grey', 'ليقنز سكالبت — رمادي', 'Sculpt Leggings in grey.', 'ليقنز سكالبت، رمادي.', 8.000, 'women', 1),
  ('sculpt-leggings-navy', 'Sculpt Leggings — Navy', 'ليقنز سكالبت — كحلي', 'Sculpt Leggings in navy.', 'ليقنز سكالبت، كحلي.', 4.200, 'women', 1),
  ('sculpt-leggings-taupe-brown', 'Sculpt Leggings — Taupe Brown', 'ليقنز سكالبت — بني فاتح', 'Sculpt Leggings in taupe brown.', 'ليقنز سكالبت، بني فاتح.', 8.000, 'women', 1),
  ('sculpt-top-black', 'Sculpt Top — Black', 'توب سكالبت — أسود', 'Sculpt Top in black.', 'توب سكالبت، أسود.', 6.000, 'women', 1),
  ('sculpt-top-grey', 'Sculpt Top — Grey', 'توب سكالبت — رمادي', 'Sculpt Top in grey.', 'توب سكالبت، رمادي.', 8.000, 'women', 1),
  ('sculpt-top-navy', 'Sculpt Top — Navy', 'توب سكالبت — كحلي', 'Sculpt Top in navy.', 'توب سكالبت، كحلي.', 8.000, 'women', 1),
  ('sculpt-top-taupe-brown', 'Sculpt Top — Taupe Brown', 'توب سكالبت — بني فاتح', 'Sculpt Top in taupe brown.', 'توب سكالبت، بني فاتح.', 8.000, 'women', 1),
  ('sgomma-t-shirt-navy', 'Sgomma T-Shirt — Navy', 'تيشيرت سغوما — كحلي', 'Sgomma T-Shirt in navy.', 'تيشيرت سغوما، كحلي.', 5.000, 'men', 1),
  ('street-pants-navy', 'Street Pants — Navy', 'بنطال ستريت — كحلي', 'Street Pants in navy.', 'بنطال ستريت، كحلي.', 3.000, 'men', 1),
  ('tekno-shorts-black', 'Tekno Shorts — Black', 'شورت تكنو — أسود', 'Tekno Shorts in black.', 'شورت تكنو، أسود.', 3.000, 'men', 1),
  ('tekno-shorts-royal', 'Tekno Shorts — Royal', 'شورت تكنو — أزرق ملكي', 'Tekno Shorts in royal.', 'شورت تكنو، أزرق ملكي.', 3.000, 'men', 1),
  ('vanquish-stringer-vest-white', 'Vanquish Stringer Vest — White', 'ستراينجر فانكويش — أبيض', 'Vanquish Stringer Vest in white.', 'ستراينجر فانكويش، أبيض.', 8.000, 'men', 1),
  ('vanquish-t-shirt-navy-blue', 'Vanquish T-Shirt — Navy Blue', 'تيشيرت فانكويش — كحلي', 'Vanquish T-Shirt in navy blue.', 'تيشيرت فانكويش، كحلي.', 10.000, 'men', 1),
  ('vanquish-t-shirt-white', 'Vanquish T-Shirt — White', 'تيشيرت فانكويش — أبيض', 'Vanquish T-Shirt in white.', 'تيشيرت فانكويش، أبيض.', 8.000, 'men', 1),
  ('vanquish-tank-navy', 'Vanquish Tank — Navy', 'تانك فانكويش — كحلي', 'Vanquish Tank in navy.', 'تانك فانكويش، كحلي.', 9.000, 'men', 1)
on duplicate key update
  name_en = values(name_en), name_ar = values(name_ar),
  desc_en = values(desc_en), desc_ar = values(desc_ar),
  price   = values(price),   category = values(category), active = values(active);

insert into product_variants (sku, slug, size, stock, cost_aed) values
  ('A-CSJ-AR-L', 'cloudsoft-jacket-army-green', 'L', 1, 75),
  ('A-CSJ-AR-M', 'cloudsoft-jacket-army-green', 'M', 1, 75),
  ('A-CSJ-CH-L', 'cloudsoft-jacket-cherry-red', 'L', 1, 75),
  ('A-CSJ-CO-L', 'cloudsoft-jacket-coffee-brown', 'L', 1, 75),
  ('A-CSJ-CO-M', 'cloudsoft-jacket-coffee-brown', 'M', 2, 75),
  ('A-CSL-AR-L', 'cloudsoft-leggings-army-green', 'L', 1, 70),
  ('A-CSL-AR-M', 'cloudsoft-leggings-army-green', 'M', 1, 70),
  ('A-CSL-CH-L', 'cloudsoft-leggings-cherry-red', 'L', 1, 70),
  ('A-CSL-CO-L', 'cloudsoft-leggings-coffee-brown', 'L', 1, 70),
  ('A-CSL-CO-M', 'cloudsoft-leggings-coffee-brown', 'M', 2, 70),
  ('A-CSL-GR-L', 'cloudsoft-leggings-grey', 'L', 1, 70),
  ('A-CSL-NA-L', 'cloudsoft-leggings-navy', 'L', 1, 70),
  ('A-CSL-ON-L', 'cloudsoft-leggings-onyx-black', 'L', 2, 70),
  ('A-CSL-ON-M', 'cloudsoft-leggings-onyx-black', 'M', 2, 70),
  ('A-CST-GR-L', 'cloudsoft-top-grey', 'L', 1, 72),
  ('A-CST-NA-L', 'cloudsoft-top-navy', 'L', 1, 72),
  ('A-CST-ON-L', 'cloudsoft-top-onyx-black', 'L', 2, 72),
  ('A-CST-ON-M', 'cloudsoft-top-onyx-black', 'M', 2, 72),
  ('A-DFZJ-IR-L', 'define-jacket-iris-purple', 'L', 1, 87),
  ('A-DFZJ-IR-M', 'define-jacket-iris-purple', 'M', 1, 87),
  ('A-DFZJ-ON-L', 'define-jacket-onyx-black', 'L', 1, 87),
  ('A-DFZJ-ON-M', 'define-jacket-onyx-black', 'M', 1, 87),
  ('A-DFZJ-ST-L', 'define-jacket-steel-grey', 'L', 1, 87),
  ('A-DFZJ-ST-M', 'define-jacket-steel-grey', 'M', 1, 87),
  ('A-SJ-ON-L', 'sculpt-jacket-black', 'L', 1, 69),
  ('A-SJ-GR-L', 'sculpt-jacket-grey', 'L', 1, 69),
  ('A-SJ-GR-M', 'sculpt-jacket-grey', 'M', 1, 69),
  ('A-SJ-NA-M', 'sculpt-jacket-navy', 'M', 1, 69),
  ('A-SJ-TA-L', 'sculpt-jacket-taupe-brown', 'L', 1, 69),
  ('A-SJ-TA-M', 'sculpt-jacket-taupe-brown', 'M', 1, 69),
  ('A-SL-ON-L', 'sculpt-leggings-black', 'L', 1, 66),
  ('A-SL-GR-L', 'sculpt-leggings-grey', 'L', 1, 66),
  ('A-SL-GR-M', 'sculpt-leggings-grey', 'M', 1, 66),
  ('A-SL-NA-M', 'sculpt-leggings-navy', 'M', 1, 66),
  ('A-SL-TA-L', 'sculpt-leggings-taupe-brown', 'L', 1, 66),
  ('A-SL-TA-M', 'sculpt-leggings-taupe-brown', 'M', 1, 66),
  ('A-ST-ON-L', 'sculpt-top-black', 'L', 1, 62),
  ('A-ST-GR-L', 'sculpt-top-grey', 'L', 1, 62),
  ('A-ST-GR-M', 'sculpt-top-grey', 'M', 1, 62),
  ('A-ST-NA-M', 'sculpt-top-navy', 'M', 1, 62),
  ('A-ST-TA-L', 'sculpt-top-taupe-brown', 'L', 1, 62),
  ('A-ST-TA-M', 'sculpt-top-taupe-brown', 'M', 1, 62)
on duplicate key update
  slug = values(slug), size = values(size), cost_aed = values(cost_aed);
  -- stock deliberately NOT updated: re-seeding must not overwrite the count.

-- ---------------------------------------------------------------------------
-- What cannot be exchanged. Women's clothing is excluded by the shop's policy,
-- and "women's" is not the same set as category = 'women': the Sculpt,
-- Cloudsoft, Define and Naples JACKETS are women's line but sit under
-- 'outerwear', so a category rule alone would have left ten of them
-- exchangeable while the matching tops were not.
--
-- An UPDATE rather than a column in every INSERT above, so this stays readable
-- and re-running the seed cannot half-apply it. The owner can override any
-- single product afterwards in /backends.
update products set no_exchange = 1 where category = 'women';
update products set no_exchange = 1 where category = 'outerwear'
  and (slug like 'sculpt-%' or slug like 'cloudsoft-%' or slug like 'define-%' or slug like 'naples-%');


-- ========================================================================
-- brands.mysql.sql — the brands list
-- ========================================================================

-- Sporta — the brands table, for a shop that was set up BEFORE this feature.
--
-- Fresh installs get it from schema.mysql.sql already; running this as well is
-- harmless (create table if not exists). phpMyAdmin -> your database -> Import.
--
-- It seeds the brands the catalogue already mentions, so the screen is not
-- empty on the first visit. Names only — add each logo in the admin.

set names utf8mb4;

create table if not exists brands (
  id        int unsigned auto_increment primary key,
  slug      varchar(80)  not null unique,
  name_en   varchar(80)  not null,
  name_ar   varchar(80)  not null,
  logo      mediumtext   null,
  active    tinyint(1)   not null default 1,
  sort      int          not null default 0,
  created_at timestamp   not null default current_timestamp,
  updated_at timestamp   not null default current_timestamp on update current_timestamp
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

insert into brands (slug, name_en, name_ar, sort) values
  ('sporta',       'Sporta',        'سبورتا',        0),
  ('ahed',         'AHED',          'عهد',           1),
  ('rheo',         'RHEO',          'ريو',           2),
  ('vanquish',     'Vanquish',      'فانكويش',       3),
  ('ate',          'ATE',           'إيه تي إي',     4),
  ('gymshark',     'Gymshark',      'جيم شارك',      5),
  ('eyesportwear', 'Eyesportwear',  'آي سبورت وير',  6),
  ('nba',          'NBA',           'إن بي إيه',     7)
on duplicate key update name_en = values(name_en), name_ar = values(name_ar);


-- ========================================================================
-- promo.mysql.sql — hero slides, settings, promotions and discounts
-- ========================================================================

-- Sporta — hero slides, site settings, promotions and discounts.
--
-- ADDITIVE. Fresh installs get all of this from schema.mysql.sql; running this
-- as well is harmless. phpMyAdmin -> your database -> Import.
--
-- Money is decimal(10,3) here for the same reason it is everywhere else: KWD
-- has exactly three decimal places. Every calculation that touches it happens
-- in integer fils in PHP, never in floating point.

set names utf8mb4;

-- ---------------------------------------------------------------- hero slides
--
-- The image lives IN THE ROW, not as a file. That is the same rule the brand
-- logos follow and it exists because an upload endpoint has to write into the
-- web root, which this project forbids outright — the live server already had
-- one such endpoint answering to the whole internet.
--
-- But a hero photograph is two orders of magnitude bigger than a brand logo,
-- so it is NOT inlined into the storefront's JSON the way a logo is. The
-- catalogue response carries a URL; api.php?r=slide_image serves the bytes
-- with a content hash in the query string and a one-year immutable cache. The
-- home page therefore pays one cacheable image request per slide, which is
-- what it would have paid for a file, and nothing writes to disk.
create table if not exists hero_slides (
  id         int unsigned auto_increment primary key,
  sort       int          not null default 0,
  active     tinyint(1)   not null default 1,

  title_en   varchar(120) null,
  title_ar   varchar(120) null,
  subtitle_en varchar(200) null,
  subtitle_ar varchar(200) null,
  cta_label_en varchar(40) null,
  cta_label_ar varchar(40) null,
  cta_href   varchar(200) null,

  -- The bytes, base64 in a data: URI exactly as store_data_image() validates
  -- it. longtext because mediumtext (16 MB) is ample but the base64 of a large
  -- photograph plus the prefix should never be the thing that truncates.
  image      longtext     null,
  -- sha256 of the image, used as the cache-busting ?v= so a replaced photo is
  -- picked up immediately despite the immutable cache on the old URL.
  image_hash char(64)     null,
  image_w    int          null,
  image_h    int          null,

  -- Where the subject sits, as percentages. This is the "area" control: the
  -- slide crops to fill, so a subject near an edge gets cut without it.
  focal_x    tinyint unsigned not null default 50,
  focal_y    tinyint unsigned not null default 50,

  created_at timestamp    not null default current_timestamp,
  updated_at timestamp    not null default current_timestamp on update current_timestamp,
  constraint hero_focal_x_ck check (focal_x between 0 and 100),
  constraint hero_focal_y_ck check (focal_y between 0 and 100)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create index if not exists idx_hero_sort on hero_slides (active, sort);

-- ------------------------------------------------------------------- settings
--
-- Small, named pieces of site configuration the owner changes without a
-- deploy: the slider's speed, whether it shuffles, how tall it is, and the
-- promo bar's text. A key/value table rather than a column per setting, so
-- adding one is an INSERT and not a migration on a live shop.
--
-- The value is JSON so a setting can be a record (the promo bar is bilingual
-- and scheduled) without inventing a table for each.
create table if not exists settings (
  name       varchar(40) primary key,
  value      text        not null,
  updated_at timestamp   not null default current_timestamp on update current_timestamp
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

-- Defaults that match what the site does today, so importing this changes
-- nothing until the owner edits it. 6500 ms is the interval HeroSlider shipped
-- with; 'tall' is its current height.
insert into settings (name, value) values
  ('hero', '{"speed_ms":6500,"shuffle":false,"size":"tall","autoplay":true}'),
  ('promo_bar', '{"enabled": true, "text_en": "Same-day delivery in Kuwait · KNET, cards & cash on delivery", "text_ar": "توصيل في نفس اليوم داخل الكويت · كي نت والبطاقات والدفع عند الاستلام", "href": "", "starts_at": null, "ends_at": null}')
on duplicate key update name = name;   -- never clobber a value already set

-- ------------------------------------------------- promotions on the products
--
-- A sale price alongside the real one, so the shop can show "was 12.000, now
-- 9.000" and go back afterwards without anybody retyping the original. The
-- window may be open-ended at either end: no start = live now, no end = until
-- switched off.
--
-- `if not exists` on add column is MariaDB 10.2+ and MySQL 8.0.29+; Hostinger
-- runs MariaDB, and re-running this file is therefore safe.
alter table products add column if not exists sale_price     decimal(10,3) null after price;
alter table products add column if not exists sale_starts_at datetime      null after sale_price;
alter table products add column if not exists sale_ends_at   datetime      null after sale_starts_at;
alter table products add column if not exists featured       tinyint(1)    not null default 0;
alter table products add column if not exists featured_sort  int           not null default 0;

create index if not exists idx_products_featured on products (featured, featured_sort);

-- --------------------------------------------------------------- rate limiting
--
-- A fixed-window counter, keyed by a HASH of bucket + client IP. It exists for
-- `?r=discount`, which is a public endpoint that answers "is this code real?"
-- — an oracle, and an unthrottled oracle is a code generator.
--
-- In MySQL rather than a cache server or a file, because this runs on shared
-- hosting where neither exists and the request is already holding a database
-- connection. The IP is hashed: this is abuse control, not a visitor log, and
-- a table of who-asked-what is a liability with no use.
--
-- Swept opportunistically by store_throttle(), so it needs no cron.
create table if not exists rate_limit (
  bucket_key   char(32)     not null,
  window_start int unsigned not null,
  hits         int unsigned not null default 0,
  primary key (bucket_key, window_start)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create index if not exists idx_rate_limit_sweep on rate_limit (window_start);

-- ------------------------------------------------------------------ discounts
--
-- Two kinds in one table, because they are the same arithmetic and splitting
-- them would mean writing the validity window, the minimum, the limits and the
-- money maths twice — and one copy would drift. `kind` says whether a customer
-- has to type it:
--
--   'code'  the customer enters it at checkout
--   'auto'  it applies itself when the order qualifies
--
-- There is no free-delivery type because delivery is already free; adding one
-- would be a discount off nothing.
create table if not exists discounts (
  id          int unsigned auto_increment primary key,
  kind        varchar(6)   not null default 'code',
  -- Stored uppercase and unique, so SAVE10 and save10 cannot both exist.
  -- NULL for automatic rules, and MySQL lets NULLs repeat in a unique index.
  code        varchar(24)  null unique,
  label       varchar(80)  not null,
  type        varchar(8)   not null default 'percent',
  -- percent: 1-90. fixed: an amount in KWD.
  value       decimal(10,3) not null,
  -- Only orders at or above this subtotal qualify. 0 = no minimum.
  min_order   decimal(10,3) not null default 0,
  -- Restrict to one category, or NULL for the whole shop. When set, the
  -- discount is computed on the qualifying lines only.
  category    varchar(40)  null,
  starts_at   datetime     null,
  ends_at     datetime     null,
  -- 0 = unlimited. used_count is incremented in the SAME transaction as the
  -- order, so two simultaneous checkouts cannot both take the last one.
  usage_limit int unsigned not null default 0,
  used_count  int unsigned not null default 0,
  active      tinyint(1)   not null default 1,
  created_at  timestamp    not null default current_timestamp,
  updated_at  timestamp    not null default current_timestamp on update current_timestamp,
  constraint discounts_kind_ck  check (kind in ('code','auto')),
  constraint discounts_type_ck  check (type in ('percent','fixed')),
  constraint discounts_value_ck check (value > 0),
  -- An automatic rule has no code; a code rule must have one. Enforced here so
  -- a bad row cannot be created by any path, admin or otherwise.
  constraint discounts_code_ck  check ((kind = 'auto' and code is null)
                                    or (kind = 'code' and code is not null))
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create index if not exists idx_discounts_live on discounts (active, kind);

-- ------------------------------------------------------- what the order kept
--
-- The order records what was actually charged and why. subtotal is the price
-- of the goods before any discount; amount stays what the customer pays and
-- what the bank is asked for, so nothing in the payment path has to know that
-- discounts exist. discount_label is a snapshot: renaming or deleting a
-- discount later must not rewrite the history of an order.
alter table orders add column if not exists subtotal        decimal(10,3) not null default 0 after amount;
alter table orders add column if not exists discount_amount decimal(10,3) not null default 0 after subtotal;
alter table orders add column if not exists discount_code   varchar(24)   null after discount_amount;
alter table orders add column if not exists discount_label  varchar(200)  null after discount_code;

-- Existing orders predate discounts: their subtotal is simply their amount.
update orders set subtotal = amount where subtotal = 0 and amount > 0;

-- ------------------------------------------------------------------- indexes
--
-- Added when the shop was small and every plan looked fine. They are here for
-- the shape the tables grow into, not the shape they have:
--
--   orders          the admin's Orders screen filters by payment or fulfilment
--                   status and always sorts newest-first. Without a composite
--                   index each filtered view is a full scan plus a filesort,
--                   and it gets slower with every order ever taken.
--   fulfilment_outbox  the cron claims work every five minutes, forever, from a
--                   table that only grows — sent rows are KEPT, deliberately,
--                   because they are the record that the warehouse was told.
--                   Measured before this index: type ALL, Using filesort.
--   orders.discount_code  the guard that refuses to delete a discount an order
--                   was placed with. A scan per delete.
create index if not exists idx_orders_payment    on orders (payment_status, created_at);
create index if not exists idx_orders_fulfilment on orders (fulfilment_status, created_at);
create index if not exists idx_orders_discount   on orders (discount_code);
create index if not exists idx_outbox_pending    on fulfilment_outbox (sent_at, attempts, created_at);
