import 'dart:convert';
import 'package:http/http.dart' as http;
import '../models/product.dart';

/// Talks to the Sporta PHP API on Hostinger (public_html/api/).
///
/// This used to point at a second, app-only API under /knet/api/. That API is
/// gone: it queried a database the shop no longer uses, and a second order
/// path with its own pricing rules is exactly the duplication that let the two
/// payment gateways drift apart. The app now uses the SAME endpoint the
/// website does, so there is one place where an order can be created.
///
/// The server computes order totals from stored prices — the app never sends
/// a price, so totals cannot be tampered with.
class Api {
  static const base = 'https://www.sporta.com.kw/api/api.php';

  static Future<List<Product>> products() async {
    final res = await http.get(Uri.parse('$base?r=products'))
        .timeout(const Duration(seconds: 15));
    if (res.statusCode != 200) throw Exception('products ${res.statusCode}');
    // A bare JSON array, not {"products": [...]} — the shape api.php serves.
    final body = jsonDecode(utf8.decode(res.bodyBytes)) as List;
    return body
        .map((e) => Product.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  /// Creates the order server-side and returns {track_id, pay_url}.
  ///
  /// [trackId] is generated by the CALLER and must be stable for one checkout
  /// attempt: api.php treats a repeated track id as the same order and returns
  /// the existing one, so a double tap or a retry from the bank page cannot
  /// produce two orders. Six to thirty characters, letters and digits only.
  ///
  /// [customer] must carry name, phone, governorate, area, block, street and
  /// building — the server validates each and answers with a token naming the
  /// one that failed (`invalid_phone`, `missing_area`, …).
  static Future<({String trackId, String payUrl})> createOrder(
      String trackId,
      List<CartItem> items,
      Map<String, String> customer) async {
    final res = await http
        .post(Uri.parse('$base?r=order'),
            headers: {'Content-Type': 'application/json'},
            body: jsonEncode({
              'track_id': trackId,
              'payment_method': 'knet',
              'customer': customer,
              'items': items
                  .map((i) => {'slug': i.slug, 'qty': i.qty, 'size': i.size})
                  .toList(),
            }))
        .timeout(const Duration(seconds: 20));
    final j = jsonDecode(utf8.decode(res.bodyBytes)) as Map<String, dynamic>;
    if (res.statusCode != 200 || j['error'] != null) {
      throw Exception('order ${j['error'] ?? res.statusCode}');
    }
    // pay.php is given the track id ONLY. It reads the amount from the order
    // it just created, so nothing the app sends can change what is charged.
    return (
      trackId: j['track_id'] as String,
      payUrl: 'https://www.sporta.com.kw/knet/pay.php?trackid=$trackId',
    );
  }

  /// 'paid' | 'pending' | 'failed'
  static Future<String> orderStatus(String trackId) async {
    final res = await http
        .get(Uri.parse('$base?r=status&id=$trackId'))
        .timeout(const Duration(seconds: 15));
    if (res.statusCode != 200) return 'pending';
    final j = jsonDecode(res.body) as Map<String, dynamic>;
    return (j['payment_status'] ?? 'pending') as String;
  }
}
