import { chromium } from 'playwright'
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium' })
const ctx = await b.newContext({ viewport:{width:1280,height:800}, deviceScaleFactor:2, serviceWorkers:'block' })
const p = await ctx.newPage()
const errs=[]; p.on('pageerror', e=>errs.push(e.message))
await p.goto('http://127.0.0.1:8096/', { waitUntil:'networkidle' })
await p.waitForTimeout(1200)
console.log('pageerrors:', errs.length?errs.join('|'):'none')
console.log('slide imgs:', await p.locator('section[aria-roledescription=carousel] img[src*="slide_image"]').count())
console.log('h1:', JSON.stringify(await p.locator('h1').first().textContent()))
await p.screenshot({ path:'/tmp/claude-0/hero-db.png', clip:{x:0,y:0,width:1280,height:700} })
await b.close()
