// Turns data/ahed.json into the two things that consume it:
//
//   src/lib/ahed.js                        — what the storefront shows
//   supabase/ahed-inventory-migration.sql  — the stock the shop actually holds
//
//   node scripts/generate-ahed.mjs
//
// WHY GENERATED
// The AHED details arrived as a Word file of collection features and an Excel
// proforma invoice + packing slip. Retyping 42 variants — SKU, size, quantity,
// HS code, gram weight, wholesale cost — into two places would go wrong, and
// the two places would then disagree about what is in the shop. data/ahed.json
// is the transcription; everything else is derived from it.
//
// WHAT IS DELIBERATELY *NOT* GENERATED
// Retail prices. Those live in seed-products.sql and, at runtime, in
// products.price — the column create_order reads. The invoice's AED figures are
// what Sporta PAID, and they are carried here as cost only, so margin can be
// seen in the admin. Nothing in this file can move a customer-facing price.
import { readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const web = resolve(new URL('..', import.meta.url).pathname)
const src = JSON.parse(readFileSync(join(web, 'data', 'ahed.json'), 'utf8'))

const q = (s) => (s === null || s === undefined ? 'null' : `'${String(s).replace(/'/g, "''")}'`)
const j = (o) => JSON.stringify(o, null, 2).replace(/\n/g, '\n  ')

// Strip the _note keys — they explain a wording choice to whoever edits the
// source and have no business in the bundle.
const clean = (features) => features.map(({ en, ar }) => ({ en, ar }))

// Wholesale cost per SKU. Kept out of AHED_PRODUCTS so that the storefront's
// product-detail path never carries a purchase price at all.
const costBySku = Object.fromEntries(src.variants.map((v) => [v.sku, v.cost_aed]))

// ------------------------------------------------------------ src/lib/ahed.js
const collections = Object.fromEntries(
  Object.entries(src.collections).map(([id, c]) => [
    id,
    {
      name: c.name,
      fabric: c.fabric,
      garments: Object.fromEntries(
        Object.entries(c.garments).map(([g, v]) => [g, { features: clean(v.features) }]),
      ),
    },
  ]),
)

// One entry per product slug: the spec a shopper reads. Sizes are the sizes that
// were actually shipped, in order, not every size the garment exists in.
const bySlug = {}
const SIZE_ORDER = ['XS', 'S', 'M', 'L', 'XL', 'XXL']
for (const v of src.variants) {
  const p = (bySlug[v.slug] ??= {
    collection: v.collection,
    garment: v.garment,
    colour: v.colour,
    hsCode: v.hs_code,
    grams: v.grams,
    sizes: [],
    skus: {},
  })
  if (!p.sizes.includes(v.size)) p.sizes.push(v.size)
  p.skus[v.size] = v.sku
}
for (const p of Object.values(bySlug)) {
  p.sizes.sort((a, b) => SIZE_ORDER.indexOf(a) - SIZE_ORDER.indexOf(b))
}

const lib = `// AHED brand product detail — features, fabric and the shipped size range.
//
// GENERATED by scripts/generate-ahed.mjs from data/ahed.json. Do not hand-edit.
//
// This is copy and specification only. Prices are never here: the database
// column products.price is the one create_order charges from, and a detail file
// must not be able to argue with it.
export const AHED_BRAND = ${j(src.brand)}

// Wholesale was invoiced in dirhams and the shop sells in dinars, so margin
// needs a rate. Admin-only — see the note in data/ahed.json.
export const AHED_FX = ${j({ aedPerKwd: src.fx.aed_per_kwd, asOf: src.fx.as_of })}

// Wholesale cost of one piece, in KWD, or null if the SKU is not AHED. Used by
// the admin to show margin; never by anything a customer touches.
export function ahedCostKwd(sku) {
  const cost = AHED_COST_AED[sku]
  return cost == null ? null : Math.round((cost / AHED_FX.aedPerKwd) * 1000) / 1000
}

export const AHED_COST_AED = ${j(costBySku)}

export const AHED_COLLECTIONS = ${j(collections)}

export const AHED_COLOURS = ${j(src.colours)}

// slug -> { collection, garment, colour, hsCode, grams, sizes[], skus{size:sku} }
export const AHED_PRODUCTS = ${j(bySlug)}

// Everything a product page needs about an AHED item, or null if the product is
// not one. Callers stay free of the collection/garment indirection.
export function ahedDetail(slug) {
  const p = AHED_PRODUCTS[slug]
  if (!p) return null
  const collection = AHED_COLLECTIONS[p.collection]
  const garment = collection?.garments?.[p.garment]
  if (!collection || !garment) return null
  return {
    brand: AHED_BRAND,
    collection: collection.name,
    collectionId: p.collection,
    fabric: collection.fabric,
    features: garment.features,
    colour: AHED_COLOURS[colourKey(slug, p)] ?? null,
    sizes: p.sizes,
    skus: p.skus,
    hsCode: p.hsCode,
    grams: p.grams,
  }
}

// The colour is the tail of the slug after the garment — 'sculpt-top-taupe-brown'
// is taupe-brown. Read from the slug rather than stored twice, so a renamed
// product cannot end up labelled with the old colour.
function colourKey(slug, p) {
  const prefix = \`\${p.collection}-\${p.garment === 'leggings' ? 'leggings' : p.garment}-\`
  return slug.startsWith(prefix) ? slug.slice(prefix.length) : slug.split('-').slice(2).join('-')
}

export const isAhed = (slug) => Boolean(AHED_PRODUCTS[slug])
`
writeFileSync(join(web, 'src', 'lib', 'ahed.js'), lib)

// ------------------------------------------------ supabase/ahed-inventory-migration.sql
const rows = src.variants
  .map(
    (v) =>
      `  (${q(v.sku)}, ${q(v.slug)}, ${q(v.size)}, ${q(v.collection)}, ${q(v.garment)}, ` +
      `${v.received}, ${v.received}, ${q(v.hs_code)}, ${v.grams}, ${v.cost_aed})`,
  )
  .join(',\n')

const received = src.variants.reduce((n, v) => n + v.received, 0)
const sql = `-- Sporta — AHED stock, as received.
--
-- GENERATED by scripts/generate-ahed.mjs from data/ahed.json. Do not hand-edit.
-- Safe to re-run. Run AFTER seed-products.sql (every row references a product
-- slug) and after admin-allowlist-migration.sql (it needs is_admin()).
--
-- WHY THERE IS A VARIANT TABLE AT ALL
-- products holds one row per colourway and one price. It has no idea that the
-- shop owns two Onyx leggings in M and two in L, and none in S — so the size
-- buttons on a product page offered every size and the shop could sell what it
-- did not have. This table is the shipment: ${src.variants.length} variants across
-- ${new Set(src.variants.map((v) => v.slug)).size} products, ${received} pieces, one carton from ${src.supplier.city}
-- on ${src.supplier.invoice_date}.
--
-- stock vs received
--   received  what the packing slip said. A fact about the past; re-running this
--             file restores it.
--   stock     what is on the shelf now. Set once, at insert, and NEVER touched
--             again by this migration — see the ON CONFLICT clause. Re-running
--             the setup after a month of trading must not restore sold-out
--             stock to its opening figure, which is exactly what a plain
--             "do update set stock = excluded.stock" would do.
--
-- cost_aed is the wholesale price Sporta paid, for margin in the admin. It is
-- NOT a retail price and nothing reads it at checkout: create_order prices from
-- products.price and the browser never sends a price.

create table if not exists public.product_variants (
  sku        text primary key,
  slug       text not null references public.products(slug) on delete cascade,
  size       text not null,
  collection text,
  garment    text,
  stock      int  not null default 0 check (stock >= 0),
  received   int  not null default 0 check (received >= 0),
  hs_code    text,
  grams      int,
  cost_aed   numeric(10,2),
  updated_at timestamptz not null default now(),
  unique (slug, size)
);

create index if not exists idx_variants_slug on public.product_variants(slug);

comment on table public.product_variants is
  'Per-size stock for a product. Generated from the AHED packing slip; stock is '
  'maintained by the admin thereafter and is never reset by re-running setup.';

-- ============ stock the shop is holding ============
-- stock is seeded from the same figure as received, but only here, in the
-- INSERT. A row that already exists keeps whatever the owner has counted it to.
insert into public.product_variants
  (sku, slug, size, collection, garment, stock, received, hs_code, grams, cost_aed)
values
${rows}
on conflict (sku) do update set
  -- Facts from the shipment: refreshed, because a corrected packing slip should
  -- land. stock is conspicuously absent.
  slug       = excluded.slug,
  size       = excluded.size,
  collection = excluded.collection,
  garment    = excluded.garment,
  received   = excluded.received,
  hs_code    = excluded.hs_code,
  grams      = excluded.grams,
  cost_aed   = excluded.cost_aed,
  updated_at = now();

-- ============ who can see and change it ============
alter table public.product_variants enable row level security;

-- The storefront needs this: a size button must know whether that size exists.
-- Public, like products, and for the same reason — it is shop-window data.
-- stock is a count, not a secret; cost_aed IS commercially sensitive, so the
-- public read goes through a view that does not include it.
drop policy if exists variants_admin_all on public.product_variants;
create policy variants_admin_all on public.product_variants
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

create or replace view public.product_stock as
  select slug, size, sku, greatest(stock, 0) as stock, stock > 0 as in_stock
    from public.product_variants;

comment on view public.product_stock is
  'Public face of product_variants: sizes and whether they are in stock. '
  'Deliberately excludes cost_aed — the wholesale price is not shop-window data.';

grant select on public.product_stock to anon, authenticated;
revoke all on public.product_variants from anon;

-- ============ admin: read everything, and count stock ============
create or replace function public.admin_variants()
returns table (
  sku text, slug text, name_en text, size text, collection text, garment text,
  stock int, received int, cost_aed numeric, price numeric, grams int, hs_code text
)
language plpgsql stable security definer set search_path = public as $$
begin
  if not public.is_admin() then
    raise exception 'not_admin' using errcode = '42501';
  end if;
  return query
    select v.sku, v.slug, p.name_en, v.size, v.collection, v.garment,
           v.stock, v.received, v.cost_aed, p.price, v.grams, v.hs_code
      from public.product_variants v
      join public.products p on p.slug = v.slug
     order by v.slug, v.size;
end $$;

revoke all on function public.admin_variants() from public, anon;
grant execute on function public.admin_variants() to authenticated;

-- Counting stock is a single narrow door rather than an UPDATE policy, so the
-- admin can only ever move the count — not the SKU, the cost or the slug.
create or replace function public.admin_set_stock(p_sku text, p_stock int)
returns table (sku text, stock int)
language plpgsql security definer set search_path = public as $$
begin
  if not public.is_admin() then
    raise exception 'not_admin' using errcode = '42501';
  end if;
  if p_stock is null or p_stock < 0 then
    raise exception 'stock_cannot_be_negative' using errcode = 'P0001';
  end if;
  update public.product_variants v
     set stock = p_stock, updated_at = now()
   where v.sku = p_sku;
  if not found then
    raise exception 'sku_not_found' using errcode = 'P0001';
  end if;
  return query select v.sku, v.stock from public.product_variants v where v.sku = p_sku;
end $$;

revoke all on function public.admin_set_stock(text, int) from public, anon;
grant execute on function public.admin_set_stock(text, int) to authenticated;

select
  (select count(*) from public.product_variants)                   as variants,
  (select count(distinct slug) from public.product_variants)       as products_with_sizes,
  (select coalesce(sum(stock), 0) from public.product_variants)    as pieces_in_stock,
  (select count(*) from public.product_variants where stock = 0)   as sold_out_sizes;
`
writeFileSync(join(web, 'supabase', 'ahed-inventory-migration.sql'), sql)

console.log(
  `src/lib/ahed.js + supabase/ahed-inventory-migration.sql written — ` +
    `${Object.keys(bySlug).length} products, ${src.variants.length} variants, ${received} pieces`,
)
