// Turns data/ahed.json into the two things that consume it:
//
//   src/lib/ahed.js  — what the storefront shows
//
// The stock itself is loaded by dropin/php-store/seed.mysql.sql, which
// scripts/generate-mysql-seed.mjs generates from this same data/ahed.json.
//
//   node scripts/generate-ahed.mjs
//
// WHY GENERATED
// The AHED details arrived as a Word file of collection features and an Excel
// proforma invoice + packing slip. Retyping 42 variants — SKU, size, quantity,
// HS code, gram weight, wholesale cost — into the storefront and the database
// separately would go wrong, and the two would then disagree about what is in
// the shop. data/ahed.json
// is the transcription; everything else is derived from it.
//
// WHAT IS DELIBERATELY *NOT* GENERATED
// Retail prices. Those live in seed.mysql.sql and, at runtime, in
// products.price — the column create_order reads. The invoice's AED figures are
// what Sporta PAID, and they are carried here as cost only, so margin can be
// seen in the admin. Nothing in this file can move a customer-facing price.
import { readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const web = resolve(new URL('..', import.meta.url).pathname)
const src = JSON.parse(readFileSync(join(web, 'data', 'ahed.json'), 'utf8'))

const q = (s) => (s === null || s === undefined ? 'null' : `'${String(s).replace(/'/g, "''")}'`)
const j = (o) => JSON.stringify(o, null, 2).replace(/\n/g, '\n  ')

// Strip the _note keys — they explain a wording choice to whoever edits the
// source and have no business in the bundle.
const clean = (features) => features.map(({ en, ar }) => ({ en, ar }))

// Wholesale cost per SKU. Kept out of AHED_PRODUCTS so that the storefront's
// product-detail path never carries a purchase price at all.
const costBySku = Object.fromEntries(src.variants.map((v) => [v.sku, v.cost_aed]))

// ------------------------------------------------------------ src/lib/ahed.js
const collections = Object.fromEntries(
  Object.entries(src.collections).map(([id, c]) => [
    id,
    {
      name: c.name,
      fabric: c.fabric,
      garments: Object.fromEntries(
        Object.entries(c.garments).map(([g, v]) => [g, { features: clean(v.features) }]),
      ),
    },
  ]),
)

// One entry per product slug: the spec a shopper reads. Sizes are the sizes that
// were actually shipped, in order, not every size the garment exists in.
const bySlug = {}
const SIZE_ORDER = ['XS', 'S', 'M', 'L', 'XL', 'XXL']
for (const v of src.variants) {
  const p = (bySlug[v.slug] ??= {
    collection: v.collection,
    garment: v.garment,
    colour: v.colour,
    hsCode: v.hs_code,
    grams: v.grams,
    sizes: [],
    skus: {},
  })
  if (!p.sizes.includes(v.size)) p.sizes.push(v.size)
  p.skus[v.size] = v.sku
}
for (const p of Object.values(bySlug)) {
  p.sizes.sort((a, b) => SIZE_ORDER.indexOf(a) - SIZE_ORDER.indexOf(b))
}

const lib = `// AHED brand product detail — features, fabric and the shipped size range.
//
// GENERATED by scripts/generate-ahed.mjs from data/ahed.json. Do not hand-edit.
//
// This is copy and specification only. Prices are never here: the database
// column products.price is the one create_order charges from, and a detail file
// must not be able to argue with it.
export const AHED_BRAND = ${j(src.brand)}

// Wholesale was invoiced in dirhams and the shop sells in dinars, so margin
// needs a rate. Admin-only — see the note in data/ahed.json.
export const AHED_FX = ${j({ aedPerKwd: src.fx.aed_per_kwd, asOf: src.fx.as_of })}

// Wholesale cost of one piece, in KWD, or null if the SKU is not AHED. Used by
// the admin to show margin; never by anything a customer touches.
export function ahedCostKwd(sku) {
  const cost = AHED_COST_AED[sku]
  return cost == null ? null : Math.round((cost / AHED_FX.aedPerKwd) * 1000) / 1000
}

export const AHED_COST_AED = ${j(costBySku)}

export const AHED_COLLECTIONS = ${j(collections)}

export const AHED_COLOURS = ${j(src.colours)}

// slug -> { collection, garment, colour, hsCode, grams, sizes[], skus{size:sku} }
export const AHED_PRODUCTS = ${j(bySlug)}

// Everything a product page needs about an AHED item, or null if the product is
// not one. Callers stay free of the collection/garment indirection.
export function ahedDetail(slug) {
  const p = AHED_PRODUCTS[slug]
  if (!p) return null
  const collection = AHED_COLLECTIONS[p.collection]
  const garment = collection?.garments?.[p.garment]
  if (!collection || !garment) return null
  return {
    brand: AHED_BRAND,
    collection: collection.name,
    collectionId: p.collection,
    fabric: collection.fabric,
    features: garment.features,
    colour: AHED_COLOURS[colourKey(slug, p)] ?? null,
    sizes: p.sizes,
    skus: p.skus,
    hsCode: p.hsCode,
    grams: p.grams,
  }
}

// The colour is the tail of the slug after the garment — 'sculpt-top-taupe-brown'
// is taupe-brown. Read from the slug rather than stored twice, so a renamed
// product cannot end up labelled with the old colour.
function colourKey(slug, p) {
  const prefix = \`\${p.collection}-\${p.garment === 'leggings' ? 'leggings' : p.garment}-\`
  return slug.startsWith(prefix) ? slug.slice(prefix.length) : slug.split('-').slice(2).join('-')
}

export const isAhed = (slug) => Boolean(AHED_PRODUCTS[slug])
`
writeFileSync(join(web, 'src', 'lib', 'ahed.js'), lib)


console.log(
  `src/lib/ahed.js written — ` +
    `${Object.keys(bySlug).length} products, ${src.variants.length} variants`,
)
